# -*- coding: utf-8 -*-
"""
完整模型导出 - 销售和合同相关
"""
# 销售管理
from ...sales import (
    AIClarification,
    ApprovalHistory,
    ApprovalRecord,
    ApprovalWorkflow,
    ApprovalWorkflowStep,
    Contract,
    ContractAmendment,
    ContractApproval,
    ContractDeliverable,
    ContractTemplate,
    ContractTemplateVersion,
    CpqRuleSet,
    FailureCase,
    Invoice,
    InvoiceApproval,
    Lead,
    LeadFollowUp,
    LeadRequirementDetail,
    OpenItem,
    Opportunity,
    OpportunityRequirement,
    PurchaseMaterialCost,
    Quote,
    QuoteApproval,
    QuoteCostApproval,
    QuoteCostHistory,
    QuoteCostTemplate,
    QuoteItem,
    QuoteTemplate,
    QuoteTemplateVersion,
    QuoteVersion,
    ReceivableDispute,
    RequirementFreeze,
    SalesTarget,
    ScoringRule,
    TechnicalAssessment,
    MaterialCostUpdateReminder,
)

__all__ = [
    # Sales
    "Lead",
    "LeadFollowUp",
    "Opportunity",
    "OpportunityRequirement",
    "Quote",
    "QuoteVersion",
    "QuoteItem",
    "QuoteCostTemplate",
    "QuoteCostApproval",
    "QuoteCostHistory",
    "PurchaseMaterialCost",
    "MaterialCostUpdateReminder",
    "CpqRuleSet",
    "QuoteTemplate",
    "QuoteTemplateVersion",
    "ContractTemplate",
    "ContractTemplateVersion",
    "Contract",
    "ContractDeliverable",
    "ContractAmendment",
    "Invoice",
    "ReceivableDispute",
    "SalesTarget",
    "QuoteApproval",
    "ContractApproval",
    "InvoiceApproval",
    # Technical Assessment
    "TechnicalAssessment",
    "ScoringRule",
    "FailureCase",
    "LeadRequirementDetail",
    "RequirementFreeze",
    "OpenItem",
    "AIClarification",
    # Approval Workflow
    "ApprovalWorkflow",
    "ApprovalWorkflowStep",
    "ApprovalRecord",
    "ApprovalHistory",
]
