# -*- coding: utf-8 -*-
"""
枚举定义模块 - 按业务域聚合
"""

# 验收和质量
from .acceptance import (
    AcceptanceOrderStatusEnum,
    AcceptanceResultEnum,
    AcceptanceTypeEnum,
    CheckItemResultEnum,
    DispositionEnum,
    InspectionResultEnum,
    IssueRootCauseEnum,
    IssueStatusEnum,
    IssueTypeEnum,
    OutsourcingOrderStatusEnum,
    SeverityEnum,
    VendorTypeEnum,
)

# 物料相关
from .material import (
    MaterialSourceEnum,
    MaterialTypeEnum,
    PerformanceLevelEnum,
    PurchaseOrderStatusEnum,
    ReadinessAnalysisTypeEnum,
    ReadinessStatusEnum,
    ShortageAlertLevelEnum,
    ShortageStatusEnum,
    SuggestionStatusEnum,
    SuggestionTypeEnum,
    SupplierLevelEnum,
)

# 其他
from .others import (
    ActionItemStatus,
    ActiveStatusEnum,
    AlertLevelEnum,
    AlertRuleTypeEnum,
    AlertStatusEnum,
    AssessmentDecisionEnum,
    AssessmentSourceTypeEnum,
    AssessmentStatusEnum,
    AttendanceStatusEnum,
    ChecklistResultEnum,
    DataScopeEnum,
    EquipmentTypeEnum,
    FreezeTypeEnum,
    ImportanceLevelEnum,
    IssueLevelEnum,
    MaterialTypeEnumReview,
    MeetingCycleType,
    MeetingRhythmLevel,
    MeetingTypeEnum,
    OpenItemStatusEnum,
    OpenItemTypeEnum,
    ParticipantRoleEnum,
    ResponsiblePartyEnum,
    ReviewConclusionEnum,
    ReviewIssueStatusEnum,
    ReviewStatusEnum,
    ReviewTypeEnum,
    RhythmHealthStatus,
    StatusEnum,
    VerifyResultEnum,
)

# 项目相关
from .project import (
    ApprovalDecision,
    AssemblyStageEnum,
    MachineStatusEnum,
    MilestoneTypeEnum,
    PaymentStatusEnum,
    ProjectEvaluationLevelEnum,
    ProjectEvaluationStatusEnum,
    ProjectHealthEnum,
    ProjectNoveltyLevelEnum,
    ProjectStageEnum,
    TaskImportance,
    TaskPriority,
    TaskStatus,
)

# 销售相关
from .sales import (
    ContractStatusEnum,
    DisputeReasonCodeEnum,
    DisputeStatusEnum,
    EvaluationDecisionEnum,
    GateStatusEnum,
    InvoiceStatusEnum,
    InvoiceTypeEnum,
    LeadOutcomeEnum,
    LeadStatusEnum,
    LossReasonEnum,
    OpportunityStageEnum,
    PresalesLeadStatusEnum,
    QuoteStatusEnum,
    WinProbabilityLevelEnum,
)

# 阶段模板相关
from .stage import (
    CompletionMethodEnum,
    NodeTypeEnum,
    StageStatusEnum,
    TemplateProjectTypeEnum,
)

# 审批和工作流
from .workflow import (
    ApprovalActionEnum,
    ApprovalRecordStatusEnum,
    BonusCalculationStatusEnum,
    BonusDistributionStatusEnum,
    BonusTypeEnum,
    ChangeScopeEnum,
    EcnSourceTypeEnum,
    EcnStatusEnum,
    EcnTypeEnum,
    NotifyChannelEnum,
    PaymentMethodEnum,
    PriorityEnum,
    TeamBonusAllocationMethodEnum,
    WorkflowTypeEnum,
)

__all__ = [
    # 项目相关
    "ProjectStageEnum",
    "ProjectHealthEnum",
    "MachineStatusEnum",
    "MilestoneTypeEnum",
    "ProjectNoveltyLevelEnum",
    "ProjectEvaluationLevelEnum",
    "ProjectEvaluationStatusEnum",
    "PaymentStatusEnum",
    "TaskImportance",
    "TaskStatus",
    "TaskPriority",
    "ApprovalDecision",
    "AssemblyStageEnum",
    # 物料相关
    "MaterialTypeEnum",
    "MaterialSourceEnum",
    "PurchaseOrderStatusEnum",
    "SupplierLevelEnum",
    "PerformanceLevelEnum",
    "ShortageAlertLevelEnum",
    "ShortageStatusEnum",
    "ReadinessStatusEnum",
    "ReadinessAnalysisTypeEnum",
    "SuggestionTypeEnum",
    "SuggestionStatusEnum",
    # 销售相关
    "LeadStatusEnum",
    "OpportunityStageEnum",
    "GateStatusEnum",
    "QuoteStatusEnum",
    "ContractStatusEnum",
    "InvoiceStatusEnum",
    "InvoiceTypeEnum",
    "DisputeStatusEnum",
    "DisputeReasonCodeEnum",
    "PresalesLeadStatusEnum",
    "EvaluationDecisionEnum",
    "WinProbabilityLevelEnum",
    "LeadOutcomeEnum",
    "LossReasonEnum",
    # 审批和工作流
    "BonusTypeEnum",
    "BonusCalculationStatusEnum",
    "BonusDistributionStatusEnum",
    "PaymentMethodEnum",
    "TeamBonusAllocationMethodEnum",
    "EcnTypeEnum",
    "EcnSourceTypeEnum",
    "EcnStatusEnum",
    "PriorityEnum",
    "ChangeScopeEnum",
    "WorkflowTypeEnum",
    "ApprovalRecordStatusEnum",
    "ApprovalActionEnum",
    "NotifyChannelEnum",
    # 验收和质量
    "AcceptanceTypeEnum",
    "AcceptanceOrderStatusEnum",
    "AcceptanceResultEnum",
    "CheckItemResultEnum",
    "IssueTypeEnum",
    "SeverityEnum",
    "IssueStatusEnum",
    "IssueRootCauseEnum",
    "VendorTypeEnum",
    "OutsourcingOrderStatusEnum",
    "InspectionResultEnum",
    "DispositionEnum",
    # 其他
    "StatusEnum",
    "ActiveStatusEnum",
    "ReviewTypeEnum",
    "ReviewStatusEnum",
    "MeetingTypeEnum",
    "ReviewConclusionEnum",
    "ParticipantRoleEnum",
    "AttendanceStatusEnum",
    "MaterialTypeEnumReview",
    "ChecklistResultEnum",
    "IssueLevelEnum",
    "ReviewIssueStatusEnum",
    "VerifyResultEnum",
    "AssessmentSourceTypeEnum",
    "AssessmentStatusEnum",
    "AssessmentDecisionEnum",
    "FreezeTypeEnum",
    "OpenItemTypeEnum",
    "OpenItemStatusEnum",
    "ResponsiblePartyEnum",
    "ImportanceLevelEnum",
    "EquipmentTypeEnum",
    "MeetingRhythmLevel",
    "MeetingCycleType",
    "ActionItemStatus",
    "RhythmHealthStatus",
    "DataScopeEnum",
    "AlertLevelEnum",
    "AlertStatusEnum",
    "AlertRuleTypeEnum",
    # 阶段模板相关
    "NodeTypeEnum",
    "CompletionMethodEnum",
    "StageStatusEnum",
    "TemplateProjectTypeEnum",
]
