# -*- coding: utf-8 -*-
"""
项目收尾阶段定义 (S21-S22)

包含项目收尾、质保服务两个阶段
"""

from typing import Any, Dict, List

# 项目收尾阶段 (S21-S22)
CLOSURE_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S21",
            "stage_name": "项目收尾",
            "sequence": 20,
            "category": "closure",
            "estimated_days": 14,
            "description": "资料移交、培训、备品备件移交、项目归档、项目结算",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S21N01",
                    "node_name": "资料移交",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "技术资料整理、操作手册移交、维护手册移交、图纸资料移交",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["测试算法程序"],
                },
                {
                    "node_code": "S21N02",
                    "node_name": "培训",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "操作培训、维护培训、培训考核、培训记录",
                    "dependency_node_codes": ["S21N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["到货检验记录", "齐套确认单"],
                },
                {
                    "node_code": "S21N03",
                    "node_name": "备品备件移交",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "备品备件清单、备品备件交接、交接确认",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["EE", "TE"],
                    "deliverables": ["软件联调报告"],
                },
                {
                    "node_code": "S21N04",
                    "node_name": "项目归档",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "项目资料归档、项目总结报告、经验教训总结、知识库更新",
                    "dependency_node_codes": ["S21N01", "S21N02", "S21N03"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["ME"],
                    "deliverables": ["外协订单", "外协件检验记录"],
                },
                {
                    "node_code": "S21N05",
                    "node_name": "项目结算",
                    "node_type": "MILESTONE",
                    "sequence": 4,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "成本核算、利润分析、尾款催收、财务结算、项目关闭",
                    "dependency_node_codes": ["S21N04"],
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["PMC"],
                    "deliverables": ["领料单"],
                },
            ],
        },
        # ==================== 售后阶段 (阶段 22) ====================
        {
            "stage_code": "S22",
            "stage_name": "质保服务",
            "sequence": 21,
            "category": "closure",
            "estimated_days": 365,
            "description": "质保期服务、质保期问题处理、质保到期",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S22N01",
                    "node_name": "质保期服务",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 360,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "定期回访、远程支持、预防性维护、软件升级",
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["软件自检报告"],
                },
                {
                    "node_code": "S22N02",
                    "node_name": "质保期问题处理",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 0,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "问题接收、问题分析、现场维修、远程支持、备件更换、问题关闭",
                    "owner_role_code": "TE",
                    "participant_role_codes": ["SW", "EE"],
                    "deliverables": ["空载联调报告"],
                },
                {
                    "node_code": "S22N03",
                    "node_name": "质保到期",
                    "node_type": "MILESTONE",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "质保到期通知、延保方案沟通、维保合同签订、质保结束确认",
                    "dependency_node_codes": ["S22N01"],
                    "owner_role_code": "ASM",
                    "participant_role_codes": [],
                    "deliverables": ["框架装配记录"],
                },
            ],
        },
]
