# -*- coding: utf-8 -*-
"""
非标自动化测试设备项目全流程模板（22阶段）

TPL_FULL_LIFECYCLE - 完整生命周期模板
从市场开拓到质保服务的全流程管理

来源: 非标自动化测试设备项目全流程阶段节点.xlsx
"""

from typing import Any, Dict

# 完整生命周期模板（22大阶段）
FULL_LIFECYCLE_TEMPLATE: Dict[str, Any] = {
    "template_code": "TPL_FULL_LIFECYCLE",
    "template_name": "完整生命周期模板",
    "description": "非标自动化测试设备项目全流程，从市场开拓、销售、售前、项目执行到售后服务的完整22阶段管理",
    "project_type": "NEW",
    "stages": [
        # ==================== 销售阶段 (阶段 1-3, 7-8) ====================
        {
            "stage_code": "S01",
            "stage_name": "市场开拓",
            "sequence": 0,
            "category": "sales",
            "estimated_days": 30,
            "description": "市场调研、品牌推广、渠道建设",
            "is_required": False,  # 销售阶段通常可选
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S01N01",
                    "node_name": "市场调研",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "行业趋势分析、目标客户画像、竞争对手分析、潜在客户名单整理、区域市场规划",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["市场调研报告", "潜在客户名单"],
                },
                {
                    "node_code": "S01N02",
                    "node_name": "品牌推广",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "官网/公众号维护、行业展会参展、技术文章/案例发布、行业协会活动、客户参观接待",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["推广活动记录"],
                },
                {
                    "node_code": "S01N03",
                    "node_name": "渠道建设",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "代理商/合作伙伴开发、老客户转介绍激励、供应商反向推荐、行业圈子经营",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["渠道合作协议"],
                },
            ],
        },
        {
            "stage_code": "S02",
            "stage_name": "线索获取",
            "sequence": 1,
            "category": "sales",
            "estimated_days": 14,
            "description": "收集销售线索并进行初筛",
            "is_required": False,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S02N01",
                    "node_name": "线索来源",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "展会名片收集、官网询盘、400电话咨询、老客户新项目需求、转介绍、招标信息",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["线索清单"],
                },
                {
                    "node_code": "S02N02",
                    "node_name": "线索录入",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "线索信息登记、来源标注、线索分配、线索查重",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["CRM线索记录"],
                },
                {
                    "node_code": "S02N03",
                    "node_name": "线索初筛",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "客户背景初步了解、需求真实性判断、预算/时间紧迫度初判、线索评级(A/B/C/D)",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["线索评级报告"],
                },
            ],
        },
        {
            "stage_code": "S03",
            "stage_name": "商机培育",
            "sequence": 2,
            "category": "sales",
            "estimated_days": 30,
            "description": "商机挖掘、跟进和状态管理",
            "is_required": False,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S03N01",
                    "node_name": "初次接触",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "电话/微信初次沟通、需求初步了解、公司介绍/案例分享、约定拜访时间",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["沟通记录"],
                },
                {
                    "node_code": "S03N02",
                    "node_name": "需求挖掘",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "客户拜访、需求详细沟通、测试产品/样品了解、测试标准获取、产能要求、预算探询、决策链了解",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["客户拜访记录", "需求初步记录"],
                },
                {
                    "node_code": "S03N03",
                    "node_name": "商机录入",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "商机信息登记、金额预估、预计成交时间、成交概率评估、商机评级",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["CRM商机记录"],
                },
                {
                    "node_code": "S03N04",
                    "node_name": "商机跟进",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "定期跟进计划、跟进记录登记、商机状态更新、异常商机预警",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["跟进记录"],
                },
            ],
        },
        # ==================== 售前阶段 (阶段 4-6) ====================
        {
            "stage_code": "S04",
            "stage_name": "需求评审",
            "sequence": 3,
            "category": "presales",
            "estimated_days": 10,
            "description": "需求资料收集、现场考察、需求分析与评审",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S04N01",
                    "node_name": "需求资料收集",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "测试样品接收、测试标准/规范接收、产品图纸/3D模型接收、保密协议签署、样品登记入库",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["样品接收单", "保密协议", "技术资料清单"],
                },
                {
                    "node_code": "S04N02",
                    "node_name": "现场考察",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "客户现场考察、产线环境了解、上下游设备对接了解、安装空间确认、现场照片/视频记录",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["现场考察报告", "现场照片"],
                },
                {
                    "node_code": "S04N03",
                    "node_name": "需求分析",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "测试项目梳理、测试原理初判、技术难点识别、资源需求评估、初步工期估算",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["需求分析报告"],
                },
                {
                    "node_code": "S04N04",
                    "node_name": "需求评审会",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "需求评审会议召开、技术可行性评估、商务可行性评估、风险评估、评审结论",
                    "dependency_node_codes": ["S04N01", "S04N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["市场调研报告", "潜在客户名单"],
                },
            ],
        },
        {
            "stage_code": "S05",
            "stage_name": "项目初立项",
            "sequence": 4,
            "category": "presales",
            "estimated_days": 5,
            "description": "⭐售前正式投入起点：初立项申请、售前团队组建",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S05N01",
                    "node_name": "初立项申请",
                    "node_type": "APPROVAL",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "售前立项申请提交、方案工作量评估、投入资源评估、商机赢率评估、初立项审批、临时项目编号分配",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE", "PM"],
                    "deliverables": ["初立项申请单", "临时项目编号"],
                },
                {
                    "node_code": "S05N02",
                    "node_name": "售前团队组建",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "售前项目负责人指定、技术部对接人指定、资源协调确认、售前进度计划制定、售前预算确定",
                    "dependency_node_codes": ["S05N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["推广活动记录"],
                },
            ],
        },
        {
            "stage_code": "S06",
            "stage_name": "售前方案",
            "sequence": 5,
            "category": "presales",
            "estimated_days": 30,
            "description": "⭐高投入高风险阶段：技术预研、方案设计、客户沟通、方案冻结",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S06N01",
                    "node_name": "技术预研",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 7,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "测试原理研究、关键技术验证试验、可行性分析、技术风险识别、预研报告输出",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["技术预研报告", "可行性分析报告"],
                },
                {
                    "node_code": "S06N02",
                    "node_name": "概念方案设计",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "整机布局方案设计、工艺流程设计、自动化程度定义、人机交互方式确定、初步节拍估算",
                    "dependency_node_codes": ["S06N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["渠道合作协议"],
                },
                {
                    "node_code": "S06N03",
                    "node_name": "详细方案设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 7,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "机械方案设计、电气方案设计、软件方案设计、测试方案设计、关键部件选型、初步BOM估算",
                    "dependency_node_codes": ["S06N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["线索清单"],
                },
                {
                    "node_code": "S06N04",
                    "node_name": "方案内部评审",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "技术方案评审会、技术风险评估、成本初步核算、工期初步估算、方案修改完善",
                    "dependency_node_codes": ["S06N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["CRM线索记录"],
                },
                {
                    "node_code": "S06N05",
                    "node_name": "客户方案沟通",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "方案汇报PPT准备、客户技术交流会、客户反馈收集、方案修改调整、多轮沟通迭代",
                    "dependency_node_codes": ["S06N04"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["线索评级报告"],
                },
                {
                    "node_code": "S06N06",
                    "node_name": "方案冻结",
                    "node_type": "MILESTONE",
                    "sequence": 5,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "最终方案确定、客户方案认可确认、方案版本冻结、方案文档归档",
                    "dependency_node_codes": ["S06N05"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["沟通记录"],
                },
            ],
        },
        {
            "stage_code": "S07",
            "stage_name": "商务报价与投标",
            "sequence": 6,
            "category": "presales",
            "estimated_days": 14,
            "description": "成本核算、报价编制、投标准备、商务谈判",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S07N01",
                    "node_name": "成本核算",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "BOM成本详细核算、工时成本估算、外协加工成本估算、采购成本估算、差旅/安装/售后成本估算、风险成本预留、管理费用分摊、目标毛利核算",
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["SE", "FIN"],
                    "deliverables": ["成本核算表"],
                },
                {
                    "node_code": "S07N02",
                    "node_name": "报价编制",
                    "node_type": "DELIVERABLE",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "报价单编制、报价明细表、技术方案书定稿、报价内部评审、特殊折扣审批、报价文件定稿",
                    "dependency_node_codes": ["S07N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["客户拜访记录", "需求初步记录"],
                },
                {
                    "node_code": "S07N03",
                    "node_name": "投标准备",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "招标文件研读、投标资质准备、投标文件编制、技术标编制、商务标编制、投标文件内部评审、投标文件封装",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["投标文件"],
                },
                {
                    "node_code": "S07N04",
                    "node_name": "报价/投标提交",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "报价单提交客户、投标文件递交、开标参与、技术澄清/答疑、商务澄清/答疑",
                    "dependency_node_codes": ["S07N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["CRM商机记录"],
                },
                {
                    "node_code": "S07N05",
                    "node_name": "商务谈判",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "价格谈判、技术条款谈判、付款条件谈判、交期谈判、验收条款谈判、质保条款谈判、谈判记录整理",
                    "dependency_node_codes": ["S07N04"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["跟进记录"],
                },
            ],
        },
        {
            "stage_code": "S08",
            "stage_name": "中标与合同签订",
            "sequence": 7,
            "category": "presales",
            "estimated_days": 14,
            "description": "中标确认、技术协议签订、商务合同签订、首付款收取",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S08N01",
                    "node_name": "中标确认",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "中标通知书接收、中标结果确认、内部通报",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["中标通知书"],
                },
                {
                    "node_code": "S08N02",
                    "node_name": "技术协议",
                    "node_type": "DELIVERABLE",
                    "sequence": 1,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "技术协议拟定、技术协议内部评审、技术协议客户沟通、技术协议修改定稿、技术协议签署",
                    "dependency_node_codes": ["S08N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["样品接收单", "保密协议", "技术资料清单"],
                },
                {
                    "node_code": "S08N03",
                    "node_name": "商务合同",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "合同草拟、合同条款审核(商务/技术/法务)、合同修改谈判、合同定稿、合同签署、合同盖章归档",
                    "dependency_node_codes": ["S08N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["现场考察报告", "现场照片"],
                },
                {
                    "node_code": "S08N04",
                    "node_name": "首付款",
                    "node_type": "MILESTONE",
                    "sequence": 3,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "首付款发票开具、首付款跟催、首付款到账确认、财务入账确认",
                    "dependency_node_codes": ["S08N03"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["需求分析报告"],
                },
            ],
        },
        # ==================== 项目执行阶段 (阶段 9-21) ====================
        {
            "stage_code": "S09",
            "stage_name": "项目正式立项",
            "sequence": 8,
            "category": "execution",
            "estimated_days": 7,
            "description": "⭐项目正式启动：正式立项审批、项目移交、团队组建、启动会",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S09N01",
                    "node_name": "正式立项审批",
                    "node_type": "APPROVAL",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "正式立项申请、合同/首付款确认、正式项目编号分配、立项审批通过、立项通知发布",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SALES", "FIN"],
                    "deliverables": ["正式立项申请单", "项目编号"],
                },
                {
                    "node_code": "S09N02",
                    "node_name": "项目移交",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "售前资料移交(方案/图纸/样品/沟通记录)、技术协议移交、样品/图纸移交、关键风险点移交、遗留问题移交、移交确认签字",
                    "dependency_node_codes": ["S09N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES", "ME", "EE", "PM"],
                    "deliverables": ["需求评审纪要", "评审结论"],
                },
                {
                    "node_code": "S09N03",
                    "node_name": "项目团队组建",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "项目经理任命、核心团队组建(机械/电气/软件/测试)、职责分工明确、项目群组建立",
                    "dependency_node_codes": ["S09N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE", "PM"],
                    "deliverables": ["初立项申请单", "临时项目编号"],
                },
                {
                    "node_code": "S09N04",
                    "node_name": "项目启动会",
                    "node_type": "MILESTONE",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "项目启动会召开、客户需求宣贯、售前方案宣贯、里程碑计划制定、风险识别与应对、启动会议纪要签发",
                    "dependency_node_codes": ["S09N02", "S09N03"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SE", "SALES"],
                    "deliverables": ["售前团队名单", "售前计划"],
                },
                {
                    "node_code": "S09N05",
                    "node_name": "输入资料确认",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "产品图纸/3D模型确认、测试标准/规范确认、产能/节拍要求确认、接口定义确认、特殊要求确认、客户对接人确认",
                    "dependency_node_codes": ["S09N04"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["技术预研报告", "可行性分析报告"],
                },
            ],
        },
        {
            "stage_code": "S10",
            "stage_name": "详细方案设计",
            "sequence": 9,
            "category": "execution",
            "estimated_days": 10,
            "description": "方案深化、技术规格书编制、方案确认冻结",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S10N01",
                    "node_name": "方案深化",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "售前方案评估、方案优化调整、详细布局设计、详细工艺流程、详细测试方案",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["深化方案"],
                },
                {
                    "node_code": "S10N02",
                    "node_name": "技术规格书",
                    "node_type": "DELIVERABLE",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "设备技术规格书编制、测试项目清单确认、性能指标定义、验收标准拟定",
                    "dependency_node_codes": ["S10N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE"],
                    "deliverables": ["概念方案", "布局图"],
                },
                {
                    "node_code": "S10N03",
                    "node_name": "方案确认",
                    "node_type": "APPROVAL",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "详细方案内部评审、详细方案客户汇报、客户签字确认、方案冻结",
                    "dependency_node_codes": ["S10N02"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["详细技术方案", "初步BOM"],
                },
            ],
        },
        {
            "stage_code": "S11",
            "stage_name": "详细设计",
            "sequence": 10,
            "category": "execution",
            "estimated_days": 21,
            "description": "机械/电气/软件/测试方案详细设计（并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S11N01",
                    "node_name": "机械设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 14,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "总体结构设计、治具/夹具设计、运动机构设计、防护/安全设计、标准件选型、非标件出图、机械BOM输出、机械设计评审",
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["3D总装图", "2D零件图", "机械BOM"],
                },
                {
                    "node_code": "S11N02",
                    "node_name": "电气设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 1,
                    "estimated_days": 14,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "电气原理图设计、控制柜布局设计、线缆走向设计、传感器/执行器选型、PLC/运动控制选型、安全回路设计、电气BOM输出、电气设计评审",
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["电气原理图", "控制柜布局图", "电气BOM"],
                },
                {
                    "node_code": "S11N03",
                    "node_name": "软件设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 10,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "软件功能规格书、系统架构设计、接口协议定义、数据库设计、UI界面设计、软件设计评审",
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["软件设计文档", "接口协议", "UI设计稿"],
                },
                {
                    "node_code": "S11N04",
                    "node_name": "测试方案设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 3,
                    "estimated_days": 10,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "测试流程设计、测试算法设计、判定逻辑设计、数据处理方案、报表格式设计",
                    "owner_role_code": "TE",
                    "participant_role_codes": ["SW"],
                    "deliverables": ["测试方案", "测试算法说明"],
                },
                {
                    "node_code": "S11N05",
                    "node_name": "设计输出确认",
                    "node_type": "APPROVAL",
                    "sequence": 4,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "图纸会签、BOM冻结、设计变更控制启动、采购清单输出",
                    "dependency_node_codes": ["S11N01", "S11N02", "S11N03", "S11N04"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW", "PM"],
                    "deliverables": ["方案评审纪要"],
                },
            ],
        },
        {
            "stage_code": "S12",
            "stage_name": "采购与外协",
            "sequence": 11,
            "category": "execution",
            "estimated_days": 21,
            "description": "采购启动、到货管理、外协加工管理",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S12N01",
                    "node_name": "采购启动",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "采购清单分类(标准件/非标件/外购件)、供应商询价、交期确认、采购订单下达",
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["采购订单"],
                },
                {
                    "node_code": "S12N02",
                    "node_name": "到货管理",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "标准件到货检验、非标件加工跟踪、外购件到货检验、不合格品处理、物料齐套确认",
                    "dependency_node_codes": ["S12N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["方案汇报PPT", "客户沟通纪要"],
                },
                {
                    "node_code": "S12N03",
                    "node_name": "外协加工管理",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "外协图纸发放、外协进度跟踪、外协件首检、外协件入库",
                    "dependency_node_codes": ["S12N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES", "PM"],
                    "deliverables": ["冻结版技术方案", "客户确认函"],
                },
            ],
        },
        {
            "stage_code": "S13",
            "stage_name": "机械装配",
            "sequence": 12,
            "category": "execution",
            "estimated_days": 14,
            "description": "装配准备、框架装配、模块装配、机械调试（与电气/软件并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S13N01",
                    "node_name": "装配准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物料领用、工位准备、装配工艺卡确认、工装/工具准备",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["PMC"],
                    "deliverables": ["领料单"],
                },
                {
                    "node_code": "S13N02",
                    "node_name": "框架装配",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "底座安装调平、框架组装、防护罩安装、基准建立",
                    "dependency_node_codes": ["S13N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["SE", "FIN"],
                    "deliverables": ["成本核算表"],
                },
                {
                    "node_code": "S13N03",
                    "node_name": "模块装配",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "上下料机构装配、定位机构装配、测试工位装配、传输机构装配、治具安装",
                    "dependency_node_codes": ["S13N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["报价单", "报价明细表"],
                },
                {
                    "node_code": "S13N04",
                    "node_name": "机械调试",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "运动机构调试、定位精度调试、重复精度验证、干涉检查",
                    "dependency_node_codes": ["S13N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["投标文件"],
                },
                {
                    "node_code": "S13N05",
                    "node_name": "机械自检",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "装配自检、问题整改、机械完工确认",
                    "dependency_node_codes": ["S13N04"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["报价提交回执"],
                },
            ],
        },
        {
            "stage_code": "S14",
            "stage_name": "电气装配",
            "sequence": 13,
            "category": "execution",
            "estimated_days": 10,
            "description": "电气安装、电气接线、电气调试（与机械/软件并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S14N01",
                    "node_name": "电气安装",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "控制柜安装、线槽/线管布设、线缆敷设、传感器/执行器安装",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["ME"],
                    "deliverables": ["模块装配记录"],
                },
                {
                    "node_code": "S14N02",
                    "node_name": "电气接线",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "柜内接线、现场接线、接线检查、绝缘/接地测试",
                    "dependency_node_codes": ["S14N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE", "PM"],
                    "deliverables": ["谈判记录"],
                },
                {
                    "node_code": "S14N03",
                    "node_name": "电气调试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "上电前检查、分步上电测试、I/O点检、运动轴调试、安全回路验证",
                    "dependency_node_codes": ["S14N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["中标通知书"],
                },
                {
                    "node_code": "S14N04",
                    "node_name": "电气自检",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "电气功能自检、问题整改、电气完工确认",
                    "dependency_node_codes": ["S14N03"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["技术协议"],
                },
            ],
        },
        {
            "stage_code": "S15",
            "stage_name": "软件开发与调试",
            "sequence": 14,
            "category": "execution",
            "estimated_days": 21,
            "description": "底层软件开发、上位机软件开发、测试算法开发、软件联调（与机械/电气并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S15N01",
                    "node_name": "底层软件开发",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "PLC程序开发、运动控制程序开发、通讯程序开发、安全程序开发",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["ME"],
                    "deliverables": ["机械调试记录"],
                },
                {
                    "node_code": "S15N02",
                    "node_name": "上位机软件开发",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "界面开发、业务逻辑开发、数据库开发、报表功能开发",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["机械自检报告"],
                },
                {
                    "node_code": "S15N03",
                    "node_name": "测试算法开发",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "算法编码、算法调试、算法验证、算法优化",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["电气安装记录"],
                },
                {
                    "node_code": "S15N04",
                    "node_name": "软件联调",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "底层与上位机联调、各模块联调、异常处理测试、性能测试",
                    "dependency_node_codes": ["S15N01", "S15N02", "S15N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["FIN"],
                    "deliverables": ["商务合同"],
                },
                {
                    "node_code": "S15N05",
                    "node_name": "软件自检",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "功能自检、bug修复、软件完工确认",
                    "dependency_node_codes": ["S15N04"],
                    "owner_role_code": "FIN",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["首付款发票", "到账确认单"],
                },
            ],
        },
        {
            "stage_code": "S16",
            "stage_name": "整机联调",
            "sequence": 15,
            "category": "execution",
            "estimated_days": 10,
            "description": "空载联调、带载联调、性能验证、问题整改",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S16N01",
                    "node_name": "空载联调",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "空载运行测试、流程验证、节拍测试、异常处理验证",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["接线检查记录"],
                },
                {
                    "node_code": "S16N02",
                    "node_name": "带载联调",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "产品上料测试、全流程测试、测试结果验证、数据记录验证",
                    "dependency_node_codes": ["S16N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SALES", "FIN"],
                    "deliverables": ["正式立项申请单", "项目编号"],
                },
                {
                    "node_code": "S16N03",
                    "node_name": "性能验证",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "节拍验证、精度验证、良率验证、稳定性验证",
                    "dependency_node_codes": ["S16N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SE", "SALES"],
                    "deliverables": ["项目移交清单", "移交确认单"],
                },
                {
                    "node_code": "S16N04",
                    "node_name": "问题整改",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "问题清单整理、问题分析、整改实施、整改验证",
                    "dependency_node_codes": ["S16N03"],
                    "owner_role_code": "PM",
                    "participant_role_codes": [],
                    "deliverables": ["项目团队名单", "职责分工表"],
                },
            ],
        },
        {
            "stage_code": "S17",
            "stage_name": "内部验收",
            "sequence": 16,
            "category": "execution",
            "estimated_days": 5,
            "description": "验收准备、功能验收、性能验收、资料验收、内部评审",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S17N01",
                    "node_name": "验收准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "验收计划制定、验收标准确认、验收环境准备、验收人员组织",
                    "owner_role_code": "EE",
                    "participant_role_codes": ["ASM"],
                    "deliverables": ["电气调试记录", "I/O点检表"],
                },
                {
                    "node_code": "S17N02",
                    "node_name": "功能验收",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "功能逐项验证、操作便捷性验证、异常处理验证",
                    "dependency_node_codes": ["S17N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SE", "ME", "EE", "SW", "TE"],
                    "deliverables": ["启动会议纪要", "里程碑计划"],
                },
                {
                    "node_code": "S17N03",
                    "node_name": "性能验收",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "节拍验收、精度验收、稳定性验收",
                    "dependency_node_codes": ["S17N02"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["输入资料确认单"],
                },
                {
                    "node_code": "S17N04",
                    "node_name": "资料验收",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "图纸资料完整性检查、操作手册检查、培训资料检查",
                    "dependency_node_codes": ["S17N03"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["深化方案"],
                },
                {
                    "node_code": "S17N05",
                    "node_name": "内部评审",
                    "node_type": "APPROVAL",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "内部验收评审会、遗留问题确认、出厂放行决定",
                    "dependency_node_codes": ["S17N04"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["技术规格书", "验收标准"],
                },
            ],
        },
        {
            "stage_code": "S18",
            "stage_name": "出厂发运",
            "sequence": 17,
            "category": "execution",
            "estimated_days": 5,
            "description": "出厂准备、包装、发运",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S18N01",
                    "node_name": "出厂准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "出厂资料准备、设备清洁、随机备件准备、包装材料准备",
                    "owner_role_code": "EE",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["电气自检报告"],
                },
                {
                    "node_code": "S18N02",
                    "node_name": "包装",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备拆分、防护处理、装箱、箱唛标识",
                    "dependency_node_codes": ["S18N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["PM", "SALES"],
                    "deliverables": ["方案确认单", "客户签字"],
                },
                {
                    "node_code": "S18N03",
                    "node_name": "发运",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物流安排、装车、运输跟踪、到达确认",
                    "dependency_node_codes": ["S18N02"],
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["3D总装图", "2D零件图", "机械BOM"],
                },
            ],
        },
        {
            "stage_code": "S19",
            "stage_name": "现场安装调试",
            "sequence": 18,
            "category": "execution",
            "estimated_days": 14,
            "description": "现场准备、现场安装、现场调试、现场问题处理",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S19N01",
                    "node_name": "现场准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "现场环境确认、水电气确认、吊装条件确认、开箱检查",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["PLC程序", "运动控制程序"],
                },
                {
                    "node_code": "S19N02",
                    "node_name": "现场安装",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备就位、设备组装、水电气接入、设备调平",
                    "dependency_node_codes": ["S19N01"],
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["电气原理图", "控制柜布局图", "电气BOM"],
                },
                {
                    "node_code": "S19N03",
                    "node_name": "现场调试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "上电调试、参数调整、流程验证、性能验证",
                    "dependency_node_codes": ["S19N02"],
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["软件设计文档", "接口协议", "UI设计稿"],
                },
                {
                    "node_code": "S19N04",
                    "node_name": "现场问题处理",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "问题记录、问题分析、现场整改、整改验证",
                    "dependency_node_codes": ["S19N03"],
                    "owner_role_code": "TE",
                    "participant_role_codes": ["SW"],
                    "deliverables": ["测试方案", "测试算法说明"],
                },
            ],
        },
        {
            "stage_code": "S20",
            "stage_name": "客户验收",
            "sequence": 19,
            "category": "execution",
            "estimated_days": 7,
            "description": "预验收、正式验收、验收签字",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S20N01",
                    "node_name": "预验收",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "预验收计划、功能预验收、性能预验收、问题整改",
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["上位机软件"],
                },
                {
                    "node_code": "S20N02",
                    "node_name": "正式验收",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "正式验收计划、功能正式验收、性能正式验收、连续运行验证",
                    "dependency_node_codes": ["S20N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW", "PM"],
                    "deliverables": ["会签记录", "冻结BOM", "采购清单"],
                },
                {
                    "node_code": "S20N03",
                    "node_name": "验收签字",
                    "node_type": "MILESTONE",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "验收报告编制、遗留问题确认、验收单签署、验收款支付申请",
                    "dependency_node_codes": ["S20N02"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["采购订单"],
                },
            ],
        },
        {
            "stage_code": "S21",
            "stage_name": "项目收尾",
            "sequence": 20,
            "category": "closure",
            "estimated_days": 14,
            "description": "资料移交、培训、备品备件移交、项目归档、项目结算",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S21N01",
                    "node_name": "资料移交",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "技术资料整理、操作手册移交、维护手册移交、图纸资料移交",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["测试算法程序"],
                },
                {
                    "node_code": "S21N02",
                    "node_name": "培训",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "操作培训、维护培训、培训考核、培训记录",
                    "dependency_node_codes": ["S21N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["到货检验记录", "齐套确认单"],
                },
                {
                    "node_code": "S21N03",
                    "node_name": "备品备件移交",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "备品备件清单、备品备件交接、交接确认",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["EE", "TE"],
                    "deliverables": ["软件联调报告"],
                },
                {
                    "node_code": "S21N04",
                    "node_name": "项目归档",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "项目资料归档、项目总结报告、经验教训总结、知识库更新",
                    "dependency_node_codes": ["S21N01", "S21N02", "S21N03"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["ME"],
                    "deliverables": ["外协订单", "外协件检验记录"],
                },
                {
                    "node_code": "S21N05",
                    "node_name": "项目结算",
                    "node_type": "MILESTONE",
                    "sequence": 4,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "成本核算、利润分析、尾款催收、财务结算、项目关闭",
                    "dependency_node_codes": ["S21N04"],
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["PMC"],
                    "deliverables": ["领料单"],
                },
            ],
        },
        # ==================== 售后阶段 (阶段 22) ====================
        {
            "stage_code": "S22",
            "stage_name": "质保服务",
            "sequence": 21,
            "category": "closure",
            "estimated_days": 365,
            "description": "质保期服务、质保期问题处理、质保到期",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S22N01",
                    "node_name": "质保期服务",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 360,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "定期回访、远程支持、预防性维护、软件升级",
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["软件自检报告"],
                },
                {
                    "node_code": "S22N02",
                    "node_name": "质保期问题处理",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 0,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "问题接收、问题分析、现场维修、远程支持、备件更换、问题关闭",
                    "owner_role_code": "TE",
                    "participant_role_codes": ["SW", "EE"],
                    "deliverables": ["空载联调报告"],
                },
                {
                    "node_code": "S22N03",
                    "node_name": "质保到期",
                    "node_type": "MILESTONE",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "质保到期通知、延保方案沟通、维保合同签订、质保结束确认",
                    "dependency_node_codes": ["S22N01"],
                    "owner_role_code": "ASM",
                    "participant_role_codes": [],
                    "deliverables": ["框架装配记录"],
                },
            ],
        },
    ],
}
