# -*- coding: utf-8 -*-
"""
售前阶段定义 (S04-S08)

包含需求评审、项目初立项、售前方案、商务报价与投标、中标与合同签订五个阶段
"""

from typing import Any, Dict, List

# 售前阶段 (S04-S08)
PRESALES_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S04",
            "stage_name": "需求评审",
            "sequence": 3,
            "category": "presales",
            "estimated_days": 10,
            "description": "需求资料收集、现场考察、需求分析与评审",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S04N01",
                    "node_name": "需求资料收集",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "测试样品接收、测试标准/规范接收、产品图纸/3D模型接收、保密协议签署、样品登记入库",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["样品接收单", "保密协议", "技术资料清单"],
                },
                {
                    "node_code": "S04N02",
                    "node_name": "现场考察",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "客户现场考察、产线环境了解、上下游设备对接了解、安装空间确认、现场照片/视频记录",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["现场考察报告", "现场照片"],
                },
                {
                    "node_code": "S04N03",
                    "node_name": "需求分析",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "测试项目梳理、测试原理初判、技术难点识别、资源需求评估、初步工期估算",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["需求分析报告"],
                },
                {
                    "node_code": "S04N04",
                    "node_name": "需求评审会",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "需求评审会议召开、技术可行性评估、商务可行性评估、风险评估、评审结论",
                    "dependency_node_codes": ["S04N01", "S04N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["市场调研报告", "潜在客户名单"],
                },
            ],
        },
        {
            "stage_code": "S05",
            "stage_name": "项目初立项",
            "sequence": 4,
            "category": "presales",
            "estimated_days": 5,
            "description": "⭐售前正式投入起点：初立项申请、售前团队组建",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S05N01",
                    "node_name": "初立项申请",
                    "node_type": "APPROVAL",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "售前立项申请提交、方案工作量评估、投入资源评估、商机赢率评估、初立项审批、临时项目编号分配",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE", "PM"],
                    "deliverables": ["初立项申请单", "临时项目编号"],
                },
                {
                    "node_code": "S05N02",
                    "node_name": "售前团队组建",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "售前项目负责人指定、技术部对接人指定、资源协调确认、售前进度计划制定、售前预算确定",
                    "dependency_node_codes": ["S05N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["推广活动记录"],
                },
            ],
        },
        {
            "stage_code": "S06",
            "stage_name": "售前方案",
            "sequence": 5,
            "category": "presales",
            "estimated_days": 30,
            "description": "⭐高投入高风险阶段：技术预研、方案设计、客户沟通、方案冻结",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S06N01",
                    "node_name": "技术预研",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 7,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "测试原理研究、关键技术验证试验、可行性分析、技术风险识别、预研报告输出",
                    "owner_role_code": "SE",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["技术预研报告", "可行性分析报告"],
                },
                {
                    "node_code": "S06N02",
                    "node_name": "概念方案设计",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "整机布局方案设计、工艺流程设计、自动化程度定义、人机交互方式确定、初步节拍估算",
                    "dependency_node_codes": ["S06N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["渠道合作协议"],
                },
                {
                    "node_code": "S06N03",
                    "node_name": "详细方案设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 7,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "机械方案设计、电气方案设计、软件方案设计、测试方案设计、关键部件选型、初步BOM估算",
                    "dependency_node_codes": ["S06N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["线索清单"],
                },
                {
                    "node_code": "S06N04",
                    "node_name": "方案内部评审",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "技术方案评审会、技术风险评估、成本初步核算、工期初步估算、方案修改完善",
                    "dependency_node_codes": ["S06N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["CRM线索记录"],
                },
                {
                    "node_code": "S06N05",
                    "node_name": "客户方案沟通",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "方案汇报PPT准备、客户技术交流会、客户反馈收集、方案修改调整、多轮沟通迭代",
                    "dependency_node_codes": ["S06N04"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["线索评级报告"],
                },
                {
                    "node_code": "S06N06",
                    "node_name": "方案冻结",
                    "node_type": "MILESTONE",
                    "sequence": 5,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "最终方案确定、客户方案认可确认、方案版本冻结、方案文档归档",
                    "dependency_node_codes": ["S06N05"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["沟通记录"],
                },
            ],
        },
        {
            "stage_code": "S07",
            "stage_name": "商务报价与投标",
            "sequence": 6,
            "category": "presales",
            "estimated_days": 14,
            "description": "成本核算、报价编制、投标准备、商务谈判",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S07N01",
                    "node_name": "成本核算",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "BOM成本详细核算、工时成本估算、外协加工成本估算、采购成本估算、差旅/安装/售后成本估算、风险成本预留、管理费用分摊、目标毛利核算",
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["SE", "FIN"],
                    "deliverables": ["成本核算表"],
                },
                {
                    "node_code": "S07N02",
                    "node_name": "报价编制",
                    "node_type": "DELIVERABLE",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "报价单编制、报价明细表、技术方案书定稿、报价内部评审、特殊折扣审批、报价文件定稿",
                    "dependency_node_codes": ["S07N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["客户拜访记录", "需求初步记录"],
                },
                {
                    "node_code": "S07N03",
                    "node_name": "投标准备",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "招标文件研读、投标资质准备、投标文件编制、技术标编制、商务标编制、投标文件内部评审、投标文件封装",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["投标文件"],
                },
                {
                    "node_code": "S07N04",
                    "node_name": "报价/投标提交",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "报价单提交客户、投标文件递交、开标参与、技术澄清/答疑、商务澄清/答疑",
                    "dependency_node_codes": ["S07N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["CRM商机记录"],
                },
                {
                    "node_code": "S07N05",
                    "node_name": "商务谈判",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "价格谈判、技术条款谈判、付款条件谈判、交期谈判、验收条款谈判、质保条款谈判、谈判记录整理",
                    "dependency_node_codes": ["S07N04"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["跟进记录"],
                },
            ],
        },
        {
            "stage_code": "S08",
            "stage_name": "中标与合同签订",
            "sequence": 7,
            "category": "presales",
            "estimated_days": 14,
            "description": "中标确认、技术协议签订、商务合同签订、首付款收取",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S08N01",
                    "node_name": "中标确认",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "中标通知书接收、中标结果确认、内部通报",
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["中标通知书"],
                },
                {
                    "node_code": "S08N02",
                    "node_name": "技术协议",
                    "node_type": "DELIVERABLE",
                    "sequence": 1,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "技术协议拟定、技术协议内部评审、技术协议客户沟通、技术协议修改定稿、技术协议签署",
                    "dependency_node_codes": ["S08N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["样品接收单", "保密协议", "技术资料清单"],
                },
                {
                    "node_code": "S08N03",
                    "node_name": "商务合同",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "合同草拟、合同条款审核(商务/技术/法务)、合同修改谈判、合同定稿、合同签署、合同盖章归档",
                    "dependency_node_codes": ["S08N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["现场考察报告", "现场照片"],
                },
                {
                    "node_code": "S08N04",
                    "node_name": "首付款",
                    "node_type": "MILESTONE",
                    "sequence": 3,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "首付款发票开具、首付款跟催、首付款到账确认、财务入账确认",
                    "dependency_node_codes": ["S08N03"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["需求分析报告"],
                },
            ],
        },
]
