# -*- coding: utf-8 -*-
"""
重复生产模板（最简流程）

TPL_REPEAT - 重复生产（老产品复制）
"""

from typing import Any, Dict

# 重复生产模板（最简流程）
REPEAT_TEMPLATE: Dict[str, Any] = {
    "template_code": "TPL_REPEAT",
    "template_name": "重复生产",
    "description": "适用于已有成熟产品的重复生产订单，跳过设计阶段直接生产",
    "project_type": "REPEAT",
    "stages": [
        {
            "stage_code": "R1",
            "stage_name": "订单确认",
            "sequence": 0,
            "estimated_days": 2,
            "description": "确认订单和生产计划",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "R1N01",
                    "node_name": "订单登记",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "登记订单信息",
                    "owner_role_code": "PM",
                    "participant_role_codes": [],
                    "deliverables": ["订单登记表"],
                },
                {
                    "node_code": "R1N02",
                    "node_name": "生产排期",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "安排生产计划",
                    "dependency_node_codes": ["R1N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["生产计划"],
                },
            ]
        },
        {
            "stage_code": "R2",
            "stage_name": "物料准备",
            "sequence": 1,
            "estimated_days": 10,
            "description": "按照标准BOM准备物料",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "R2N01",
                    "node_name": "库存检查",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "检查物料库存",
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["库存检查报告"],
                },
                {
                    "node_code": "R2N02",
                    "node_name": "采购补料",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "采购缺料物料",
                    "dependency_node_codes": ["R2N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["采购订单"],
                },
                {
                    "node_code": "R2N03",
                    "node_name": "物料齐套",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物料齐套确认",
                    "dependency_node_codes": ["R2N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["齐套确认单"],
                },
            ]
        },
        {
            "stage_code": "R3",
            "stage_name": "批量生产",
            "sequence": 2,
            "estimated_days": 14,
            "description": "批量生产装配",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "R3N01",
                    "node_name": "生产任务下达",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "下达生产任务单",
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["生产任务单"],
                },
                {
                    "node_code": "R3N02",
                    "node_name": "批量装配",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "批量装配生产",
                    "dependency_node_codes": ["R3N01"],
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["ME", "EE"],
                    "deliverables": ["生产记录"],
                },
                {
                    "node_code": "R3N03",
                    "node_name": "调试测试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备调试测试",
                    "dependency_node_codes": ["R3N02"],
                    "owner_role_code": "TE",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["调试报告"],
                },
                {
                    "node_code": "R3N04",
                    "node_name": "质量检验",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "产品质量检验",
                    "dependency_node_codes": ["R3N03"],
                    "owner_role_code": "QA",
                    "participant_role_codes": [],
                    "deliverables": ["质检报告"],
                },
            ]
        },
        {
            "stage_code": "R4",
            "stage_name": "发货交付",
            "sequence": 3,
            "estimated_days": 3,
            "description": "包装发货交付",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "R4N01",
                    "node_name": "包装入库",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "包装入成品库",
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["ASM"],
                    "deliverables": ["入库单"],
                },
                {
                    "node_code": "R4N02",
                    "node_name": "安排发货",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "安排物流发货",
                    "dependency_node_codes": ["R4N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["发货单", "物流单号"],
                },
                {
                    "node_code": "R4N03",
                    "node_name": "交付确认",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "客户签收确认",
                    "dependency_node_codes": ["R4N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": [],
                    "deliverables": ["签收单"],
                },
            ]
        },
    ]
}
