# -*- coding: utf-8 -*-
"""
销售阶段定义 (S01-S03)

包含市场开拓、线索获取、商机培育三个阶段
"""

from typing import Any, Dict, List

# 销售阶段 (S01-S03)
SALES_STAGES: List[Dict[str, Any]] = [
    {
        "stage_code": "S01",
        "stage_name": "市场开拓",
        "sequence": 0,
        "category": "sales",
        "estimated_days": 30,
        "description": "市场调研、品牌推广、渠道建设",
        "is_required": False,  # 销售阶段通常可选
        "is_milestone": False,
        "is_parallel": False,
        "nodes": [
            {
                "node_code": "S01N01",
                "node_name": "市场调研",
                "node_type": "TASK",
                "sequence": 0,
                "estimated_days": 10,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "行业趋势分析、目标客户画像、竞争对手分析、潜在客户名单整理、区域市场规划",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["市场调研报告", "潜在客户名单"],
            },
            {
                "node_code": "S01N02",
                "node_name": "品牌推广",
                "node_type": "TASK",
                "sequence": 1,
                "estimated_days": 10,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "官网/公众号维护、行业展会参展、技术文章/案例发布、行业协会活动、客户参观接待",
                "owner_role_code": "SALES",
                "participant_role_codes": ["SE"],
                "deliverables": ["推广活动记录"],
            },
            {
                "node_code": "S01N03",
                "node_name": "渠道建设",
                "node_type": "TASK",
                "sequence": 2,
                "estimated_days": 10,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "代理商/合作伙伴开发、老客户转介绍激励、供应商反向推荐、行业圈子经营",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["渠道合作协议"],
            },
        ],
    },
    {
        "stage_code": "S02",
        "stage_name": "线索获取",
        "sequence": 1,
        "category": "sales",
        "estimated_days": 14,
        "description": "收集销售线索并进行初筛",
        "is_required": False,
        "is_milestone": False,
        "is_parallel": False,
        "nodes": [
            {
                "node_code": "S02N01",
                "node_name": "线索来源",
                "node_type": "TASK",
                "sequence": 0,
                "estimated_days": 5,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "展会名片收集、官网询盘、400电话咨询、老客户新项目需求、转介绍、招标信息",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["线索清单"],
            },
            {
                "node_code": "S02N02",
                "node_name": "线索录入",
                "node_type": "TASK",
                "sequence": 1,
                "estimated_days": 2,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "线索信息登记、来源标注、线索分配、线索查重",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["CRM线索记录"],
            },
            {
                "node_code": "S02N03",
                "node_name": "线索初筛",
                "node_type": "TASK",
                "sequence": 2,
                "estimated_days": 3,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "客户背景初步了解、需求真实性判断、预算/时间紧迫度初判、线索评级(A/B/C/D)",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["线索评级报告"],
            },
        ],
    },
    {
        "stage_code": "S03",
        "stage_name": "商机培育",
        "sequence": 2,
        "category": "sales",
        "estimated_days": 30,
        "description": "商机挖掘、跟进和状态管理",
        "is_required": False,
        "is_milestone": False,
        "is_parallel": False,
        "nodes": [
            {
                "node_code": "S03N01",
                "node_name": "初次接触",
                "node_type": "TASK",
                "sequence": 0,
                "estimated_days": 3,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "电话/微信初次沟通、需求初步了解、公司介绍/案例分享、约定拜访时间",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["沟通记录"],
            },
            {
                "node_code": "S03N02",
                "node_name": "需求挖掘",
                "node_type": "TASK",
                "sequence": 1,
                "estimated_days": 10,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "客户拜访、需求详细沟通、测试产品/样品了解、测试标准获取、产能要求、预算探询、决策链了解",
                "owner_role_code": "SALES",
                "participant_role_codes": ["SE"],
                "deliverables": ["客户拜访记录", "需求初步记录"],
            },
            {
                "node_code": "S03N03",
                "node_name": "商机录入",
                "node_type": "TASK",
                "sequence": 2,
                "estimated_days": 1,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "商机信息登记、金额预估、预计成交时间、成交概率评估、商机评级",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["CRM商机记录"],
            },
            {
                "node_code": "S03N04",
                "node_name": "商机跟进",
                "node_type": "TASK",
                "sequence": 3,
                "estimated_days": 14,
                "completion_method": "MANUAL",
                "is_required": False,
                "description": "定期跟进计划、跟进记录登记、商机状态更新、异常商机预警",
                "owner_role_code": "SALES",
                "participant_role_codes": [],
                "deliverables": ["跟进记录"],
            },
        ],
    },
]
