# -*- coding: utf-8 -*-
"""
标准全流程模板（9大阶段）

TPL_STANDARD - 标准全流程（新产品完整流程）
"""

from typing import Any, Dict

# 标准全流程模板（9大阶段）
STANDARD_TEMPLATE: Dict[str, Any] = {
    "template_code": "TPL_STANDARD",
    "template_name": "标准全流程",
    "description": "适用于新产品开发的完整流程，包含售前支持、方案设计、采购、生产、调试、验收、交付全过程",
    "project_type": "NEW",
    "stages": [
        {
            "stage_code": "S1",
            "stage_name": "需求进入",
            "sequence": 0,
            "estimated_days": 7,
            "description": "接收客户需求，评估可行性",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S1N01",
                    "node_name": "需求接收登记",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "登记客户需求基本信息",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["需求登记表"],
                },
                {
                    "node_code": "S1N02",
                    "node_name": "技术可行性评估",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "评估技术实现可行性",
                    "owner_role_code": "CTO",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["可行性评估报告"],
                },
                {
                    "node_code": "S1N03",
                    "node_name": "商务报价",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "编制项目报价",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["FINANCE"],
                    "deliverables": ["报价单"],
                },
                {
                    "node_code": "S1N04",
                    "node_name": "合同签订确认",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "确认合同签订",
                    "dependency_node_codes": ["S1N03"],
                    "owner_role_code": "GM",
                    "participant_role_codes": ["SALES_DIR", "SALES"],
                    "deliverables": ["签订合同"],
                },
            ]
        },
        {
            "stage_code": "S2",
            "stage_name": "方案设计",
            "sequence": 1,
            "estimated_days": 14,
            "description": "完成整体方案设计与技术评审",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S2N01",
                    "node_name": "需求澄清会议",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "与客户确认详细需求",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["ME", "EE", "SW", "SALES"],
                    "deliverables": ["会议纪要", "需求确认书"],
                },
                {
                    "node_code": "S2N02",
                    "node_name": "整体方案设计",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "编制整体技术方案",
                    "dependency_node_codes": ["S2N01"],
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE", "SW"],
                    "deliverables": ["技术方案书"],
                },
                {
                    "node_code": "S2N03",
                    "node_name": "机械结构设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "完成机械结构设计图纸",
                    "dependency_node_codes": ["S2N02"],
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["3D模型", "2D装配图", "零件图"],
                },
                {
                    "node_code": "S2N04",
                    "node_name": "电气设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 3,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "完成电气原理图和接线图",
                    "dependency_node_codes": ["S2N02"],
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["电气原理图", "接线图", "元器件清单"],
                },
                {
                    "node_code": "S2N05",
                    "node_name": "技术评审",
                    "node_type": "APPROVAL",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "技术方案评审通过",
                    "dependency_node_codes": ["S2N03", "S2N04"],
                    "owner_role_code": "CTO",
                    "participant_role_codes": ["ME", "EE", "SW", "QA"],
                    "deliverables": ["评审记录"],
                },
            ]
        },
        {
            "stage_code": "S3",
            "stage_name": "采购备料",
            "sequence": 2,
            "estimated_days": 21,
            "description": "BOM确认和物料采购",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S3N01",
                    "node_name": "BOM编制",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "编制物料清单",
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["BOM清单"],
                },
                {
                    "node_code": "S3N02",
                    "node_name": "BOM评审",
                    "node_type": "APPROVAL",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "物料清单评审确认",
                    "dependency_node_codes": ["S3N01"],
                    "owner_role_code": "CTO",
                    "participant_role_codes": ["PU_MGR", "PMC"],
                    "deliverables": ["BOM评审记录"],
                },
                {
                    "node_code": "S3N03",
                    "node_name": "采购申请",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "提交采购申请",
                    "dependency_node_codes": ["S3N02"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["PU_MGR"],
                    "deliverables": ["采购申请单"],
                },
                {
                    "node_code": "S3N04",
                    "node_name": "供应商选择",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "选择供应商并下单",
                    "dependency_node_codes": ["S3N03"],
                    "owner_role_code": "PU_MGR",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["采购订单"],
                },
                {
                    "node_code": "S3N05",
                    "node_name": "物料到货验收",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物料到货并完成验收",
                    "dependency_node_codes": ["S3N04"],
                    "owner_role_code": "QA",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["入库单", "检验报告"],
                },
            ]
        },
        {
            "stage_code": "S4",
            "stage_name": "加工制造",
            "sequence": 3,
            "estimated_days": 21,
            "description": "机械加工和外协管理",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S4N01",
                    "node_name": "加工图纸发放",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "发放加工图纸给车间/外协",
                    "owner_role_code": "ME",
                    "participant_role_codes": ["PMC"],
                    "deliverables": ["加工图纸"],
                },
                {
                    "node_code": "S4N02",
                    "node_name": "自制件加工",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "内部加工自制零件",
                    "dependency_node_codes": ["S4N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["加工完成零件"],
                },
                {
                    "node_code": "S4N03",
                    "node_name": "外协件加工",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "外协加工零件",
                    "dependency_node_codes": ["S4N01"],
                    "owner_role_code": "PU_MGR",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["外协加工零件"],
                },
                {
                    "node_code": "S4N04",
                    "node_name": "零件检验入库",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "零件检验合格入库",
                    "dependency_node_codes": ["S4N02"],
                    "owner_role_code": "QA",
                    "participant_role_codes": [],
                    "deliverables": ["检验报告", "入库单"],
                },
            ]
        },
        {
            "stage_code": "S5",
            "stage_name": "装配调试",
            "sequence": 4,
            "estimated_days": 14,
            "description": "设备装配和调试验证",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S5N01",
                    "node_name": "机械装配",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "完成机械部分装配",
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["装配完成确认"],
                },
                {
                    "node_code": "S5N02",
                    "node_name": "电气接线",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "完成电气接线安装",
                    "dependency_node_codes": ["S5N01"],
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["接线完成确认"],
                },
                {
                    "node_code": "S5N03",
                    "node_name": "程序调试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 4,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "软件程序调试",
                    "dependency_node_codes": ["S5N02"],
                    "owner_role_code": "SW",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["调试记录"],
                },
                {
                    "node_code": "S5N04",
                    "node_name": "联调测试",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "整机联调测试",
                    "dependency_node_codes": ["S5N03"],
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE", "SW", "QA"],
                    "deliverables": ["联调测试报告"],
                },
            ]
        },
        {
            "stage_code": "S6",
            "stage_name": "出厂验收",
            "sequence": 5,
            "estimated_days": 3,
            "description": "FAT出厂验收测试",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S6N01",
                    "node_name": "内部预验收",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "内部预验收检查",
                    "owner_role_code": "QA",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["预验收检查表"],
                },
                {
                    "node_code": "S6N02",
                    "node_name": "客户FAT验收",
                    "node_type": "APPROVAL",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "客户出厂验收",
                    "dependency_node_codes": ["S6N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA", "SALES"],
                    "deliverables": ["FAT验收记录"],
                },
                {
                    "node_code": "S6N03",
                    "node_name": "FAT报告签署",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "FAT验收报告签署",
                    "dependency_node_codes": ["S6N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["FAT验收报告"],
                },
            ]
        },
        {
            "stage_code": "S7",
            "stage_name": "包装发运",
            "sequence": 6,
            "estimated_days": 3,
            "description": "设备包装和发货",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S7N01",
                    "node_name": "设备包装",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备包装入箱",
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["装箱单"],
                },
                {
                    "node_code": "S7N02",
                    "node_name": "发货安排",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "安排物流发货",
                    "dependency_node_codes": ["S7N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["发货单", "物流单号"],
                },
                {
                    "node_code": "S7N03",
                    "node_name": "发货确认",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "确认发货到达",
                    "dependency_node_codes": ["S7N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["签收单"],
                },
            ]
        },
        {
            "stage_code": "S8",
            "stage_name": "现场安装",
            "sequence": 7,
            "estimated_days": 7,
            "description": "现场安装调试和SAT验收",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S8N01",
                    "node_name": "现场安装",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "现场设备安装",
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["安装完成确认"],
                },
                {
                    "node_code": "S8N02",
                    "node_name": "现场调试",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "现场设备调试",
                    "dependency_node_codes": ["S8N01"],
                    "owner_role_code": "SW",
                    "participant_role_codes": ["ME", "EE"],
                    "deliverables": ["现场调试记录"],
                },
                {
                    "node_code": "S8N03",
                    "node_name": "客户SAT验收",
                    "node_type": "APPROVAL",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "客户现场验收",
                    "dependency_node_codes": ["S8N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA", "SALES"],
                    "deliverables": ["SAT验收记录"],
                },
                {
                    "node_code": "S8N04",
                    "node_name": "SAT报告签署",
                    "node_type": "DELIVERABLE",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "SAT验收报告签署",
                    "dependency_node_codes": ["S8N03"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["SAT验收报告"],
                },
            ]
        },
        {
            "stage_code": "S9",
            "stage_name": "质保结项",
            "sequence": 8,
            "estimated_days": 7,
            "description": "项目收尾和质保交接",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S9N01",
                    "node_name": "项目文档归档",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "整理归档项目文档",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["项目文档包", "技术资料"],
                },
                {
                    "node_code": "S9N02",
                    "node_name": "客户培训",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "客户操作培训",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["ME", "EE"],
                    "deliverables": ["培训记录", "操作手册"],
                },
                {
                    "node_code": "S9N03",
                    "node_name": "质保交接",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "移交售后质保服务",
                    "dependency_node_codes": ["S9N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["质保交接单"],
                },
                {
                    "node_code": "S9N04",
                    "node_name": "项目结项审批",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "项目结项审批确认",
                    "dependency_node_codes": ["S9N03"],
                    "owner_role_code": "GM",
                    "participant_role_codes": ["CTO", "CFO"],
                    "deliverables": ["结项审批单"],
                },
                {
                    "node_code": "S9N05",
                    "node_name": "经验总结",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "项目经验总结归档",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["经验总结报告"],
                },
            ]
        },
    ]
}
