/**
 * Alert Center Constants (canonical entry point).
 *
 * Re-export from alert constants but remap getAlert*Config to
 * the alert-center versions (ALERT_LEVELS/ALERT_STATUS/ALERT_TYPES).
 */
export {
  ALERT_STAT_TYPES,
  ALERT_LEVEL_STATS,
  ALERT_STATUS_STATS,
  ALERT_TYPE_STATS,
  TIME_DIMENSIONS,
  CHART_TYPES,
  STAT_METRICS,
  FILTER_CONFIGS,
  CHART_COLORS,
  STATISTICS_METRICS,
  TABLE_CONFIG,
  ALERT_LEVELS,
  ALERT_STATUS,
  ALERT_TYPES,
  ALERT_RULES,
  NOTIFICATION_CHANNELS,
  ALERT_PRIORITY,
  ALERT_ACTIONS,
  ALERT_METRICS,
  ALERT_TIME_CONFIG,
  ALERT_STATUS_FLOW,
  ALERT_PERMISSIONS,
  DEFAULT_STAT_CONFIG,
  DEFAULT_CHART_CONFIG,
  DEFAULT_ALERT_CONFIG,
  DEFAULT_RULE_CONFIG,
  calculateSLACompliance,
  calculateAverageResponseTime,
  calculateResponseTime,
  formatStatValue,
  getTrendDirection,
  getTrendColor,
  getTrendIcon,
  generateTimeSeries,
  getAlertRuleConfig,
  getNotificationChannelConfig,
  calculateCenterResponseTime,
  calculateResolutionTime,
  checkResponseTimeSLA,
  checkResolutionTimeSLA,
  getAvailableActions,
  validateAlertRule,
  generateAlertNumber,
  getAlertSummary,
  requiresEscalation,
  getAlertSeverityScore,
  isBusinessHour,
  formatAlertTime,
  // Alert-center specific mappings (ALERT_LEVELS/ALERT_STATUS/ALERT_TYPES)
  getAlertCenterLevelConfig as getAlertLevelConfig,
  getAlertCenterStatusConfig as getAlertStatusConfig,
  getAlertCenterTypeConfig as getAlertTypeConfig,
} from "./alert";

export { default } from "./alert";
