/**
 * 客户沟通枚举常量（兼容导出）
 * 简单枚举定义、标签映射、图标颜色配置、统计函数
 */

// 简单枚举定义
export const COMMUNICATION_TYPE = {
  PHONE: 'phone',
  EMAIL: 'email',
  ON_SITE: 'on_site',
  WECHAT: 'wechat',
  MEETING: 'meeting',
  VIDEO_CALL: 'video_call'
};

export const COMMUNICATION_PRIORITY = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low'
};

export const COMMUNICATION_STATUS = {
  PENDING: 'pending',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  FOLLOW_UP: 'follow_up'
};

export const COMMUNICATION_TOPIC = {
  SALES: 'sales',
  SUPPORT: 'support',
  COMPLAINT: 'complaint',
  CONSULTATION: 'consultation',
  FEEDBACK: 'feedback',
  TRAINING: 'training',
  MAINTENANCE: 'maintenance',
  OTHER: 'other'
};

export const CUSTOMER_SATISFACTION = {
  VERY_SATISFIED: 5,
  SATISFIED: 4,
  NEUTRAL: 3,
  DISSATISFIED: 2,
  VERY_DISSATISFIED: 1
};

export const FOLLOW_UP_PRIORITY = {
  URGENT: 'urgent',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low'
};

// 标签映射
export const COMMUNICATION_TYPE_LABELS = {
  [COMMUNICATION_TYPE.PHONE]: '电话',
  [COMMUNICATION_TYPE.EMAIL]: '邮件',
  [COMMUNICATION_TYPE.ON_SITE]: '现场',
  [COMMUNICATION_TYPE.WECHAT]: '微信',
  [COMMUNICATION_TYPE.MEETING]: '会议',
  [COMMUNICATION_TYPE.VIDEO_CALL]: '视频通话'
};

export const COMMUNICATION_PRIORITY_LABELS = {
  [COMMUNICATION_PRIORITY.HIGH]: '高优先级',
  [COMMUNICATION_PRIORITY.MEDIUM]: '中优先级',
  [COMMUNICATION_PRIORITY.LOW]: '低优先级'
};

export const COMMUNICATION_STATUS_LABELS = {
  [COMMUNICATION_STATUS.PENDING]: '待处理',
  [COMMUNICATION_STATUS.IN_PROGRESS]: '进行中',
  [COMMUNICATION_STATUS.COMPLETED]: '已完成',
  [COMMUNICATION_STATUS.FOLLOW_UP]: '需要跟进'
};

export const COMMUNICATION_TOPIC_LABELS = {
  [COMMUNICATION_TOPIC.SALES]: '销售',
  [COMMUNICATION_TOPIC.SUPPORT]: '技术支持',
  [COMMUNICATION_TOPIC.COMPLAINT]: '投诉',
  [COMMUNICATION_TOPIC.CONSULTATION]: '咨询',
  [COMMUNICATION_TOPIC.FEEDBACK]: '反馈',
  [COMMUNICATION_TOPIC.TRAINING]: '培训',
  [COMMUNICATION_TOPIC.MAINTENANCE]: '维护',
  [COMMUNICATION_TOPIC.OTHER]: '其他'
};

export const CUSTOMER_SATISFACTION_LABELS = {
  [CUSTOMER_SATISFACTION.VERY_SATISFIED]: '非常满意',
  [CUSTOMER_SATISFACTION.SATISFIED]: '满意',
  [CUSTOMER_SATISFACTION.NEUTRAL]: '一般',
  [CUSTOMER_SATISFACTION.DISSATISFIED]: '不满意',
  [CUSTOMER_SATISFACTION.VERY_DISSATISFIED]: '非常不满意'
};

export const FOLLOW_UP_PRIORITY_LABELS = {
  [FOLLOW_UP_PRIORITY.URGENT]: '紧急',
  [FOLLOW_UP_PRIORITY.HIGH]: '高',
  [FOLLOW_UP_PRIORITY.MEDIUM]: '中',
  [FOLLOW_UP_PRIORITY.LOW]: '低'
};

// 图标配置
export const COMMUNICATION_TYPE_ICONS = {
  [COMMUNICATION_TYPE.PHONE]: '📞',
  [COMMUNICATION_TYPE.EMAIL]: '📧',
  [COMMUNICATION_TYPE.ON_SITE]: '🏢',
  [COMMUNICATION_TYPE.WECHAT]: '💬',
  [COMMUNICATION_TYPE.MEETING]: '👥',
  [COMMUNICATION_TYPE.VIDEO_CALL]: '📹'
};

// 颜色配置
export const COMMUNICATION_STATUS_COLORS = {
  [COMMUNICATION_STATUS.PENDING]: '#8B5CF6',
  [COMMUNICATION_STATUS.IN_PROGRESS]: '#F59E0B',
  [COMMUNICATION_STATUS.COMPLETED]: '#10B981',
  [COMMUNICATION_STATUS.FOLLOW_UP]: '#3B82F6'
};

export const PRIORITY_COLORS = {
  [COMMUNICATION_PRIORITY.HIGH]: '#EF4444',
  [COMMUNICATION_PRIORITY.MEDIUM]: '#F59E0B',
  [COMMUNICATION_PRIORITY.LOW]: '#10B981'
};

export const TOPIC_COLORS = {
  [COMMUNICATION_TOPIC.SALES]: '#3B82F6',
  [COMMUNICATION_TOPIC.SUPPORT]: '#10B981',
  [COMMUNICATION_TOPIC.COMPLAINT]: '#EF4444',
  [COMMUNICATION_TOPIC.CONSULTATION]: '#8B5CF6',
  [COMMUNICATION_TOPIC.FEEDBACK]: '#F59E0B',
  [COMMUNICATION_TOPIC.TRAINING]: '#06B6D4',
  [COMMUNICATION_TOPIC.MAINTENANCE]: '#6B7280',
  [COMMUNICATION_TOPIC.OTHER]: '#EC4899'
};

export const SATISFACTION_COLORS = {
  [CUSTOMER_SATISFACTION.VERY_SATISFIED]: '#10B981',
  [CUSTOMER_SATISFACTION.SATISFIED]: '#22C55E',
  [CUSTOMER_SATISFACTION.NEUTRAL]: '#F59E0B',
  [CUSTOMER_SATISFACTION.DISSATISFIED]: '#F97316',
  [CUSTOMER_SATISFACTION.VERY_DISSATISFIED]: '#EF4444'
};

// 统计配置
export const COMMUNICATION_STATS_CONFIG = {
  TOTAL_COMMUNICATIONS: 'total_communications',
  PENDING_COMMUNICATIONS: 'pending_communications',
  IN_PROGRESS_COMMUNICATIONS: 'in_progress_communications',
  COMPLETED_COMMUNICATIONS: 'completed_communications',
  FOLLOW_UP_COMMUNICATIONS: 'follow_up_communications',
  AVERAGE_SATISFACTION: 'average_satisfaction',
  RESPONSE_RATE: 'response_rate'
};

// 过滤选项
export const COMMUNICATION_FILTER_OPTIONS = [
  { value: 'all', label: '全部状态' },
  { value: COMMUNICATION_STATUS.PENDING, label: '待处理' },
  { value: COMMUNICATION_STATUS.IN_PROGRESS, label: '进行中' },
  { value: COMMUNICATION_STATUS.COMPLETED, label: '已完成' },
  { value: COMMUNICATION_STATUS.FOLLOW_UP, label: '需要跟进' }
];

export const PRIORITY_FILTER_OPTIONS = [
  { value: 'all', label: '全部优先级' },
  { value: COMMUNICATION_PRIORITY.HIGH, label: '高优先级' },
  { value: COMMUNICATION_PRIORITY.MEDIUM, label: '中优先级' },
  { value: COMMUNICATION_PRIORITY.LOW, label: '低优先级' }
];

export const TYPE_FILTER_OPTIONS = [
  { value: 'all', label: '全部方式' },
  { value: COMMUNICATION_TYPE.PHONE, label: '电话' },
  { value: COMMUNICATION_TYPE.EMAIL, label: '邮件' },
  { value: COMMUNICATION_TYPE.ON_SITE, label: '现场' },
  { value: COMMUNICATION_TYPE.WECHAT, label: '微信' },
  { value: COMMUNICATION_TYPE.MEETING, label: '会议' },
  { value: COMMUNICATION_TYPE.VIDEO_CALL, label: '视频通话' }
];

export const TOPIC_FILTER_OPTIONS = [
  { value: 'all', label: '全部主题' },
  { value: COMMUNICATION_TOPIC.SALES, label: '销售' },
  { value: COMMUNICATION_TOPIC.SUPPORT, label: '技术支持' },
  { value: COMMUNICATION_TOPIC.COMPLAINT, label: '投诉' },
  { value: COMMUNICATION_TOPIC.CONSULTATION, label: '咨询' },
  { value: COMMUNICATION_TOPIC.FEEDBACK, label: '反馈' },
  { value: COMMUNICATION_TOPIC.TRAINING, label: '培训' },
  { value: COMMUNICATION_TOPIC.MAINTENANCE, label: '维护' },
  { value: COMMUNICATION_TOPIC.OTHER, label: '其他' }
];

// 默认配置
export const DEFAULT_COMMUNICATION_CONFIG = {
  status: COMMUNICATION_STATUS.PENDING,
  priority: COMMUNICATION_PRIORITY.MEDIUM,
  communication_type: COMMUNICATION_TYPE.PHONE,
  topic: COMMUNICATION_TOPIC.SUPPORT,
  satisfaction_rating: null,
  follow_up_priority: FOLLOW_UP_PRIORITY.MEDIUM
};

export const DEFAULT_FOLLOW_UP_CONFIG = {
  priority: FOLLOW_UP_PRIORITY.MEDIUM,
  due_date: null,
  assigned_to: null,
  notes: ''
};
