# -*- coding: utf-8 -*-
"""
其他任务配置 - HR、销售、外协、采购等
"""

OTHER_TASKS = [
    {
        "id": "daily_spec_match_check",
        "name": "每日规格匹配检查",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_spec_match_check",
        "cron": {"hour": 9, "minute": 0},
        "owner": "Quality Team",
        "category": "Spec Match",
        "description": "检查采购订单与 BOM 的规格匹配情况，生成差异记录。",
        "enabled": True,
        "dependencies_tables": ["purchase_orders", "bom_items", "materials"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 900,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_workload_overload_alerts",
        "name": "负荷超限预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_workload_overload_alerts",
        "cron": {"hour": 11, "minute": 0},
        "owner": "PMO",
        "category": "Resource",
        "description": "每天 11 点检查工时与人员负荷是否超限。",
        "enabled": True,
        "dependencies_tables": ["users", "timesheets", "tasks", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_milestone_status_and_adjust_payments",
        "name": "里程碑状态监控与收款计划调整",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_milestone_status_and_adjust_payments",
        "cron": {"minute": 0},
        "owner": "Sales",
        "category": "Payment",
        "description": "Issue 7.3: 每小时检查里程碑状态变化，自动调整关联的收款计划。",
        "enabled": True,
        "dependencies_tables": ["project_milestones", "project_payment_plans", "notifications"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_delivery_delay",
        "name": "到货延迟检查",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_delivery_delay",
        "cron": {"hour": 14, "minute": 0},
        "owner": "Supply Chain",
        "category": "Procurement",
        "description": "下午 2 点扫描采购到货延迟。",
        "enabled": True,
        "dependencies_tables": ["purchase_orders", "goods_receipts", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_outsourcing_delivery_alerts",
        "name": "外协交期预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_outsourcing_delivery_alerts",
        "cron": {"hour": 15, "minute": 0},
        "owner": "Supply Chain",
        "category": "Outsourcing",
        "description": "下午 3 点检查外协交期风险。",
        "enabled": True,
        "dependencies_tables": ["outsourcing_orders", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "generate_job_duty_tasks",
        "name": "岗位职责任务生成",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_job_duty_tasks",
        "cron": {"hour": 4, "minute": 0},
        "owner": "PMO",
        "category": "Workspace",
        "description": "凌晨 4 点生成岗位职责相关任务。",
        "enabled": True,
        "dependencies_tables": ["job_duties", "tasks", "users"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_ecn_overdue",
        "name": "ECN 超时检查",
        "module": "app.services.ecn_scheduler",
        "callable": "run_ecn_scheduler",
        "cron": {"hour": 9, "minute": 0},
        "owner": "ECN Team",
        "category": "Change Management",
        "description": "每天 9 点扫描 ECN 超时事项。",
        "enabled": True,
        "dependencies_tables": ["ecns", "ecn_tasks", "ecn_approvals"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_opportunity_stage_timeout",
        "name": "商机阶段超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_opportunity_stage_timeout",
        "cron": {"hour": 15, "minute": 30},
        "owner": "Sales",
        "category": "Sales",
        "description": "15:30 提醒超时的商机阶段。",
        "enabled": True,
        "dependencies_tables": ["opportunities", "opportunity_stages"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_presale_workorder_timeout",
        "name": "售前工单超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_presale_workorder_timeout",
        "cron": {"hour": 16, "minute": 0},
        "owner": "Presales",
        "category": "Sales",
        "description": "16:00 扫描售前工单超时情况。",
        "enabled": True,
        "dependencies_tables": ["presale_workorders"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "sales_reminder_scan",
        "name": "销售提醒扫描",
        "module": "app.utils.scheduled_tasks",
        "callable": "sales_reminder_scan",
        "cron": {"hour": 9, "minute": 0},
        "owner": "Sales",
        "category": "Sales",
        "description": "每天9点扫描销售里程碑、收款计划等需要提醒的事项并发送通知。",
        "enabled": True,
        "dependencies_tables": ["opportunities", "project_payment_plans", "projects"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_contract_expiry_reminder",
        "name": "合同到期提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_contract_expiry_reminder",
        "cron": {"hour": 9, "minute": 0},
        "owner": "HR",
        "category": "HR Management",
        "description": "每天9点扫描即将到期的员工合同（提前60天、30天、14天提醒），并生成提醒记录。",
        "enabled": True,
        "dependencies_tables": ["employee_contracts", "contract_reminders", "employees"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_employee_confirmation_reminder",
        "name": "员工转正提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_employee_confirmation_reminder",
        "cron": {"hour": 9, "minute": 15},
        "owner": "HR",
        "category": "HR Management",
        "description": "每天9:15扫描即将到期的试用期员工（提前7天提醒），生成转正提醒。",
        "enabled": True,
        "dependencies_tables": ["employees", "employee_hr_profiles", "hr_transactions"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
]
