# -*- coding: utf-8 -*-
"""
工时管理任务配置
"""

TIMESHEET_TASKS = [
    {
        "id": "daily_timesheet_aggregation",
        "name": "每日工时汇总",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_timesheet_aggregation_task",
        "cron": {"hour": 1, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天凌晨1点汇总前一天的工时数据",
        "enabled": True,
        "dependencies_tables": ["timesheet", "timesheet_summary"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "weekly_timesheet_aggregation",
        "name": "每周工时汇总",
        "module": "app.utils.scheduled_tasks",
        "callable": "weekly_timesheet_aggregation_task",
        "cron": {"day_of_week": "mon", "hour": 2, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每周一凌晨2点汇总上一周的工时数据",
        "enabled": True,
        "dependencies_tables": ["timesheet", "timesheet_summary"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "monthly_timesheet_aggregation",
        "name": "每月工时汇总",
        "module": "app.utils.scheduled_tasks",
        "callable": "monthly_timesheet_aggregation_task",
        "cron": {"day": 1, "hour": 3, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每月1号凌晨3点汇总上个月的工时数据",
        "enabled": True,
        "dependencies_tables": ["timesheet", "timesheet_summary"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 1800,
            "retry_on_failure": True,
        },
    },
    {
        "id": "generate_monthly_reports",
        "name": "生成月度报表",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_monthly_reports_task",
        "cron": {"day": 1, "hour": 4, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每月1号凌晨4点生成上个月的各类报表并同步到各系统",
        "enabled": True,
        "dependencies_tables": ["timesheet", "financial_project_costs", "rd_cost", "project_cost"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 3600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "daily_timesheet_reminder",
        "name": "每日工时填报提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_timesheet_reminder_task",
        "cron": {"hour": 9, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天上午9点提醒未填报昨天工时的用户",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "user_roles", "roles", "departments"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "weekly_timesheet_reminder",
        "name": "每周工时填报提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "weekly_timesheet_reminder_task",
        "cron": {"day_of_week": "mon", "hour": 10, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每周一上午10点提醒未完成上周工时填报的用户",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "user_roles", "roles", "departments"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "timesheet_anomaly_alert",
        "name": "异常工时预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "timesheet_anomaly_alert_task",
        "cron": {"hour": 14, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天下午2点检测并提醒异常工时记录",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "timesheet_approval_timeout_reminder",
        "name": "工时审批超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "timesheet_approval_timeout_reminder_task",
        "cron": {"hour": 11, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天上午11点和下午3点提醒审批超时的记录",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "departments", "projects"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "timesheet_sync_failure_alert",
        "name": "工时数据同步失败提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "timesheet_sync_failure_alert_task",
        "cron": {"hour": 16, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天下午4点检查并提醒同步失败的记录",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "financial_project_costs", "rd_costs", "project_costs"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
]
