# -*- coding: utf-8 -*/
"""
采购和装配阶段定义 (S13-S16)

包含：
- S13: 机械装配
- S14: 电气装配
- S15: 软件开发与调试
- S16: 整机联调
"""

from typing import Any, Dict, List

# 采购和装配阶段 (S13-S16)
PROCUREMENT_ASSEMBLY_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S13",
            "stage_name": "机械装配",
            "sequence": 12,
            "category": "execution",
            "estimated_days": 14,
            "description": "装配准备、框架装配、模块装配、机械调试（与电气/软件并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S13N01",
                    "node_name": "装配准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物料领用、工位准备、装配工艺卡确认、工装/工具准备",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["PMC"],
                    "deliverables": ["领料单"],
                },
                {
                    "node_code": "S13N02",
                    "node_name": "框架装配",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "底座安装调平、框架组装、防护罩安装、基准建立",
                    "dependency_node_codes": ["S13N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["SE", "FIN"],
                    "deliverables": ["成本核算表"],
                },
                {
                    "node_code": "S13N03",
                    "node_name": "模块装配",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "上下料机构装配、定位机构装配、测试工位装配、传输机构装配、治具安装",
                    "dependency_node_codes": ["S13N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["报价单", "报价明细表"],
                },
                {
                    "node_code": "S13N04",
                    "node_name": "机械调试",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "运动机构调试、定位精度调试、重复精度验证、干涉检查",
                    "dependency_node_codes": ["S13N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["投标文件"],
                },
                {
                    "node_code": "S13N05",
                    "node_name": "机械自检",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "装配自检、问题整改、机械完工确认",
                    "dependency_node_codes": ["S13N04"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE"],
                    "deliverables": ["报价提交回执"],
                },
            ],
        },
        {
            "stage_code": "S14",
            "stage_name": "电气装配",
            "sequence": 13,
            "category": "execution",
            "estimated_days": 10,
            "description": "电气安装、电气接线、电气调试（与机械/软件并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S14N01",
                    "node_name": "电气安装",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "控制柜安装、线槽/线管布设、线缆敷设、传感器/执行器安装",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["ME"],
                    "deliverables": ["模块装配记录"],
                },
                {
                    "node_code": "S14N02",
                    "node_name": "电气接线",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "柜内接线、现场接线、接线检查、绝缘/接地测试",
                    "dependency_node_codes": ["S14N01"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["SE", "PM"],
                    "deliverables": ["谈判记录"],
                },
                {
                    "node_code": "S14N03",
                    "node_name": "电气调试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "上电前检查、分步上电测试、I/O点检、运动轴调试、安全回路验证",
                    "dependency_node_codes": ["S14N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": [],
                    "deliverables": ["中标通知书"],
                },
                {
                    "node_code": "S14N04",
                    "node_name": "电气自检",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "电气功能自检、问题整改、电气完工确认",
                    "dependency_node_codes": ["S14N03"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["技术协议"],
                },
            ],
        },
        {
            "stage_code": "S15",
            "stage_name": "软件开发与调试",
            "sequence": 14,
            "category": "execution",
            "estimated_days": 21,
            "description": "底层软件开发、上位机软件开发、测试算法开发、软件联调（与机械/电气并行）",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": True,
            "nodes": [
                {
                    "node_code": "S15N01",
                    "node_name": "底层软件开发",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "PLC程序开发、运动控制程序开发、通讯程序开发、安全程序开发",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["ME"],
                    "deliverables": ["机械调试记录"],
                },
                {
                    "node_code": "S15N02",
                    "node_name": "上位机软件开发",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 7,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "界面开发、业务逻辑开发、数据库开发、报表功能开发",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["机械自检报告"],
                },
                {
                    "node_code": "S15N03",
                    "node_name": "测试算法开发",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "算法编码、算法调试、算法验证、算法优化",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["电气安装记录"],
                },
                {
                    "node_code": "S15N04",
                    "node_name": "软件联调",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "底层与上位机联调、各模块联调、异常处理测试、性能测试",
                    "dependency_node_codes": ["S15N01", "S15N02", "S15N03"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["FIN"],
                    "deliverables": ["商务合同"],
                },
                {
                    "node_code": "S15N05",
                    "node_name": "软件自检",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "功能自检、bug修复、软件完工确认",
                    "dependency_node_codes": ["S15N04"],
                    "owner_role_code": "FIN",
                    "participant_role_codes": ["SALES"],
                    "deliverables": ["首付款发票", "到账确认单"],
                },
            ],
        },
        {
            "stage_code": "S16",
            "stage_name": "整机联调",
            "sequence": 15,
            "category": "execution",
            "estimated_days": 10,
            "description": "空载联调、带载联调、性能验证、问题整改",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S16N01",
                    "node_name": "空载联调",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "空载运行测试、流程验证、节拍测试、异常处理验证",
                    "owner_role_code": "ASM",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["接线检查记录"],
                },
                {
                    "node_code": "S16N02",
                    "node_name": "带载联调",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "产品上料测试、全流程测试、测试结果验证、数据记录验证",
                    "dependency_node_codes": ["S16N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SALES", "FIN"],
                    "deliverables": ["正式立项申请单", "项目编号"],
                },
                {
                    "node_code": "S16N03",
                    "node_name": "性能验证",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "节拍验证、精度验证、良率验证、稳定性验证",
                    "dependency_node_codes": ["S16N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SE", "SALES"],
                    "deliverables": ["项目移交清单", "移交确认单"],
                },
                {
                    "node_code": "S16N04",
                    "node_name": "问题整改",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "问题清单整理、问题分析、整改实施、整改验证",
                    "dependency_node_codes": ["S16N03"],
                    "owner_role_code": "PM",
                    "participant_role_codes": [],
                    "deliverables": ["项目团队名单", "职责分工表"],
                },
            ],
        },
]
