# -*- coding: utf-8 -*-
"""
项目启动和设计阶段定义 (S09-S12)

包含：
- S09: 项目正式立项
- S10: 详细方案设计
- S11: 详细设计
- S12: 采购与外协
"""

from typing import Any, Dict, List

# 项目启动和设计阶段 (S09-S12)
PROJECT_INITIATION_STAGES: List[Dict[str, Any]] = [
    {
        "stage_code": "S09",
        "stage_name": "项目正式立项",
        "sequence": 8,
        "category": "execution",
        "estimated_days": 7,
        "description": "⭐项目正式启动：正式立项审批、项目移交、团队组建、启动会",
        "is_required": True,
        "is_milestone": True,
        "is_parallel": False,
        "nodes": [
            {
                "node_code": "S09N01",
                "node_name": "正式立项审批",
                "node_type": "APPROVAL",
                "sequence": 0,
                "estimated_days": 2,
                "completion_method": "APPROVAL",
                "is_required": True,
                "description": "正式立项申请、合同/首付款确认、正式项目编号分配、立项审批通过、立项通知发布",
                "owner_role_code": "PM",
                "participant_role_codes": ["SALES", "FIN"],
                "deliverables": ["正式立项申请单", "项目编号"],
            },
            {
                "node_code": "S09N02",
                "node_name": "项目移交",
                "node_type": "TASK",
                "sequence": 1,
                "estimated_days": 1,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "售前资料移交(方案/图纸/样品/沟通记录)、技术协议移交、样品/图纸移交、关键风险点移交、遗留问题移交、移交确认签字",
                "dependency_node_codes": ["S09N01"],
                "owner_role_code": "SE",
                "participant_role_codes": ["SALES", "ME", "EE", "PM"],
                "deliverables": ["需求评审纪要", "评审结论"],
            },
            {
                "node_code": "S09N03",
                "node_name": "项目团队组建",
                "node_type": "TASK",
                "sequence": 2,
                "estimated_days": 1,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "项目经理任命、核心团队组建(机械/电气/软件/测试)、职责分工明确、项目群组建立",
                "dependency_node_codes": ["S09N01"],
                "owner_role_code": "SALES",
                "participant_role_codes": ["SE", "PM"],
                "deliverables": ["初立项申请单", "临时项目编号"],
            },
            {
                "node_code": "S09N04",
                "node_name": "项目启动会",
                "node_type": "MILESTONE",
                "sequence": 3,
                "estimated_days": 1,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "项目启动会召开、客户需求宣贯、售前方案宣贯、里程碑计划制定、风险识别与应对、启动会议纪要签发",
                "dependency_node_codes": ["S09N02", "S09N03"],
                "owner_role_code": "PM",
                "participant_role_codes": ["SE", "SALES"],
                "deliverables": ["售前团队名单", "售前计划"],
            },
            {
                "node_code": "S09N05",
                "node_name": "输入资料确认",
                "node_type": "TASK",
                "sequence": 4,
                "estimated_days": 2,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "产品图纸/3D模型确认、测试标准/规范确认、产能/节拍要求确认、接口定义确认、特殊要求确认、客户对接人确认",
                "dependency_node_codes": ["S09N04"],
                "owner_role_code": "SE",
                "participant_role_codes": ["TE"],
                "deliverables": ["技术预研报告", "可行性分析报告"],
            },
        ],
    },
    {
        "stage_code": "S10",
        "stage_name": "详细方案设计",
        "sequence": 9,
        "category": "execution",
        "estimated_days": 10,
        "description": "方案深化、技术规格书编制、方案确认冻结",
        "is_required": True,
        "is_milestone": False,
        "is_parallel": False,
        "nodes": [
            {
                "node_code": "S10N01",
                "node_name": "方案深化",
                "node_type": "TASK",
                "sequence": 0,
                "estimated_days": 5,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "售前方案评估、方案优化调整、详细布局设计、详细工艺流程、详细测试方案",
                "owner_role_code": "SE",
                "participant_role_codes": ["ME", "EE", "SW"],
                "deliverables": ["深化方案"],
            },
            {
                "node_code": "S10N02",
                "node_name": "技术规格书",
                "node_type": "DELIVERABLE",
                "sequence": 1,
                "estimated_days": 3,
                "completion_method": "UPLOAD",
                "is_required": True,
                "required_attachments": True,
                "description": "设备技术规格书编制、测试项目清单确认、性能指标定义、验收标准拟定",
                "dependency_node_codes": ["S10N01"],
                "owner_role_code": "SE",
                "participant_role_codes": ["ME", "EE"],
                "deliverables": ["概念方案", "布局图"],
            },
            {
                "node_code": "S10N03",
                "node_name": "方案确认",
                "node_type": "APPROVAL",
                "sequence": 2,
                "estimated_days": 2,
                "completion_method": "APPROVAL",
                "is_required": True,
                "description": "详细方案内部评审、详细方案客户汇报、客户签字确认、方案冻结",
                "dependency_node_codes": ["S10N02"],
                "owner_role_code": "SE",
                "participant_role_codes": ["ME", "EE", "SW"],
                "deliverables": ["详细技术方案", "初步BOM"],
            },
        ],
    },
    {
        "stage_code": "S11",
        "stage_name": "详细设计",
        "sequence": 10,
        "category": "execution",
        "estimated_days": 21,
        "description": "机械/电气/软件/测试方案详细设计（并行）",
        "is_required": True,
        "is_milestone": False,
        "is_parallel": True,
        "nodes": [
            {
                "node_code": "S11N01",
                "node_name": "机械设计",
                "node_type": "DELIVERABLE",
                "sequence": 0,
                "estimated_days": 14,
                "completion_method": "UPLOAD",
                "is_required": True,
                "required_attachments": True,
                "description": "总体结构设计、治具/夹具设计、运动机构设计、防护/安全设计、标准件选型、非标件出图、机械BOM输出、机械设计评审",
                "owner_role_code": "ME",
                "participant_role_codes": [],
                "deliverables": ["3D总装图", "2D零件图", "机械BOM"],
            },
            {
                "node_code": "S11N02",
                "node_name": "电气设计",
                "node_type": "DELIVERABLE",
                "sequence": 1,
                "estimated_days": 14,
                "completion_method": "UPLOAD",
                "is_required": True,
                "required_attachments": True,
                "description": "电气原理图设计、控制柜布局设计、线缆走向设计、传感器/执行器选型、PLC/运动控制选型、安全回路设计、电气BOM输出、电气设计评审",
                "owner_role_code": "EE",
                "participant_role_codes": [],
                "deliverables": ["电气原理图", "控制柜布局图", "电气BOM"],
            },
            {
                "node_code": "S11N03",
                "node_name": "软件设计",
                "node_type": "DELIVERABLE",
                "sequence": 2,
                "estimated_days": 10,
                "completion_method": "UPLOAD",
                "is_required": True,
                "required_attachments": True,
                "description": "软件功能规格书、系统架构设计、接口协议定义、数据库设计、UI界面设计、软件设计评审",
                "owner_role_code": "SW",
                "participant_role_codes": [],
                "deliverables": ["软件设计文档", "接口协议", "UI设计稿"],
            },
            {
                "node_code": "S11N04",
                "node_name": "测试方案设计",
                "node_type": "DELIVERABLE",
                "sequence": 3,
                "estimated_days": 10,
                "completion_method": "UPLOAD",
                "is_required": True,
                "required_attachments": True,
                "description": "测试流程设计、测试算法设计、判定逻辑设计、数据处理方案、报表格式设计",
                "owner_role_code": "TE",
                "participant_role_codes": ["SW"],
                "deliverables": ["测试方案", "测试算法说明"],
            },
            {
                "node_code": "S11N05",
                "node_name": "设计输出确认",
                "node_type": "APPROVAL",
                "sequence": 4,
                "estimated_days": 2,
                "completion_method": "APPROVAL",
                "is_required": True,
                "description": "图纸会签、BOM冻结、设计变更控制启动、采购清单输出",
                "dependency_node_codes": ["S11N01", "S11N02", "S11N03", "S11N04"],
                "owner_role_code": "SE",
                "participant_role_codes": ["ME", "EE", "SW", "PM"],
                "deliverables": ["方案评审纪要"],
            },
        ],
    },
    {
        "stage_code": "S12",
        "stage_name": "采购与外协",
        "sequence": 11,
        "category": "execution",
        "estimated_days": 21,
        "description": "采购启动、到货管理、外协加工管理",
        "is_required": True,
        "is_milestone": False,
        "is_parallel": False,
        "nodes": [
            {
                "node_code": "S12N01",
                "node_name": "采购启动",
                "node_type": "TASK",
                "sequence": 0,
                "estimated_days": 5,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "采购清单分类(标准件/非标件/外购件)、供应商询价、交期确认、采购订单下达",
                "owner_role_code": "PMC",
                "participant_role_codes": [],
                "deliverables": ["采购订单"],
            },
            {
                "node_code": "S12N02",
                "node_name": "到货管理",
                "node_type": "TASK",
                "sequence": 1,
                "estimated_days": 14,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "标准件到货检验、非标件加工跟踪、外购件到货检验、不合格品处理、物料齐套确认",
                "dependency_node_codes": ["S12N01"],
                "owner_role_code": "SE",
                "participant_role_codes": ["SALES"],
                "deliverables": ["方案汇报PPT", "客户沟通纪要"],
            },
            {
                "node_code": "S12N03",
                "node_name": "外协加工管理",
                "node_type": "TASK",
                "sequence": 2,
                "estimated_days": 14,
                "completion_method": "MANUAL",
                "is_required": True,
                "description": "外协图纸发放、外协进度跟踪、外协件首检、外协件入库",
                "dependency_node_codes": ["S12N01"],
                "owner_role_code": "SE",
                "participant_role_codes": ["SALES", "PM"],
                "deliverables": ["冻结版技术方案", "客户确认函"],
            },
        ],
    },
]
