# -*- coding: utf-8 -*/
"""
调试和验收阶段定义 (S17-S20)

包含：
- S17: 内部验收
- S18: 出厂发运
- S19: 现场安装调试
- S20: 客户验收
"""

from typing import Any, Dict, List

# 调试和验收阶段 (S17-S20)
TESTING_ACCEPTANCE_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S17",
            "stage_name": "内部验收",
            "sequence": 16,
            "category": "execution",
            "estimated_days": 5,
            "description": "验收准备、功能验收、性能验收、资料验收、内部评审",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S17N01",
                    "node_name": "验收准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "验收计划制定、验收标准确认、验收环境准备、验收人员组织",
                    "owner_role_code": "EE",
                    "participant_role_codes": ["ASM"],
                    "deliverables": ["电气调试记录", "I/O点检表"],
                },
                {
                    "node_code": "S17N02",
                    "node_name": "功能验收",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "功能逐项验证、操作便捷性验证、异常处理验证",
                    "dependency_node_codes": ["S17N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["SE", "ME", "EE", "SW", "TE"],
                    "deliverables": ["启动会议纪要", "里程碑计划"],
                },
                {
                    "node_code": "S17N03",
                    "node_name": "性能验收",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "节拍验收、精度验收、稳定性验收",
                    "dependency_node_codes": ["S17N02"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["输入资料确认单"],
                },
                {
                    "node_code": "S17N04",
                    "node_name": "资料验收",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "图纸资料完整性检查、操作手册检查、培训资料检查",
                    "dependency_node_codes": ["S17N03"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["深化方案"],
                },
                {
                    "node_code": "S17N05",
                    "node_name": "内部评审",
                    "node_type": "APPROVAL",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "内部验收评审会、遗留问题确认、出厂放行决定",
                    "dependency_node_codes": ["S17N04"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["TE"],
                    "deliverables": ["技术规格书", "验收标准"],
                },
            ],
        },
        {
            "stage_code": "S18",
            "stage_name": "出厂发运",
            "sequence": 17,
            "category": "execution",
            "estimated_days": 5,
            "description": "出厂准备、包装、发运",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S18N01",
                    "node_name": "出厂准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "出厂资料准备、设备清洁、随机备件准备、包装材料准备",
                    "owner_role_code": "EE",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["电气自检报告"],
                },
                {
                    "node_code": "S18N02",
                    "node_name": "包装",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备拆分、防护处理、装箱、箱唛标识",
                    "dependency_node_codes": ["S18N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["PM", "SALES"],
                    "deliverables": ["方案确认单", "客户签字"],
                },
                {
                    "node_code": "S18N03",
                    "node_name": "发运",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物流安排、装车、运输跟踪、到达确认",
                    "dependency_node_codes": ["S18N02"],
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["3D总装图", "2D零件图", "机械BOM"],
                },
            ],
        },
        {
            "stage_code": "S19",
            "stage_name": "现场安装调试",
            "sequence": 18,
            "category": "execution",
            "estimated_days": 14,
            "description": "现场准备、现场安装、现场调试、现场问题处理",
            "is_required": True,
            "is_milestone": False,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S19N01",
                    "node_name": "现场准备",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "现场环境确认、水电气确认、吊装条件确认、开箱检查",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["PLC程序", "运动控制程序"],
                },
                {
                    "node_code": "S19N02",
                    "node_name": "现场安装",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备就位、设备组装、水电气接入、设备调平",
                    "dependency_node_codes": ["S19N01"],
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["电气原理图", "控制柜布局图", "电气BOM"],
                },
                {
                    "node_code": "S19N03",
                    "node_name": "现场调试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "上电调试、参数调整、流程验证、性能验证",
                    "dependency_node_codes": ["S19N02"],
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["软件设计文档", "接口协议", "UI设计稿"],
                },
                {
                    "node_code": "S19N04",
                    "node_name": "现场问题处理",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "问题记录、问题分析、现场整改、整改验证",
                    "dependency_node_codes": ["S19N03"],
                    "owner_role_code": "TE",
                    "participant_role_codes": ["SW"],
                    "deliverables": ["测试方案", "测试算法说明"],
                },
            ],
        },
        {
            "stage_code": "S20",
            "stage_name": "客户验收",
            "sequence": 19,
            "category": "execution",
            "estimated_days": 7,
            "description": "预验收、正式验收、验收签字",
            "is_required": True,
            "is_milestone": True,
            "is_parallel": False,
            "nodes": [
                {
                    "node_code": "S20N01",
                    "node_name": "预验收",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "预验收计划、功能预验收、性能预验收、问题整改",
                    "owner_role_code": "SW",
                    "participant_role_codes": [],
                    "deliverables": ["上位机软件"],
                },
                {
                    "node_code": "S20N02",
                    "node_name": "正式验收",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "正式验收计划、功能正式验收、性能正式验收、连续运行验证",
                    "dependency_node_codes": ["S20N01"],
                    "owner_role_code": "SE",
                    "participant_role_codes": ["ME", "EE", "SW", "PM"],
                    "deliverables": ["会签记录", "冻结BOM", "采购清单"],
                },
                {
                    "node_code": "S20N03",
                    "node_name": "验收签字",
                    "node_type": "MILESTONE",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "验收报告编制、遗留问题确认、验收单签署、验收款支付申请",
                    "dependency_node_codes": ["S20N02"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["采购订单"],
                },
            ],
        },
]
