-- Installation Dispatch module migration (MySQL)
-- Creates installation_dispatch_orders table

CREATE TABLE IF NOT EXISTS installation_dispatch_orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    order_no VARCHAR(50) UNIQUE NOT NULL COMMENT '派工单号',
    project_id INT NOT NULL COMMENT '项目ID',
    machine_id INT NULL COMMENT '机台ID',
    customer_id INT NOT NULL COMMENT '客户ID',
    task_type VARCHAR(20) NOT NULL COMMENT '任务类型',
    task_title VARCHAR(200) NOT NULL COMMENT '任务标题',
    task_description TEXT NULL COMMENT '任务描述',
    location VARCHAR(200) NULL COMMENT '现场地点',
    scheduled_date DATE NOT NULL COMMENT '计划日期',
    estimated_hours DECIMAL(5, 2) NULL COMMENT '预计工时（小时）',
    assigned_to_id INT NULL COMMENT '派工人员ID',
    assigned_to_name VARCHAR(50) NULL COMMENT '派工人员姓名',
    assigned_by_id INT NULL COMMENT '派工人ID',
    assigned_by_name VARCHAR(50) NULL COMMENT '派工人姓名',
    assigned_time DATETIME NULL COMMENT '派工时间',
    status VARCHAR(20) DEFAULT 'PENDING' NOT NULL COMMENT '状态',
    priority VARCHAR(20) DEFAULT 'NORMAL' NOT NULL COMMENT '优先级',
    start_time DATETIME NULL COMMENT '开始时间',
    end_time DATETIME NULL COMMENT '结束时间',
    actual_hours DECIMAL(5, 2) NULL COMMENT '实际工时（小时）',
    progress INT DEFAULT 0 COMMENT '进度百分比（0-100）',
    customer_contact VARCHAR(50) NULL COMMENT '客户联系人',
    customer_phone VARCHAR(20) NULL COMMENT '客户电话',
    customer_address VARCHAR(500) NULL COMMENT '客户地址',
    execution_notes TEXT NULL COMMENT '执行说明',
    issues_found TEXT NULL COMMENT '发现的问题',
    solution_provided TEXT NULL COMMENT '提供的解决方案',
    photos JSON NULL COMMENT '现场照片列表',
    service_record_id INT NULL COMMENT '关联服务记录ID',
    acceptance_order_id INT NULL COMMENT '关联验收单ID',
    remark TEXT NULL COMMENT '备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (machine_id) REFERENCES machines(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id),
    FOREIGN KEY (assigned_to_id) REFERENCES users(id),
    FOREIGN KEY (assigned_by_id) REFERENCES users(id),
    FOREIGN KEY (service_record_id) REFERENCES service_records(id),
    FOREIGN KEY (acceptance_order_id) REFERENCES acceptance_orders(id),
    INDEX idx_install_dispatch_project (project_id),
    INDEX idx_install_dispatch_machine (machine_id),
    INDEX idx_install_dispatch_customer (customer_id),
    INDEX idx_install_dispatch_status (status),
    INDEX idx_install_dispatch_assigned (assigned_to_id),
    INDEX idx_install_dispatch_date (scheduled_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安装调试派工单表';
