CREATE TABLE IF NOT EXISTS project_risks (
	id INTEGER NOT NULL, 
	risk_code VARCHAR(50) NOT NULL, 
	project_id INTEGER NOT NULL, 
	risk_name VARCHAR(200) NOT NULL, 
	description TEXT, 
	risk_type VARCHAR(9) NOT NULL, 
	probability INTEGER NOT NULL, 
	impact INTEGER NOT NULL, 
	risk_score INTEGER NOT NULL, 
	risk_level VARCHAR(20), 
	mitigation_plan TEXT, 
	contingency_plan TEXT, 
	owner_id INTEGER, 
	owner_name VARCHAR(50), 
	status VARCHAR(10) NOT NULL, 
	identified_date DATETIME, 
	target_closure_date DATETIME, 
	actual_closure_date DATETIME, 
	is_occurred BOOLEAN, 
	occurrence_date DATETIME, 
	actual_impact TEXT, 
	created_by_id INTEGER, 
	created_by_name VARCHAR(50), 
	updated_by_id INTEGER, 
	updated_by_name VARCHAR(50), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (risk_code), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(owner_id) REFERENCES users (id), 
	FOREIGN KEY(created_by_id) REFERENCES users (id), 
	FOREIGN KEY(updated_by_id) REFERENCES users (id)
);
