-- APPR-13: normalize sales contract statuses to the canonical uppercase vocabulary.
-- This migration is intentionally data-only and idempotent for SQLite.

BEGIN TRANSACTION;

UPDATE contracts
SET status = CASE UPPER(TRIM(status))
    WHEN 'DRAFT' THEN 'DRAFT'
    WHEN 'APPROVING' THEN 'PENDING_APPROVAL'
    WHEN 'PENDING_APPROVAL' THEN 'PENDING_APPROVAL'
    WHEN 'REVIEW' THEN 'APPROVED'
    WHEN 'APPROVED' THEN 'APPROVED'
    WHEN 'REJECTED' THEN 'REJECTED'
    WHEN 'SIGNED' THEN 'SIGNED'
    WHEN 'ACTIVE' THEN 'EXECUTING'
    WHEN 'EXECUTING' THEN 'EXECUTING'
    WHEN 'COMPLETED' THEN 'COMPLETED'
    WHEN 'CANCELLED' THEN 'CANCELLED'
    WHEN 'CANCELED' THEN 'CANCELLED'
    WHEN 'TERMINATED' THEN 'CANCELLED'
    WHEN 'VOIDED' THEN 'CANCELLED'
    ELSE UPPER(TRIM(status))
END
WHERE status IS NOT NULL
  AND TRIM(status) <> ''
  AND status <> CASE UPPER(TRIM(status))
      WHEN 'DRAFT' THEN 'DRAFT'
      WHEN 'APPROVING' THEN 'PENDING_APPROVAL'
      WHEN 'PENDING_APPROVAL' THEN 'PENDING_APPROVAL'
      WHEN 'REVIEW' THEN 'APPROVED'
      WHEN 'APPROVED' THEN 'APPROVED'
      WHEN 'REJECTED' THEN 'REJECTED'
      WHEN 'SIGNED' THEN 'SIGNED'
      WHEN 'ACTIVE' THEN 'EXECUTING'
      WHEN 'EXECUTING' THEN 'EXECUTING'
      WHEN 'COMPLETED' THEN 'COMPLETED'
      WHEN 'CANCELLED' THEN 'CANCELLED'
      WHEN 'CANCELED' THEN 'CANCELLED'
      WHEN 'TERMINATED' THEN 'CANCELLED'
      WHEN 'VOIDED' THEN 'CANCELLED'
      ELSE UPPER(TRIM(status))
  END;

COMMIT;

-- Optional verification:
-- SELECT status, COUNT(*) FROM contracts GROUP BY status ORDER BY status;
