-- TEN-03（补建幽灵缺口）：这 20 张表在 ORM 里已经有模型声明（含 tenant_id
-- 字段），但 data/app.db 里从未真正建过表——此前的迁移历史里漏跑了，不是
-- 本次改动引入的缺口。既然模型已经存在且已经声明了 tenant_id，直接按模型
-- 定义建表最省事也最不容易和 ORM 产生偏差（用 SQLAlchemy CreateTable 编译器
-- 从当前模型反向生成 DDL，保证列定义、外键、唯一约束与 ORM 完全一致）。

-- AfterSalesFieldService (app.models.after_sales)
CREATE TABLE after_sales_field_services (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER, 
	customer_id INTEGER, 
	ticket_id INTEGER, 
	dispatch_order_id INTEGER, 
	service_no VARCHAR(50), 
	service_type VARCHAR(30), 
	service_content TEXT, 
	planned_date DATE, 
	actual_date DATE, 
	service_hours INTEGER, 
	travel_hours INTEGER, 
	engineer_id INTEGER, 
	engineer_name VARCHAR(100), 
	travel_cost NUMERIC(12, 2), 
	parts_cost NUMERIC(12, 2), 
	service_fee NUMERIC(12, 2), 
	total_cost NUMERIC(12, 2), 
	is_warranty BOOLEAN, 
	warranty_source VARCHAR(30), 
	charge_required BOOLEAN, 
	charge_reason VARCHAR(50), 
	charge_status VARCHAR(20), 
	report_content TEXT, 
	customer_sign BOOLEAN, 
	status VARCHAR(20), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(ticket_id) REFERENCES after_sales_support_tickets (id), 
	FOREIGN KEY(dispatch_order_id) REFERENCES installation_dispatch_orders (id), 
	UNIQUE (service_no), 
	FOREIGN KEY(engineer_id) REFERENCES users (id)
);

-- AfterSalesKnowledge (app.models.after_sales)
CREATE TABLE after_sales_knowledge (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	title VARCHAR(200), 
	category VARCHAR(30), 
	content TEXT, 
	keywords VARCHAR(500), 
	project_type VARCHAR(50), 
	product_category VARCHAR(100), 
	view_count INTEGER, 
	helpful_count INTEGER, 
	status VARCHAR(20), 
	created_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);

-- AfterSalesSatisfaction (app.models.after_sales)
CREATE TABLE after_sales_satisfaction (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER, 
	customer_id INTEGER, 
	ticket_id INTEGER, 
	field_service_id INTEGER, 
	overall_score INTEGER, 
	response_score INTEGER, 
	quality_score INTEGER, 
	attitude_score INTEGER, 
	nps_score INTEGER, 
	comments TEXT, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(ticket_id) REFERENCES after_sales_support_tickets (id), 
	FOREIGN KEY(field_service_id) REFERENCES after_sales_field_services (id)
);

-- AfterSalesSLA (app.models.after_sales)
CREATE TABLE after_sales_sla (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER, 
	ticket_id INTEGER, 
	response_target_hours INTEGER, 
	resolve_target_hours INTEGER, 
	actual_response_hours INTEGER, 
	actual_resolve_hours INTEGER, 
	response_met BOOLEAN, 
	resolve_met BOOLEAN, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(ticket_id) REFERENCES after_sales_support_tickets (id)
);

-- AfterSalesSparePart (app.models.after_sales)
CREATE TABLE after_sales_spare_parts (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER, 
	part_no VARCHAR(50), 
	part_name VARCHAR(200), 
	part_spec VARCHAR(500), 
	quantity INTEGER, 
	min_stock INTEGER, 
	unit_price NUMERIC(12, 2), 
	supplier VARCHAR(200), 
	lead_time_days INTEGER, 
	status VARCHAR(20), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);

-- AfterSalesWarranty (app.models.after_sales)
CREATE TABLE after_sales_warranty (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER, 
	customer_id INTEGER, 
	warranty_no VARCHAR(50), 
	warranty_type VARCHAR(30), 
	warranty_start DATE, 
	warranty_end DATE, 
	warranty_months INTEGER, 
	scope TEXT, 
	exclusions TEXT, 
	status VARCHAR(20), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	UNIQUE (warranty_no)
);

-- EngineerCapacity (app.models.engineer_capacity)
CREATE TABLE engineer_capacity (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	engineer_id INTEGER NOT NULL, 
	engineer_name VARCHAR(100), 
	department_id INTEGER, 
	avg_concurrent_projects FLOAT, 
	max_concurrent_projects INTEGER, 
	current_project_count INTEGER, 
	mech_design_efficiency FLOAT, 
	electric_design_efficiency FLOAT, 
	assembly_efficiency FLOAT, 
	debugging_efficiency FLOAT, 
	avg_quality_score FLOAT, 
	on_time_delivery_rate FLOAT, 
	rework_rate FLOAT, 
	skill_tags TEXT, 
	specialty_areas TEXT, 
	ai_skill_level VARCHAR(20), 
	ai_tools TEXT, 
	ai_usage_frequency VARCHAR(20), 
	ai_efficiency_boost FLOAT, 
	ai_code_acceptance_rate FLOAT, 
	ai_saved_hours FLOAT, 
	ai_learning_score FLOAT, 
	multi_project_capacity INTEGER, 
	multi_project_efficiency FLOAT, 
	context_switch_cost FLOAT, 
	standardization_score FLOAT, 
	modularity_score FLOAT, 
	reuse_rate FLOAT, 
	standard_modules_created INTEGER, 
	documentation_quality FLOAT, 
	workload_status VARCHAR(20), 
	available_hours_per_week FLOAT, 
	booked_hours_per_week FLOAT, 
	last_evaluation_date DATE, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(engineer_id) REFERENCES users (id)
);

-- WorkloadWarning (app.models.engineer_capacity)
CREATE TABLE workload_warnings (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	warning_no VARCHAR(50), 
	engineer_id INTEGER, 
	project_id INTEGER, 
	department_id INTEGER, 
	warning_type VARCHAR(50) NOT NULL, 
	warning_level VARCHAR(20), 
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	impact TEXT, 
	suggestion TEXT, 
	data_snapshot TEXT, 
	status VARCHAR(20), 
	acknowledged_by INTEGER, 
	acknowledged_at DATETIME, 
	resolved_at DATETIME, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	UNIQUE (warning_no), 
	FOREIGN KEY(engineer_id) REFERENCES users (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(acknowledged_by) REFERENCES users (id)
);

-- ExpediteRecord (app.models.kitting_optimization)
CREATE TABLE expedite_records (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	shortage_id INTEGER, 
	material_id INTEGER NOT NULL, 
	supplier_id INTEGER, 
	purchase_order_id INTEGER, 
	project_id INTEGER, 
	material_code VARCHAR(50) NOT NULL, 
	material_name VARCHAR(200) NOT NULL, 
	expedite_type VARCHAR(20), 
	urgency_level VARCHAR(20), 
	shortage_qty NUMERIC(10, 4), 
	required_date DATE, 
	original_promised_date DATE, 
	new_promised_date DATE, 
	notify_method VARCHAR(50), 
	notify_content TEXT, 
	notify_sent_at DATETIME, 
	notify_status VARCHAR(20), 
	status VARCHAR(20), 
	supplier_response TEXT, 
	response_at DATETIME, 
	actual_delivery_date DATE, 
	is_on_time BOOLEAN, 
	created_by INTEGER, 
	remark TEXT, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(shortage_id) REFERENCES material_shortages (id), 
	FOREIGN KEY(material_id) REFERENCES materials (id), 
	FOREIGN KEY(supplier_id) REFERENCES vendors (id), 
	FOREIGN KEY(purchase_order_id) REFERENCES purchase_orders (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);

-- MaterialAlternative (app.models.kitting_optimization)
CREATE TABLE material_alternatives (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	original_material_id INTEGER NOT NULL, 
	alternative_material_id INTEGER NOT NULL, 
	match_score NUMERIC(5, 2), 
	match_reason TEXT, 
	is_verified BOOLEAN, 
	verified_by INTEGER, 
	verified_at DATETIME, 
	price_diff_pct NUMERIC(5, 2), 
	ecn_no VARCHAR(50), 
	ecn_status VARCHAR(20), 
	is_active BOOLEAN, 
	remark TEXT, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(original_material_id) REFERENCES materials (id), 
	FOREIGN KEY(alternative_material_id) REFERENCES materials (id), 
	FOREIGN KEY(verified_by) REFERENCES users (id)
);

-- MaterialProgressSubscription (app.models.material_progress_subscription)
CREATE TABLE material_progress_subscriptions (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	notify_kitting_change BOOLEAN, 
	notify_key_material_arrival BOOLEAN, 
	notify_shortage_alert BOOLEAN, 
	kitting_change_threshold NUMERIC(5, 2), 
	is_active BOOLEAN, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

-- ProjectCostBenchmark (app.models.project.cost_benchmark)
CREATE TABLE project_cost_benchmarks (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	project_id INTEGER NOT NULL, 
	benchmark_project_id INTEGER NOT NULL, 
	similarity_score NUMERIC(5, 2), 
	similarity_level VARCHAR(20), 
	industry_score NUMERIC(5, 2), 
	test_type_score NUMERIC(5, 2), 
	scale_score NUMERIC(5, 2), 
	complexity_score NUMERIC(5, 2), 
	customer_score NUMERIC(5, 2), 
	current_estimated_cost NUMERIC(14, 2), 
	benchmark_actual_cost NUMERIC(14, 2), 
	cost_variance NUMERIC(14, 2), 
	cost_variance_ratio NUMERIC(5, 2), 
	category_comparison JSON, 
	current_estimated_hours NUMERIC(10, 2), 
	benchmark_actual_hours NUMERIC(10, 2), 
	hours_variance NUMERIC(10, 2), 
	hours_variance_ratio NUMERIC(5, 2), 
	variance_analysis TEXT, 
	risk_factors JSON, 
	recommendations JSON, 
	is_primary BOOLEAN, 
	analyzed_at DATETIME, 
	analyzed_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(benchmark_project_id) REFERENCES projects (id), 
	FOREIGN KEY(analyzed_by) REFERENCES users (id)
);

-- SalesDataAuditRequest (app.models.sales.data_audit)
CREATE TABLE sales_data_audit_requests (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_id INTEGER NOT NULL, 
	entity_code VARCHAR(100), 
	change_type VARCHAR(50) NOT NULL, 
	change_reason TEXT, 
	old_value JSON NOT NULL, 
	new_value JSON NOT NULL, 
	changed_fields JSON, 
	status VARCHAR(20) NOT NULL, 
	priority VARCHAR(20) NOT NULL, 
	requester_id INTEGER NOT NULL, 
	requester_dept VARCHAR(100), 
	requested_at DATETIME NOT NULL, 
	reviewer_id INTEGER, 
	reviewed_at DATETIME, 
	review_comment TEXT, 
	applied_at DATETIME, 
	applied_by INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(requester_id) REFERENCES users (id), 
	FOREIGN KEY(reviewer_id) REFERENCES users (id), 
	FOREIGN KEY(applied_by) REFERENCES users (id)
);

-- LeadRequirementBasicV2 (app.models.sales.lead_requirement_v2)
CREATE TABLE lead_requirement_basic_v2 (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	lead_id INTEGER NOT NULL, 
	customer_factory_location VARCHAR(200), 
	target_object_type VARCHAR(100), 
	application_scenario VARCHAR(100), 
	delivery_mode VARCHAR(100), 
	expected_delivery_date DATETIME, 
	requirement_source VARCHAR(100), 
	participant_ids TEXT, 
	requirement_maturity INTEGER, 
	has_sow BOOLEAN, 
	has_interface_doc BOOLEAN, 
	has_drawing_doc BOOLEAN, 
	sample_availability TEXT, 
	customer_support_resources TEXT, 
	key_risk_factors TEXT, 
	veto_triggered BOOLEAN, 
	veto_reason TEXT, 
	requirement_version VARCHAR(50), 
	is_frozen BOOLEAN, 
	frozen_at DATETIME, 
	frozen_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	UNIQUE (lead_id), 
	FOREIGN KEY(lead_id) REFERENCES leads (id), 
	FOREIGN KEY(frozen_by) REFERENCES users (id)
);

-- LeadRequirementFacilityV2 (app.models.sales.lead_requirement_v2)
CREATE TABLE lead_requirement_facility_v2 (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	basic_id INTEGER NOT NULL, 
	power_supply TEXT, 
	air_supply TEXT, 
	environment TEXT, 
	safety_requirements TEXT, 
	space_and_logistics TEXT, 
	customer_site_standards TEXT, 
	customer_supplied_materials TEXT, 
	restricted_brands TEXT, 
	specified_brands TEXT, 
	long_lead_items TEXT, 
	spare_parts_requirement TEXT, 
	after_sales_support TEXT, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	UNIQUE (basic_id), 
	FOREIGN KEY(basic_id) REFERENCES lead_requirement_basic_v2 (id) ON DELETE CASCADE
);

-- LeadRequirementTechnicalV2 (app.models.sales.lead_requirement_v2)
CREATE TABLE lead_requirement_technical_v2 (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	basic_id INTEGER NOT NULL, 
	target_capacity_uph NUMERIC(10, 2), 
	target_capacity_daily NUMERIC(10, 2), 
	target_capacity_shift NUMERIC(10, 2), 
	cycle_time_seconds NUMERIC(10, 2), 
	workstation_count INTEGER, 
	changeover_method VARCHAR(100), 
	yield_target NUMERIC(5, 2), 
	retest_allowed BOOLEAN, 
	retest_max_count INTEGER, 
	traceability_type VARCHAR(50), 
	data_retention_period INTEGER, 
	data_format VARCHAR(100), 
	test_scope TEXT, 
	key_metrics_spec TEXT, 
	coverage_boundary TEXT, 
	exception_handling TEXT, 
	acceptance_method VARCHAR(100), 
	acceptance_basis TEXT, 
	delivery_checklist TEXT, 
	interface_types TEXT, 
	io_point_estimate TEXT, 
	communication_protocols TEXT, 
	upper_system_integration TEXT, 
	data_field_list TEXT, 
	it_security_restrictions TEXT, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	UNIQUE (basic_id), 
	FOREIGN KEY(basic_id) REFERENCES lead_requirement_basic_v2 (id) ON DELETE CASCADE
);

-- SalesOperationLog (app.models.sales.operation_log)
CREATE TABLE sales_operation_logs (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_id INTEGER NOT NULL, 
	entity_code VARCHAR(100), 
	operation_type VARCHAR(50) NOT NULL, 
	operation_desc VARCHAR(500), 
	old_value JSON, 
	new_value JSON, 
	changed_fields JSON, 
	operator_id INTEGER, 
	operator_name VARCHAR(100), 
	operator_dept VARCHAR(100), 
	operation_time DATETIME NOT NULL, 
	ip_address VARCHAR(50), 
	user_agent VARCHAR(500), 
	request_id VARCHAR(100), 
	remark TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(operator_id) REFERENCES users (id)
);

-- StageTemplateChangeLog (app.models.stage_template)
CREATE TABLE stage_template_change_logs (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	template_id INTEGER NOT NULL, 
	action VARCHAR(30) NOT NULL, 
	target_type VARCHAR(20), 
	target_id INTEGER, 
	target_name VARCHAR(100), 
	change_description TEXT, 
	change_detail TEXT, 
	changed_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(template_id) REFERENCES stage_templates (id) ON DELETE CASCADE, 
	FOREIGN KEY(changed_by) REFERENCES users (id)
);

-- DashboardChartConfig (app.models.dashboard_chart_config)
CREATE TABLE dashboard_chart_configs (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	user_id INTEGER, 
	chart_type VARCHAR(50) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	x_axis VARCHAR(100), 
	y_axis VARCHAR(100), 
	data_source VARCHAR(100) NOT NULL, 
	filters JSON, 
	custom_metrics JSON, 
	is_active BOOLEAN NOT NULL, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

-- BenchmarkConfiguration (app.models.project.cost_benchmark)
CREATE TABLE benchmark_configurations (
	id INTEGER NOT NULL, 
	tenant_id INTEGER, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	industry_weight NUMERIC(3, 2), 
	test_type_weight NUMERIC(3, 2), 
	scale_weight NUMERIC(3, 2), 
	complexity_weight NUMERIC(3, 2), 
	customer_weight NUMERIC(3, 2), 
	high_threshold NUMERIC(5, 2), 
	medium_threshold NUMERIC(5, 2), 
	low_threshold NUMERIC(5, 2), 
	max_benchmarks INTEGER, 
	min_similarity NUMERIC(5, 2), 
	cost_variance_warning NUMERIC(5, 2), 
	cost_variance_alert NUMERIC(5, 2), 
	is_active BOOLEAN, 
	is_default BOOLEAN, 
	created_by INTEGER, 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);
