# -*- coding: utf-8 -*-
"""
Scheduler metadata describing all background jobs.

字段说明：
- dependencies_tables: 任务依赖的数据库表列表，用于评估表结构变更影响
- risk_level: 风险级别 (LOW/MEDIUM/HIGH/CRITICAL)，用于评估任务失败影响
- sla: 服务级别协议，包含 max_execution_time_seconds（最大执行时间，秒）和 retry_on_failure（失败是否重试）
"""

SCHEDULER_TASKS = [
    {
        "id": "calculate_project_health",
        "name": "计算项目健康度",
        "module": "app.utils.scheduled_tasks",
        "callable": "calculate_project_health",
        "cron": {"minute": 0},
        "owner": "Backend Platform",
        "category": "Project Health",
        "description": "每小时为所有活跃项目重新计算健康度并写入项目表。",
        "enabled": True,
        "dependencies_tables": ["projects", "project_milestones", "issues", "alert_records", "tasks"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "daily_health_snapshot",
        "name": "每日健康度快照",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_health_snapshot",
        "cron": {"hour": 2, "minute": 0},
        "owner": "Backend Platform",
        "category": "Project Health",
        "description": "凌晨 2 点为活跃项目生成健康度快照记录。",
        "enabled": True,
        "dependencies_tables": ["projects", "project_health_snapshots"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "daily_spec_match_check",
        "name": "每日规格匹配检查",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_spec_match_check",
        "cron": {"hour": 9, "minute": 0},
        "owner": "Quality Team",
        "category": "Spec Match",
        "description": "检查采购订单与 BOM 的规格匹配情况，生成差异记录。",
        "enabled": True,
        "dependencies_tables": ["purchase_orders", "bom_items", "materials"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 900,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_overdue_issues",
        "name": "问题逾期预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_overdue_issues",
        "cron": {"minute": 0},
        "owner": "Issue Squad",
        "category": "Issue Management",
        "description": "整点扫描逾期问题并生成预警。",
        "enabled": True,
        "dependencies_tables": ["issues", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 180,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_blocking_issues",
        "name": "阻塞问题预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_blocking_issues",
        "cron": {"minute": 5},
        "owner": "Issue Squad",
        "category": "Issue Management",
        "description": "在逾期检测后 5 分钟执行阻塞问题检查。",
        "enabled": True,
        "dependencies_tables": ["issues", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 180,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_timeout_issues",
        "name": "问题超时升级",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_timeout_issues",
        "cron": {"hour": 1, "minute": 0},
        "owner": "Issue Squad",
        "category": "Issue Management",
        "description": "凌晨 1 点执行问题超时升级策略。",
        "enabled": True,
        "dependencies_tables": ["issues", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "daily_issue_statistics_snapshot",
        "name": "每日问题统计快照",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_issue_statistics_snapshot",
        "cron": {"hour": 3, "minute": 0},
        "owner": "Issue Squad",
        "category": "Issue Management",
        "description": "生成问题统计快照供仪表盘使用。",
        "enabled": True,
        "dependencies_tables": ["issues", "alert_statistics"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_milestone_alerts",
        "name": "里程碑预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_milestone_alerts",
        "cron": {"hour": 8, "minute": 0},
        "owner": "PMO",
        "category": "Milestone",
        "description": "每天早上 8 点检测里程碑延期。",
        "enabled": True,
        "dependencies_tables": ["project_milestones", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_milestone_status_and_adjust_payments",
        "name": "里程碑状态监控与收款计划调整",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_milestone_status_and_adjust_payments",
        "cron": {"minute": 0},
        "owner": "Sales",
        "category": "Payment",
        "description": "Issue 7.3: 每小时检查里程碑状态变化，自动调整关联的收款计划。",
        "enabled": True,
        "dependencies_tables": ["project_milestones", "project_payment_plans", "notifications"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_cost_overrun_alerts",
        "name": "成本超支预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_cost_overrun_alerts",
        "cron": {"hour": 10, "minute": 0},
        "owner": "Finance",
        "category": "Cost",
        "description": "每天 10 点检查项目成本超支情况。",
        "enabled": True,
        "dependencies_tables": ["projects", "project_costs", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_workload_overload_alerts",
        "name": "负荷超限预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_workload_overload_alerts",
        "cron": {"hour": 11, "minute": 0},
        "owner": "PMO",
        "category": "Resource",
        "description": "每天 11 点检查工时与人员负荷是否超限。",
        "enabled": True,
        "dependencies_tables": ["users", "timesheets", "tasks", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "generate_shortage_alerts",
        "name": "缺料预警生成",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_shortage_alerts",
        "cron": {"hour": 7, "minute": 0},
        "owner": "Supply Chain",
        "category": "Shortage",
        "description": "每天 7 点生成缺料预警并更新 AlertRecord。",
        "enabled": True,
        "dependencies_tables": ["bom_items", "materials", "purchase_orders", "goods_receipts", "alert_records"],
        "risk_level": "CRITICAL",
        "sla": {
            "max_execution_time_seconds": 1200,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_task_delay_alerts",
        "name": "任务延期预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_task_delay_alerts",
        "cron": {"minute": 0},
        "owner": "PMO",
        "category": "Schedule",
        "description": "整点检查计划任务延期情况。",
        "enabled": True,
        "dependencies_tables": ["tasks", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 180,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_production_plan_alerts",
        "name": "生产计划预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_production_plan_alerts",
        "cron": {"hour": 11, "minute": 0},
        "owner": "Manufacturing",
        "category": "Production",
        "description": "每天 11 点评估生产计划执行偏差。",
        "enabled": True,
        "dependencies_tables": ["production_plans", "machines", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_work_report_timeout",
        "name": "报工超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_work_report_timeout",
        "cron": {"minute": 0},
        "owner": "Manufacturing",
        "category": "Production",
        "description": "整点提醒未按时提交报工的人员。",
        "enabled": True,
        "dependencies_tables": ["timesheets", "users"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 120,
            "retry_on_failure": False,
        },
    },
    {
        "id": "calculate_progress_summary",
        "name": "进度汇总计算",
        "module": "app.utils.scheduled_tasks",
        "callable": "calculate_progress_summary",
        "cron": {"minute": 0},
        "owner": "PMO",
        "category": "Schedule",
        "description": "整点计算项目/任务进度汇总数据。",
        "enabled": True,
        "dependencies_tables": ["projects", "tasks"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "daily_kit_check",
        "name": "每日齐套检查",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_kit_check",
        "cron": {"hour": 6, "minute": 0},
        "owner": "Supply Chain",
        "category": "Shortage",
        "description": "每天 6 点计算物料齐套情况。",
        "enabled": True,
        "dependencies_tables": ["bom_items", "materials", "purchase_orders", "goods_receipts"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 1200,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_delivery_delay",
        "name": "到货延迟检查",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_delivery_delay",
        "cron": {"hour": 14, "minute": 0},
        "owner": "Supply Chain",
        "category": "Procurement",
        "description": "下午 2 点扫描采购到货延迟。",
        "enabled": True,
        "dependencies_tables": ["purchase_orders", "goods_receipts", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_task_deadline_reminder",
        "name": "任务到期提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_task_deadline_reminder",
        "cron": {"minute": 0},
        "owner": "PMO",
        "category": "Schedule",
        "description": "整点提醒即将到期的任务负责人。",
        "enabled": True,
        "dependencies_tables": ["tasks", "users"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 120,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_outsourcing_delivery_alerts",
        "name": "外协交期预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_outsourcing_delivery_alerts",
        "cron": {"hour": 15, "minute": 0},
        "owner": "Supply Chain",
        "category": "Outsourcing",
        "description": "下午 3 点检查外协交期风险。",
        "enabled": True,
        "dependencies_tables": ["outsourcing_orders", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_milestone_risk_alerts",
        "name": "里程碑风险预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_milestone_risk_alerts",
        "cron": {"hour": 8, "minute": 10},
        "owner": "PMO",
        "category": "Milestone",
        "description": "里程碑风险版预警，比对多维指标。",
        "enabled": True,
        "dependencies_tables": ["project_milestones", "projects", "tasks", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "generate_production_daily_reports",
        "name": "生产日报自动生成",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_production_daily_reports",
        "cron": {"hour": 5, "minute": 0},
        "owner": "Manufacturing",
        "category": "Production",
        "description": "凌晨 5 点自动生成生产日报数据。",
        "enabled": True,
        "dependencies_tables": ["production_plans", "machines", "timesheets"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 900,
            "retry_on_failure": False,
        },
    },
    {
        "id": "generate_shortage_daily_report",
        "name": "缺料日报自动生成",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_shortage_daily_report",
        "cron": {"hour": 5, "minute": 15},
        "owner": "Supply Chain",
        "category": "Shortage",
        "description": "5:15 生成缺料日报供前端查询。",
        "enabled": True,
        "dependencies_tables": ["bom_items", "materials", "purchase_orders", "goods_receipts"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 1200,
            "retry_on_failure": False,
        },
    },
    {
        "id": "generate_job_duty_tasks",
        "name": "岗位职责任务生成",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_job_duty_tasks",
        "cron": {"hour": 4, "minute": 0},
        "owner": "PMO",
        "category": "Workspace",
        "description": "凌晨 4 点生成岗位职责相关任务。",
        "enabled": True,
        "dependencies_tables": ["job_duties", "tasks", "users"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_ecn_overdue",
        "name": "ECN 超时检查",
        "module": "app.services.ecn_scheduler",
        "callable": "run_ecn_scheduler",
        "cron": {"hour": 9, "minute": 0},
        "owner": "ECN Team",
        "category": "Change Management",
        "description": "每天 9 点扫描 ECN 超时事项。",
        "enabled": True,
        "dependencies_tables": ["ecns", "ecn_tasks", "ecn_approvals"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_payment_reminder",
        "name": "收款提醒服务",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_payment_reminder",
        "cron": {"hour": 9, "minute": 30},
        "owner": "Finance",
        "category": "Finance",
        "description": "9:30 发送即将收款的提醒。",
        "enabled": True,
        "dependencies_tables": ["project_payment_plans", "projects"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_overdue_receivable_alerts",
        "name": "逾期应收预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_overdue_receivable_alerts",
        "cron": {"hour": 10, "minute": 30},
        "owner": "Finance",
        "category": "Finance",
        "description": "10:30 检查逾期应收账款。",
        "enabled": True,
        "dependencies_tables": ["project_payment_plans", "projects", "alert_records"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_alert_escalation",
        "name": "预警升级服务",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_alert_escalation",
        "cron": {"minute": 10},
        "owner": "PMO",
        "category": "Alerting",
        "description": "每小时 +10 分处理预警升级逻辑。",
        "enabled": True,
        "dependencies_tables": ["alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 180,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_opportunity_stage_timeout",
        "name": "商机阶段超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_opportunity_stage_timeout",
        "cron": {"hour": 15, "minute": 30},
        "owner": "Sales",
        "category": "Sales",
        "description": "15:30 提醒超时的商机阶段。",
        "enabled": True,
        "dependencies_tables": ["opportunities", "opportunity_stages"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_presale_workorder_timeout",
        "name": "售前工单超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_presale_workorder_timeout",
        "cron": {"hour": 16, "minute": 0},
        "owner": "Presales",
        "category": "Sales",
        "description": "16:00 扫描售前工单超时情况。",
        "enabled": True,
        "dependencies_tables": ["presale_workorders"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_issue_timeout_escalation",
        "name": "问题超时升级服务",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_issue_timeout_escalation",
        "cron": {"hour": 1, "minute": 30},
        "owner": "Issue Squad",
        "category": "Issue Management",
        "description": "凌晨 1:30 针对问题执行二次升级。",
        "enabled": True,
        "dependencies_tables": ["issues", "alert_records"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_equipment_maintenance_reminder",
        "name": "设备保养提醒服务",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_equipment_maintenance_reminder",
        "cron": {"hour": 8, "minute": 30},
        "owner": "Manufacturing",
        "category": "Equipment",
        "description": "8:30 提醒设备保养计划。",
        "enabled": True,
        "dependencies_tables": ["machines", "equipment_maintenance_plans"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "calculate_response_metrics",
        "name": "计算响应时效指标",
        "module": "app.utils.scheduled_tasks",
        "callable": "calculate_response_metrics",
        "cron": {"hour": 1, "minute": 0},
        "owner": "Backend Platform",
        "category": "Alert Statistics",
        "description": "每天凌晨1点计算预警响应时效指标并更新统计表。",
        "enabled": True,
        "dependencies_tables": ["alert_records", "alert_statistics"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "send_alert_notifications",
        "name": "消息推送服务",
        "module": "app.utils.scheduled_tasks",
        "callable": "send_alert_notifications",
        "cron": {"minute": 15},
        "owner": "PMO",
        "category": "Alerting",
        "description": "每小时 +15 分推送汇总消息（短信/企微等）。",
        "enabled": True,
        "dependencies_tables": ["alert_records", "users"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "retry_failed_notifications",
        "name": "通知重试机制",
        "module": "app.utils.scheduled_tasks",
        "callable": "retry_failed_notifications",
        "cron": {"minute": 30},
        "owner": "PMO",
        "category": "Alerting",
        "description": "每小时 +30 分重试发送失败的通知。",
        "enabled": True,
        "dependencies_tables": ["alert_notifications", "alert_records", "users"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "calculate_monthly_labor_cost",
        "name": "月度工时成本计算",
        "module": "app.utils.scheduled_tasks",
        "callable": "calculate_monthly_labor_cost_task",
        "cron": {"day": 1, "hour": 2, "minute": 0},
        "owner": "Finance",
        "category": "Cost",
        "description": "每月1号凌晨2点自动计算上个月所有项目的人工成本。",
        "enabled": True,
        "dependencies_tables": ["timesheets", "projects", "project_costs"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 1800,
            "retry_on_failure": False,
        },
    },
    {
        "id": "sales_reminder_scan",
        "name": "销售提醒扫描",
        "module": "app.utils.scheduled_tasks",
        "callable": "sales_reminder_scan",
        "cron": {"hour": 9, "minute": 0},
        "owner": "Sales",
        "category": "Sales",
        "description": "每天9点扫描销售里程碑、收款计划等需要提醒的事项并发送通知。",
        "enabled": True,
        "dependencies_tables": ["opportunities", "project_payment_plans", "projects"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": False,
        },
    },
    {
        "id": "check_contract_expiry_reminder",
        "name": "合同到期提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_contract_expiry_reminder",
        "cron": {"hour": 9, "minute": 0},
        "owner": "HR",
        "category": "HR Management",
        "description": "每天9点扫描即将到期的员工合同（提前60天、30天、14天提醒），并生成提醒记录。",
        "enabled": True,
        "dependencies_tables": ["employee_contracts", "contract_reminders", "employees"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "check_employee_confirmation_reminder",
        "name": "员工转正提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "check_employee_confirmation_reminder",
        "cron": {"hour": 9, "minute": 15},
        "owner": "HR",
        "category": "HR Management",
        "description": "每天9:15扫描即将到期的试用期员工（提前7天提醒），生成转正提醒。",
        "enabled": True,
        "dependencies_tables": ["employees", "employee_hr_profiles", "hr_transactions"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": True,
        },
    },
    {
        "id": "daily_timesheet_aggregation",
        "name": "每日工时汇总",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_timesheet_aggregation_task",
        "cron": {"hour": 1, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天凌晨1点汇总前一天的工时数据",
        "enabled": True,
        "dependencies_tables": ["timesheet", "timesheet_summary"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "weekly_timesheet_aggregation",
        "name": "每周工时汇总",
        "module": "app.utils.scheduled_tasks",
        "callable": "weekly_timesheet_aggregation_task",
        "cron": {"day_of_week": "mon", "hour": 2, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每周一凌晨2点汇总上一周的工时数据",
        "enabled": True,
        "dependencies_tables": ["timesheet", "timesheet_summary"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "monthly_timesheet_aggregation",
        "name": "每月工时汇总",
        "module": "app.utils.scheduled_tasks",
        "callable": "monthly_timesheet_aggregation_task",
        "cron": {"day": 1, "hour": 3, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每月1号凌晨3点汇总上个月的工时数据",
        "enabled": True,
        "dependencies_tables": ["timesheet", "timesheet_summary"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 1800,
            "retry_on_failure": True,
        },
    },
    {
        "id": "generate_monthly_reports",
        "name": "生成月度报表",
        "module": "app.utils.scheduled_tasks",
        "callable": "generate_monthly_reports_task",
        "cron": {"day": 1, "hour": 4, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每月1号凌晨4点生成上个月的各类报表并同步到各系统",
        "enabled": True,
        "dependencies_tables": ["timesheet", "financial_project_costs", "rd_cost", "project_cost"],
        "risk_level": "HIGH",
        "sla": {
            "max_execution_time_seconds": 3600,
            "retry_on_failure": True,
        },
    },
    {
        "id": "daily_timesheet_reminder",
        "name": "每日工时填报提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "daily_timesheet_reminder_task",
        "cron": {"hour": 9, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天上午9点提醒未填报昨天工时的用户",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "user_roles", "roles", "departments"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "weekly_timesheet_reminder",
        "name": "每周工时填报提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "weekly_timesheet_reminder_task",
        "cron": {"day_of_week": "mon", "hour": 10, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每周一上午10点提醒未完成上周工时填报的用户",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "user_roles", "roles", "departments"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "timesheet_anomaly_alert",
        "name": "异常工时预警",
        "module": "app.utils.scheduled_tasks",
        "callable": "timesheet_anomaly_alert_task",
        "cron": {"hour": 14, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天下午2点检测并提醒异常工时记录",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications"],
        "risk_level": "LOW",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "timesheet_approval_timeout_reminder",
        "name": "工时审批超时提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "timesheet_approval_timeout_reminder_task",
        "cron": {"hour": 11, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天上午11点和下午3点提醒审批超时的记录",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "departments", "projects"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
    {
        "id": "timesheet_sync_failure_alert",
        "name": "工时数据同步失败提醒",
        "module": "app.utils.scheduled_tasks",
        "callable": "timesheet_sync_failure_alert_task",
        "cron": {"hour": 16, "minute": 0},
        "owner": "Backend Platform",
        "category": "Timesheet Management",
        "description": "每天下午4点检查并提醒同步失败的记录",
        "enabled": True,
        "dependencies_tables": ["timesheet", "users", "notifications", "financial_project_costs", "rd_costs", "project_costs"],
        "risk_level": "MEDIUM",
        "sla": {
            "max_execution_time_seconds": 300,
            "retry_on_failure": False,
        },
    },
]
