import api from "./api/client.js";

export default api;
export { api };

export * from "./api/acceptance.js";
export * from "./api/admin.js";
export * from "./api/alerts.js";
export * from "./api/auth.js";
export * from "./api/businessSupport.js";
export * from "./api/customerCommunication.js";
export * from "./api/crm.js";
export * from "./api/budget.js";
export * from "./api/ecn.js";
export * from "./api/engineering.js";
export * from "./api/finance.js";
export * from "./api/hr.js";
export * from "./api/issues.js";
export * from "./api/org.js";
export * from "./api/pmo.js";
export * from "./api/presales.js";
export * from "./api/procurement.js";
export * from "./api/production.js";
export * from "./api/progress.js";
export * from "./api/projectRoles.js";
export * from "./api/projects.js";
export * from "./api/sales.js";
export * from "./api/service.js";
export * from "./api/taskCenter.js";
export * from "./api/workload.js";
