# -*- coding: utf-8 -*/
"""
交付和结项阶段定义 (S7-S9)

包含：
- S7: 包装发运
- S8: 现场安装
- S9: 质保结项
"""

from typing import Any, Dict, List

# 交付和结项阶段 (S7-S9)
DELIVERY_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S7",
            "stage_name": "包装发运",
            "sequence": 6,
            "estimated_days": 3,
            "description": "设备包装和发货",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S7N01",
                    "node_name": "设备包装",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "设备包装入箱",
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["装箱单"],
                },
                {
                    "node_code": "S7N02",
                    "node_name": "发货安排",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "安排物流发货",
                    "dependency_node_codes": ["S7N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["发货单", "物流单号"],
                },
                {
                    "node_code": "S7N03",
                    "node_name": "发货确认",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "确认发货到达",
                    "dependency_node_codes": ["S7N02"],
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["签收单"],
                },
            ]
        },
        {
            "stage_code": "S8",
            "stage_name": "现场安装",
            "sequence": 7,
            "estimated_days": 7,
            "description": "现场安装调试和SAT验收",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S8N01",
                    "node_name": "现场安装",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "现场设备安装",
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["安装完成确认"],
                },
                {
                    "node_code": "S8N02",
                    "node_name": "现场调试",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "现场设备调试",
                    "dependency_node_codes": ["S8N01"],
                    "owner_role_code": "SW",
                    "participant_role_codes": ["ME", "EE"],
                    "deliverables": ["现场调试记录"],
                },
                {
                    "node_code": "S8N03",
                    "node_name": "客户SAT验收",
                    "node_type": "APPROVAL",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "客户现场验收",
                    "dependency_node_codes": ["S8N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA", "SALES"],
                    "deliverables": ["SAT验收记录"],
                },
                {
                    "node_code": "S8N04",
                    "node_name": "SAT报告签署",
                    "node_type": "DELIVERABLE",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "SAT验收报告签署",
                    "dependency_node_codes": ["S8N03"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["SAT验收报告"],
                },
            ]
        },
        {
            "stage_code": "S9",
            "stage_name": "质保结项",
            "sequence": 8,
            "estimated_days": 7,
            "description": "项目收尾和质保交接",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S9N01",
                    "node_name": "项目文档归档",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 2,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "整理归档项目文档",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["项目文档包", "技术资料"],
                },
                {
                    "node_code": "S9N02",
                    "node_name": "客户培训",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "客户操作培训",
                    "owner_role_code": "SW",
                    "participant_role_codes": ["ME", "EE"],
                    "deliverables": ["培训记录", "操作手册"],
                },
                {
                    "node_code": "S9N03",
                    "node_name": "质保交接",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "移交售后质保服务",
                    "dependency_node_codes": ["S9N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["质保交接单"],
                },
                {
                    "node_code": "S9N04",
                    "node_name": "项目结项审批",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "项目结项审批确认",
                    "dependency_node_codes": ["S9N03"],
                    "owner_role_code": "GM",
                    "participant_role_codes": ["CTO", "CFO"],
                    "deliverables": ["结项审批单"],
                },
                {
                    "node_code": "S9N05",
                    "node_name": "经验总结",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "项目经验总结归档",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["经验总结报告"],
                },
            ]
        },
]
