# -*- coding: utf-8 -*/
"""
规划和设计阶段定义 (S1-S3)

包含：
- S1: 需求进入
- S2: 方案设计
- S3: 采购备料
"""

from typing import Any, Dict, List

# 规划和设计阶段 (S1-S3)
PLANNING_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S1",
            "stage_name": "需求进入",
            "sequence": 0,
            "estimated_days": 7,
            "description": "接收客户需求，评估可行性",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S1N01",
                    "node_name": "需求接收登记",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "登记客户需求基本信息",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["PM"],
                    "deliverables": ["需求登记表"],
                },
                {
                    "node_code": "S1N02",
                    "node_name": "技术可行性评估",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "评估技术实现可行性",
                    "owner_role_code": "CTO",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["可行性评估报告"],
                },
                {
                    "node_code": "S1N03",
                    "node_name": "商务报价",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "编制项目报价",
                    "owner_role_code": "SALES",
                    "participant_role_codes": ["FINANCE"],
                    "deliverables": ["报价单"],
                },
                {
                    "node_code": "S1N04",
                    "node_name": "合同签订确认",
                    "node_type": "APPROVAL",
                    "sequence": 3,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "确认合同签订",
                    "dependency_node_codes": ["S1N03"],
                    "owner_role_code": "GM",
                    "participant_role_codes": ["SALES_DIR", "SALES"],
                    "deliverables": ["签订合同"],
                },
            ]
        },
        {
            "stage_code": "S2",
            "stage_name": "方案设计",
            "sequence": 1,
            "estimated_days": 14,
            "description": "完成整体方案设计与技术评审",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S2N01",
                    "node_name": "需求澄清会议",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "与客户确认详细需求",
                    "owner_role_code": "PM",
                    "participant_role_codes": ["ME", "EE", "SW", "SALES"],
                    "deliverables": ["会议纪要", "需求确认书"],
                },
                {
                    "node_code": "S2N02",
                    "node_name": "整体方案设计",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "编制整体技术方案",
                    "dependency_node_codes": ["S2N01"],
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE", "SW"],
                    "deliverables": ["技术方案书"],
                },
                {
                    "node_code": "S2N03",
                    "node_name": "机械结构设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "完成机械结构设计图纸",
                    "dependency_node_codes": ["S2N02"],
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["3D模型", "2D装配图", "零件图"],
                },
                {
                    "node_code": "S2N04",
                    "node_name": "电气设计",
                    "node_type": "DELIVERABLE",
                    "sequence": 3,
                    "estimated_days": 5,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "完成电气原理图和接线图",
                    "dependency_node_codes": ["S2N02"],
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["电气原理图", "接线图", "元器件清单"],
                },
                {
                    "node_code": "S2N05",
                    "node_name": "技术评审",
                    "node_type": "APPROVAL",
                    "sequence": 4,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "技术方案评审通过",
                    "dependency_node_codes": ["S2N03", "S2N04"],
                    "owner_role_code": "CTO",
                    "participant_role_codes": ["ME", "EE", "SW", "QA"],
                    "deliverables": ["评审记录"],
                },
            ]
        },
        {
            "stage_code": "S3",
            "stage_name": "采购备料",
            "sequence": 2,
            "estimated_days": 21,
            "description": "BOM确认和物料采购",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S3N01",
                    "node_name": "BOM编制",
                    "node_type": "DELIVERABLE",
                    "sequence": 0,
                    "estimated_days": 3,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "编制物料清单",
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["BOM清单"],
                },
                {
                    "node_code": "S3N02",
                    "node_name": "BOM评审",
                    "node_type": "APPROVAL",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "物料清单评审确认",
                    "dependency_node_codes": ["S3N01"],
                    "owner_role_code": "CTO",
                    "participant_role_codes": ["PU_MGR", "PMC"],
                    "deliverables": ["BOM评审记录"],
                },
                {
                    "node_code": "S3N03",
                    "node_name": "采购申请",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "提交采购申请",
                    "dependency_node_codes": ["S3N02"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": ["PU_MGR"],
                    "deliverables": ["采购申请单"],
                },
                {
                    "node_code": "S3N04",
                    "node_name": "供应商选择",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "选择供应商并下单",
                    "dependency_node_codes": ["S3N03"],
                    "owner_role_code": "PU_MGR",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["采购订单"],
                },
                {
                    "node_code": "S3N05",
                    "node_name": "物料到货验收",
                    "node_type": "TASK",
                    "sequence": 4,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "物料到货并完成验收",
                    "dependency_node_codes": ["S3N04"],
                    "owner_role_code": "QA",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["入库单", "检验报告"],
                },
            ]
        },
]
