# -*- coding: utf-8 -*/
"""
生产和验收阶段定义 (S4-S6)

包含：
- S4: 加工制造
- S5: 装配调试
- S6: 出厂验收
"""

from typing import Any, Dict, List

# 生产和验收阶段 (S4-S6)
PRODUCTION_STAGES: List[Dict[str, Any]] = [
        {
            "stage_code": "S4",
            "stage_name": "加工制造",
            "sequence": 3,
            "estimated_days": 21,
            "description": "机械加工和外协管理",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S4N01",
                    "node_name": "加工图纸发放",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "发放加工图纸给车间/外协",
                    "owner_role_code": "ME",
                    "participant_role_codes": ["PMC"],
                    "deliverables": ["加工图纸"],
                },
                {
                    "node_code": "S4N02",
                    "node_name": "自制件加工",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 10,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "内部加工自制零件",
                    "dependency_node_codes": ["S4N01"],
                    "owner_role_code": "PMC",
                    "participant_role_codes": [],
                    "deliverables": ["加工完成零件"],
                },
                {
                    "node_code": "S4N03",
                    "node_name": "外协件加工",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 14,
                    "completion_method": "MANUAL",
                    "is_required": False,
                    "description": "外协加工零件",
                    "dependency_node_codes": ["S4N01"],
                    "owner_role_code": "PU_MGR",
                    "participant_role_codes": ["PU_ASSISTANT"],
                    "deliverables": ["外协加工零件"],
                },
                {
                    "node_code": "S4N04",
                    "node_name": "零件检验入库",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "零件检验合格入库",
                    "dependency_node_codes": ["S4N02"],
                    "owner_role_code": "QA",
                    "participant_role_codes": [],
                    "deliverables": ["检验报告", "入库单"],
                },
            ]
        },
        {
            "stage_code": "S5",
            "stage_name": "装配调试",
            "sequence": 4,
            "estimated_days": 14,
            "description": "设备装配和调试验证",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S5N01",
                    "node_name": "机械装配",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 5,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "完成机械部分装配",
                    "owner_role_code": "ME",
                    "participant_role_codes": [],
                    "deliverables": ["装配完成确认"],
                },
                {
                    "node_code": "S5N02",
                    "node_name": "电气接线",
                    "node_type": "TASK",
                    "sequence": 1,
                    "estimated_days": 3,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "完成电气接线安装",
                    "dependency_node_codes": ["S5N01"],
                    "owner_role_code": "EE",
                    "participant_role_codes": [],
                    "deliverables": ["接线完成确认"],
                },
                {
                    "node_code": "S5N03",
                    "node_name": "程序调试",
                    "node_type": "TASK",
                    "sequence": 2,
                    "estimated_days": 4,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "软件程序调试",
                    "dependency_node_codes": ["S5N02"],
                    "owner_role_code": "SW",
                    "participant_role_codes": ["EE"],
                    "deliverables": ["调试记录"],
                },
                {
                    "node_code": "S5N04",
                    "node_name": "联调测试",
                    "node_type": "TASK",
                    "sequence": 3,
                    "estimated_days": 2,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "整机联调测试",
                    "dependency_node_codes": ["S5N03"],
                    "owner_role_code": "ME",
                    "participant_role_codes": ["EE", "SW", "QA"],
                    "deliverables": ["联调测试报告"],
                },
            ]
        },
        {
            "stage_code": "S6",
            "stage_name": "出厂验收",
            "sequence": 5,
            "estimated_days": 3,
            "description": "FAT出厂验收测试",
            "is_required": True,
            "nodes": [
                {
                    "node_code": "S6N01",
                    "node_name": "内部预验收",
                    "node_type": "TASK",
                    "sequence": 0,
                    "estimated_days": 1,
                    "completion_method": "MANUAL",
                    "is_required": True,
                    "description": "内部预验收检查",
                    "owner_role_code": "QA",
                    "participant_role_codes": ["ME", "EE", "SW"],
                    "deliverables": ["预验收检查表"],
                },
                {
                    "node_code": "S6N02",
                    "node_name": "客户FAT验收",
                    "node_type": "APPROVAL",
                    "sequence": 1,
                    "estimated_days": 1,
                    "completion_method": "APPROVAL",
                    "is_required": True,
                    "description": "客户出厂验收",
                    "dependency_node_codes": ["S6N01"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA", "SALES"],
                    "deliverables": ["FAT验收记录"],
                },
                {
                    "node_code": "S6N03",
                    "node_name": "FAT报告签署",
                    "node_type": "DELIVERABLE",
                    "sequence": 2,
                    "estimated_days": 1,
                    "completion_method": "UPLOAD",
                    "is_required": True,
                    "required_attachments": True,
                    "description": "FAT验收报告签署",
                    "dependency_node_codes": ["S6N02"],
                    "owner_role_code": "PM",
                    "participant_role_codes": ["QA"],
                    "deliverables": ["FAT验收报告"],
                },
            ]
        },
]
