# -*- coding: utf-8 -*-
"""
销售管理 Schema 模块
"""

from .ai_clarifications import (
    AIClarificationCreate,
    AIClarificationResponse,
    AIClarificationUpdate,
)
from .requirement_details import (
    LeadRequirementDetailCreate,
    LeadRequirementDetailResponse,
    LeadRequirementDetailUpdate,
)
from .requirement_freezes import (
    RequirementFreezeCreate,
    RequirementFreezeResponse,
    RequirementFreezeUpdate,
)
from .assessments import (
    FailureCaseCreate,
    FailureCaseResponse,
    OpenItemCreate,
    OpenItemResponse,
    ScoringRuleCreate,
    ScoringRuleResponse,
    TechnicalAssessmentApplyRequest,
    TechnicalAssessmentEvaluateRequest,
    TechnicalAssessmentResponse,
)
from .contracts import (
    ApprovalActionRequest,
    ApprovalHistoryResponse,
    ApprovalRecordResponse,
    ApprovalStartRequest,
    ApprovalStatusResponse,
    ContractAmendmentCreate,
    ContractAmendmentResponse,
    ContractCreate,
    ContractDeliverableCreate,
    ContractDeliverableResponse,
    ContractProjectCreateRequest,
    ContractResponse,
    ContractSignRequest,
    ContractUpdate,
)
from .cost_templates import (
    CostMatchSuggestion,
    MaterialCostMatchRequest,
    MaterialCostMatchResponse,
    MaterialCostUpdateReminderResponse,
    MaterialCostUpdateReminderUpdate,
    PurchaseMaterialCostCreate,
    PurchaseMaterialCostResponse,
    PurchaseMaterialCostUpdate,
    QuoteCostTemplateCreate,
    QuoteCostTemplateResponse,
    QuoteCostTemplateUpdate,
)
from .invoices import (
    InvoiceApprovalCreate,
    InvoiceApprovalResponse,
    InvoiceCreate,
    InvoiceIssueRequest,
    InvoiceResponse,
    InvoiceUpdate,
    ReceivableDisputeCreate,
    ReceivableDisputeResponse,
)
from .leads import (
    LeadCreate,
    LeadFollowUpCreate,
    LeadFollowUpResponse,
    LeadResponse,
    LeadUpdate,
)
from .workflow import (
    ApprovalWorkflowCreate,
    ApprovalWorkflowResponse,
    ApprovalWorkflowStepResponse,
    ApprovalWorkflowUpdate,
    RankingMetric,
    SalesRankingConfigResponse,
    SalesRankingConfigUpdateRequest,
    SalesTargetCreate,
    SalesTargetResponse,
    SalesTargetUpdate,
)
from .opportunities import (
    OpportunityCreate,
    OpportunityRequirementCreate,
    OpportunityRequirementResponse,
    OpportunityResponse,
    OpportunityUpdate,
)
from .quotes import (
    GateSubmitRequest,
    QuoteApproveRequest,
    QuoteCreate,
    QuoteItemBatchUpdate,
    QuoteItemCreate,
    QuoteItemResponse,
    QuoteItemUpdate,
    QuoteResponse,
    QuoteUpdate,
    QuoteVersionCreate,
    QuoteVersionResponse,
)
from .team import (
    SalesTeamCreate,
    SalesTeamUpdate,
    SalesTeamResponse,
    SalesTeamListResponse,
    SalesTeamMemberInfo,
    TeamMemberAddRequest,
    TeamMemberUpdateRequest,
    TeamMemberBatchAddRequest,
    TeamPerformanceSnapshotResponse,
    TeamPKCreateRequest,
    TeamPKUpdateRequest,
    TeamPKResponse,
    TeamRankingItem,
    TeamRankingResponse,
)
from .contract_templates import (
    ContractTemplateCreate,
    ContractTemplateUpdate,
    ContractTemplateResponse,
    ContractTemplateVersionCreate,
    ContractTemplateVersionResponse,
    ContractTemplateApplyRequest,
    ContractTemplateApplyResponse,
    ContractTemplateVersionDiffResponse,
    ContractTemplateHistoryResponse,
    VersionDiffItem,
    VersionHistoryItem,
)
from .quote_templates import (
    CpqRuleSetCreate,
    CpqRuleSetUpdate,
    CpqRuleSetResponse,
    CpqPricePreviewRequest,
    CpqPricePreviewResponse,
    QuoteTemplateCreate,
    QuoteTemplateUpdate,
    QuoteTemplateResponse,
    QuoteTemplateVersionCreate,
    QuoteTemplateVersionResponse,
    QuoteTemplateApplyRequest,
    QuoteTemplateApplyResponse,
    TemplateVersionDiff,
    TemplateApprovalHistoryRecord,
)

__all__ = [
    # AI澄清相关
    "AIClarificationCreate",
    "AIClarificationUpdate",
    "AIClarificationResponse",
    # 需求明细相关
    "LeadRequirementDetailCreate",
    "LeadRequirementDetailUpdate",
    "LeadRequirementDetailResponse",
    # 需求冻结相关
    "RequirementFreezeCreate",
    "RequirementFreezeUpdate",
    "RequirementFreezeResponse",
    # 线索相关
    "LeadCreate",
    "LeadUpdate",
    "LeadResponse",
    "LeadFollowUpCreate",
    "LeadFollowUpResponse",
    # 机会相关
    "OpportunityCreate",
    "OpportunityUpdate",
    "OpportunityResponse",
    "OpportunityRequirementCreate",
    "OpportunityRequirementResponse",
    # 报价相关
    "QuoteCreate",
    "QuoteUpdate",
    "QuoteResponse",
    "QuoteItemCreate",
    "QuoteItemUpdate",
    "QuoteItemResponse",
    "QuoteItemBatchUpdate",
    "QuoteVersionCreate",
    "QuoteVersionResponse",
    "GateSubmitRequest",
    "QuoteApproveRequest",
    # 合同相关
    "ContractCreate",
    "ContractUpdate",
    "ContractResponse",
    "ContractDeliverableCreate",
    "ContractDeliverableResponse",
    "ContractAmendmentCreate",
    "ContractAmendmentResponse",
    "ContractSignRequest",
    "ContractProjectCreateRequest",
    # 审批工作流相关
    "ApprovalStartRequest",
    "ApprovalActionRequest",
    "ApprovalStatusResponse",
    "ApprovalRecordResponse",
    "ApprovalHistoryResponse",
    # 成本模板相关
    "QuoteCostTemplateCreate",
    "QuoteCostTemplateUpdate",
    "QuoteCostTemplateResponse",
    "PurchaseMaterialCostCreate",
    "PurchaseMaterialCostUpdate",
    "PurchaseMaterialCostResponse",
    "MaterialCostMatchRequest",
    "MaterialCostMatchResponse",
    "MaterialCostUpdateReminderResponse",
    "MaterialCostUpdateReminderUpdate",
    "CostMatchSuggestion",
    # 发票相关
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceIssueRequest",
    "InvoiceApprovalCreate",
    "InvoiceApprovalResponse",
    # 回款争议相关
    "ReceivableDisputeCreate",
    "ReceivableDisputeResponse",
    # 销售目标相关
    "SalesTargetCreate",
    "SalesTargetUpdate",
    "SalesTargetResponse",
    # 销售排名配置相关
    "RankingMetric",
    "SalesRankingConfigUpdateRequest",
    "SalesRankingConfigResponse",
    # 审批工作流相关
    "ApprovalWorkflowCreate",
    "ApprovalWorkflowUpdate",
    "ApprovalWorkflowResponse",
    "ApprovalWorkflowStepResponse",
    # 技术评估相关
    "TechnicalAssessmentApplyRequest",
    "TechnicalAssessmentEvaluateRequest",
    "TechnicalAssessmentResponse",
    "ScoringRuleCreate",
    "ScoringRuleResponse",
    "FailureCaseCreate",
    "FailureCaseResponse",
    "OpenItemCreate",
    "OpenItemResponse",
    # 团队管理相关
    "SalesTeamCreate",
    "SalesTeamUpdate",
    "SalesTeamResponse",
    "SalesTeamListResponse",
    "SalesTeamMemberInfo",
    "TeamMemberAddRequest",
    "TeamMemberUpdateRequest",
    "TeamMemberBatchAddRequest",
    "TeamPerformanceSnapshotResponse",
    "TeamPKCreateRequest",
    "TeamPKUpdateRequest",
    "TeamPKResponse",
    "TeamRankingItem",
    "TeamRankingResponse",
    # 合同模板相关
    "ContractTemplateCreate",
    "ContractTemplateUpdate",
    "ContractTemplateResponse",
    "ContractTemplateVersionCreate",
    "ContractTemplateVersionResponse",
    "ContractTemplateApplyRequest",
    "ContractTemplateApplyResponse",
    "ContractTemplateVersionDiffResponse",
    "ContractTemplateHistoryResponse",
    "VersionDiffItem",
    "VersionHistoryItem",
    # 报价模板相关
    "QuoteTemplateCreate",
    "QuoteTemplateUpdate",
    "QuoteTemplateResponse",
    "QuoteTemplateVersionCreate",
    "QuoteTemplateVersionResponse",
    "QuoteTemplateApplyRequest",
    "QuoteTemplateApplyResponse",
    # CPQ规则集相关
    "CpqRuleSetCreate",
    "CpqRuleSetUpdate",
    "CpqRuleSetResponse",
    "CpqPricePreviewRequest",
    "CpqPricePreviewResponse",
    # 模板通用
    "TemplateVersionDiff",
    "TemplateApprovalHistoryRecord",
]
