/**
 * Service Constants - 统一入口
 * 拆分自原 service.js，保持向后兼容
 */

// ==================== 客户服务模块 ====================
export {
  // 基础配置
  SERVICE_TYPES,
  TICKET_STATUS,
  PRIORITY_LEVELS,
  SATISFACTION_LEVELS,
  SERVICE_PHASES,
  RESPONSE_CHANNELS,
  RESOLUTION_METHODS,
  WARRANTY_TYPES,
  PERFORMANCE_METRICS,
  ESCALATION_LEVELS,
  TABLE_CONFIG,
  CHART_COLORS,
  DEFAULT_FILTERS,
  // 仪表盘 Tailwind 风格配置
  customerStatusConfigs,
  servicePriorityConfigs,
  serviceTypeConfigs,
  satisfactionLevelConfigs,
  serviceChannelConfigs,
  serviceStatusConfigs,
  serviceMetricConfigs,
  customerServiceTabConfigs,
  // 统计与格式化函数
  calculateServiceStats,
  formatCustomerStatus,
  formatServicePriority,
  formatServiceType,
  formatSatisfactionLevel,
  formatServiceChannel,
  formatServiceStatus,
  // 筛选函数
  filterTicketsByStatus,
  filterTicketsByPriority,
  filterTicketsByType,
  filterTicketsByCustomer,
  // 排序函数
  sortByPriority,
  sortByCreateTime,
  sortByResolutionTime,
  // 默认导出对象
  SERVICE_DEFAULT,
} from './customerService.js';

// ==================== 服务工单模块 ====================
export {
  statusConfigs,
  urgencyConfigs,
  problemTypeConfigs,
  sortOptions,
  filterOptions,
  batchOperations,
  defaultTicketForm,
  defaultAssignForm,
  defaultCloseForm,
  statusTransitions,
  getStatusLabel,
  getStatusColor,
  getUrgencyLabel,
  getUrgencyColor,
  getProblemTypeIcon,
  getProblemTypeColor,
  getProblemTypesByCategory,
  canTransition,
  getNextStatuses,
  urgencyWeights,
  calculateTicketStats,
  // 兼容导出（中文键名）
  statusConfig,
  urgencyConfig,
  problemTypeConfig,
  legacyFilterOptions,
  defaultFormData,
  defaultCloseData,
  backendToFrontendStatus,
  frontendToBackendStatus,
  backendToFrontendUrgency,
  frontendToBackendUrgency,
  mapBackendStatus,
  mapBackendUrgency,
  mapFrontendStatus,
  mapFrontendUrgency,
  statusOrderWeight,
  urgencyOrderWeight,
  keyboardShortcuts,
  getStatusBadge,
  getUrgencyBadge,
  getProblemTypeBadge,
  SERVICE_TICKET_DEFAULT,
} from './tickets.js';

// ==================== 配送管理模块 ====================
export {
  deliveryStatusConfigs,
  deliveryPriorityConfigs,
  deliveryMethodConfigs,
  deliveryTypeConfigs,
  deliveryStageConfigs,
  vehicleStatusConfigs,
  driverStatusConfigs,
  exceptionTypeConfigs,
  statsTypeConfigs,
  exportTypeConfigs,
  timeSlotConfigs,
  tabConfigs,
  getStatusConfig,
  getPriorityConfig,
  getMethodConfig,
  getTypeConfig,
  getStageConfig,
  getVehicleStatusConfig,
  getDriverStatusConfig,
  getExceptionConfig,
  getStatsConfig,
  getTimeSlotConfig,
  formatStatus,
  formatPriority,
  formatMethod,
  formatType,
  formatStage,
  getPriorityValue,
  sortByDeliveryPriority,
  sortByStatus,
  sortByDeliveryTime,
  isValidStatus,
  isValidPriority,
  isValidMethod,
  isValidType,
  isValidStage,
  filterByStatus,
  filterByPriority,
  filterByMethod,
  filterByType,
  filterByDate,
  // 兼容导出
  DELIVERY_STATUS,
  DELIVERY_PRIORITY,
  SHIPPING_METHODS,
  PACKAGE_TYPES,
  DELIVERY_DEFAULT,
} from './delivery.js';

// ==================== 默认导出 ====================
// 保持与原 service.js 的 default export 兼容
export { SERVICE_DEFAULT as default } from './customerService.js';
