"""
导入AI知识库示例案例
包含50+个历史案例，涵盖多个行业和技术领域
"""
import sys
import os

# 添加项目根目录到路径
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy.orm import Session
from app.core.database import SessionLocal
from app.services.presale_ai_knowledge_service import PresaleAIKnowledgeService
from app.schemas.presale_ai_knowledge import KnowledgeCaseCreate


# ============= 示例案例数据 =============

SAMPLE_CASES = [
    # 汽车行业案例 (15个)
    {
        "case_name": "某汽车零部件ICT测试项目",
        "industry": "汽车制造",
        "equipment_type": "ICT测试设备",
        "customer_name": "某汽车零部件公司",
        "project_amount": 680000,
        "project_summary": "为汽车ECU生产线提供在线ICT测试解决方案，支持多种PCB规格",
        "technical_highlights": "高精度测试、快速换线、实时数据采集、SPC统计分析",
        "success_factors": "技术方案成熟、团队经验丰富、客户配合度高",
        "lessons_learned": "需要提前确认客户现场环境，特别是防静电和温湿度要求",
        "tags": ["ICT测试", "汽车行业", "ECU", "高精度"],
        "quality_score": 0.92,
    },
    {
        "case_name": "新能源汽车电池管理系统测试",
        "industry": "新能源汽车",
        "equipment_type": "功能测试设备",
        "customer_name": "某新能源汽车企业",
        "project_amount": 1200000,
        "project_summary": "BMS电池管理系统的功能测试和老化测试解决方案",
        "technical_highlights": "高压安全防护、多通道并行测试、智能老化算法",
        "success_factors": "安全设计完善、测试效率高、满足车规级要求",
        "lessons_learned": "高压测试需要严格的安全培训和防护措施",
        "tags": ["功能测试", "新能源", "BMS", "高压测试"],
        "quality_score": 0.90,
    },
    {
        "case_name": "汽车仪表盘AOI检测系统",
        "industry": "汽车制造",
        "equipment_type": "AOI检测设备",
        "customer_name": "某汽车仪表厂商",
        "project_amount": 850000,
        "project_summary": "汽车仪表盘外观自动光学检测系统",
        "technical_highlights": "深度学习算法、0.01mm精度、3D检测",
        "success_factors": "AI算法准确率高、检测速度快",
        "lessons_learned": "需要大量样本训练模型，初期准备时间较长",
        "tags": ["AOI", "汽车", "深度学习", "视觉检测"],
        "quality_score": 0.88,
    },
    {
        "case_name": "汽车线束测试系统",
        "industry": "汽车制造",
        "equipment_type": "线束测试设备",
        "customer_name": "某汽车线束供应商",
        "project_amount": 450000,
        "project_summary": "汽车线束导通、绝缘、耐压综合测试",
        "technical_highlights": "1024点位、自动识别、防错设计",
        "success_factors": "测试覆盖全面、操作简单",
        "lessons_learned": "需要考虑不同车型的线束差异",
        "tags": ["线束测试", "汽车", "导通测试"],
        "quality_score": 0.85,
    },
    {
        "case_name": "车载摄像头模组测试",
        "industry": "汽车电子",
        "equipment_type": "光学测试设备",
        "customer_name": "某车载摄像头厂商",
        "project_amount": 950000,
        "project_summary": "ADAS摄像头模组的光学性能测试",
        "technical_highlights": "MTF测试、畸变校准、色彩还原",
        "success_factors": "符合车规标准、测试精度高",
        "lessons_learned": "环境光照控制要求严格",
        "tags": ["光学测试", "ADAS", "摄像头", "车载"],
        "quality_score": 0.89,
    },
    {
        "case_name": "汽车空调控制器测试",
        "industry": "汽车制造",
        "equipment_type": "功能测试设备",
        "project_amount": 380000,
        "project_summary": "汽车空调控制器功能和环境测试",
        "technical_highlights": "温度模拟、信号注入、CAN通讯测试",
        "success_factors": "测试项目完整、自动化程度高",
        "lessons_learned": "温度模拟装置需要预热",
        "tags": ["功能测试", "汽车", "空调控制器"],
        "quality_score": 0.82,
    },
    {
        "case_name": "汽车安全气囊ECU测试",
        "industry": "汽车安全",
        "equipment_type": "功能测试设备",
        "project_amount": 720000,
        "project_summary": "安全气囊ECU的功能和安全性测试",
        "technical_highlights": "碰撞信号模拟、点火回路测试、失效模式分析",
        "success_factors": "安全测试严格、符合NCAP标准",
        "lessons_learned": "测试过程需要严格的安全防护",
        "tags": ["功能测试", "安全气囊", "ECU", "汽车安全"],
        "quality_score": 0.91,
    },
    {
        "case_name": "汽车座椅控制模块测试",
        "industry": "汽车制造",
        "equipment_type": "功能测试设备",
        "project_amount": 320000,
        "project_summary": "电动座椅控制模块的功能测试",
        "technical_highlights": "多电机控制、位置传感器校准、负载测试",
        "success_factors": "测试覆盖全面、可靠性高",
        "lessons_learned": "需要考虑不同负载下的性能差异",
        "tags": ["功能测试", "汽车", "座椅控制"],
        "quality_score": 0.80,
    },
    {
        "case_name": "车载充电器测试系统",
        "industry": "新能源汽车",
        "equipment_type": "电源测试设备",
        "project_amount": 880000,
        "project_summary": "车载充电器OBC的性能和安全测试",
        "technical_highlights": "高功率测试、效率分析、EMC测试",
        "success_factors": "测试精度高、安全可靠",
        "lessons_learned": "高功率测试需要充足的散热设计",
        "tags": ["电源测试", "OBC", "新能源", "充电器"],
        "quality_score": 0.87,
    },
    {
        "case_name": "汽车雨刮控制器测试",
        "industry": "汽车制造",
        "equipment_type": "功能测试设备",
        "project_amount": 280000,
        "project_summary": "雨刮控制器的功能和耐久性测试",
        "technical_highlights": "雨量传感器模拟、速度控制、耐久测试",
        "success_factors": "测试稳定性好、自动化程度高",
        "lessons_learned": "耐久测试周期较长，需要合理安排",
        "tags": ["功能测试", "汽车", "雨刮控制器"],
        "quality_score": 0.78,
    },
    {
        "case_name": "汽车门锁控制器测试",
        "industry": "汽车制造",
        "equipment_type": "功能测试设备",
        "project_amount": 350000,
        "project_summary": "车门锁控制器的功能和安全测试",
        "technical_highlights": "无钥匙进入模拟、防盗测试、机械耐久",
        "success_factors": "安全性测试严格、可靠性高",
        "lessons_learned": "无钥匙系统测试需要模拟多种场景",
        "tags": ["功能测试", "汽车", "门锁控制器", "安全"],
        "quality_score": 0.83,
    },
    {
        "case_name": "汽车大灯控制模块测试",
        "industry": "汽车照明",
        "equipment_type": "功能测试设备",
        "project_amount": 420000,
        "project_summary": "LED大灯控制模块的功能和光学测试",
        "technical_highlights": "光强测试、色温测试、自动调节验证",
        "success_factors": "测试精度高、符合法规要求",
        "lessons_learned": "光学测试环境要求严格",
        "tags": ["功能测试", "汽车", "LED大灯", "光学"],
        "quality_score": 0.84,
    },
    {
        "case_name": "汽车轮胎压力监测系统测试",
        "industry": "汽车安全",
        "equipment_type": "功能测试设备",
        "project_amount": 390000,
        "project_summary": "TPMS传感器和接收器的测试",
        "technical_highlights": "无线通讯测试、压力传感器校准、温度补偿",
        "success_factors": "通讯可靠性高、校准精度好",
        "lessons_learned": "需要考虑不同温度下的性能变化",
        "tags": ["功能测试", "TPMS", "汽车安全", "无线"],
        "quality_score": 0.81,
    },
    {
        "case_name": "汽车倒车雷达测试系统",
        "industry": "汽车电子",
        "equipment_type": "功能测试设备",
        "project_amount": 310000,
        "project_summary": "倒车雷达传感器的性能测试",
        "technical_highlights": "超声波测距、目标识别、抗干扰测试",
        "success_factors": "测试覆盖全面、精度高",
        "lessons_learned": "需要模拟多种障碍物场景",
        "tags": ["功能测试", "倒车雷达", "超声波", "汽车"],
        "quality_score": 0.79,
    },
    {
        "case_name": "汽车防抱死制动系统测试",
        "industry": "汽车安全",
        "equipment_type": "功能测试设备",
        "customer_name": "某汽车制动系统供应商",
        "project_amount": 1100000,
        "project_summary": "ABS系统的功能和安全性测试",
        "technical_highlights": "轮速传感器模拟、制动力测试、HIL仿真",
        "success_factors": "测试精度高、符合安全标准",
        "lessons_learned": "HIL测试需要准确的车辆模型",
        "tags": ["功能测试", "ABS", "汽车安全", "HIL"],
        "quality_score": 0.93,
    },
    
    # 消费电子行业案例 (15个)
    {
        "case_name": "智能手机主板ICT测试",
        "industry": "消费电子",
        "equipment_type": "ICT测试设备",
        "customer_name": "某手机制造商",
        "project_amount": 580000,
        "project_summary": "智能手机主板的在线ICT测试",
        "technical_highlights": "高密度探针、RF测试、快速测试",
        "success_factors": "测试速度快、良率高",
        "lessons_learned": "探针维护成本高，需要定期更换",
        "tags": ["ICT测试", "手机", "消费电子"],
        "quality_score": 0.86,
    },
    {
        "case_name": "笔记本电脑功能测试系统",
        "industry": "消费电子",
        "equipment_type": "功能测试设备",
        "customer_name": "某笔记本电脑厂商",
        "project_amount": 920000,
        "project_summary": "笔记本电脑整机功能自动化测试",
        "technical_highlights": "多工位并行、全功能覆盖、自动判定",
        "success_factors": "自动化程度高、测试效率高",
        "lessons_learned": "需要适配多种型号和配置",
        "tags": ["功能测试", "笔记本", "消费电子", "自动化"],
        "quality_score": 0.88,
    },
    {
        "case_name": "无线耳机音频测试系统",
        "industry": "消费电子",
        "equipment_type": "音频测试设备",
        "customer_name": "某音频设备厂商",
        "project_amount": 450000,
        "project_summary": "TWS耳机的音频性能和蓝牙测试",
        "technical_highlights": "THD+N测试、频响曲线、蓝牙兼容性",
        "success_factors": "测试精度高、兼容性好",
        "lessons_learned": "蓝牙测试需要屏蔽环境",
        "tags": ["音频测试", "TWS", "蓝牙", "消费电子"],
        "quality_score": 0.85,
    },
    {
        "case_name": "智能手表功能测试",
        "industry": "可穿戴设备",
        "equipment_type": "功能测试设备",
        "project_amount": 380000,
        "project_summary": "智能手表的功能和续航测试",
        "technical_highlights": "触摸屏测试、传感器校准、功耗测试",
        "success_factors": "测试项目完整、自动化程度高",
        "lessons_learned": "传感器校准需要标准设备",
        "tags": ["功能测试", "智能手表", "可穿戴"],
        "quality_score": 0.82,
    },
    {
        "case_name": "平板电脑显示屏测试",
        "industry": "消费电子",
        "equipment_type": "显示测试设备",
        "project_amount": 680000,
        "project_summary": "平板电脑LCD/OLED显示屏性能测试",
        "technical_highlights": "色域测试、亮度均匀性、触摸精度",
        "success_factors": "测试精度高、速度快",
        "lessons_learned": "环境光照影响大，需要暗室",
        "tags": ["显示测试", "平板", "LCD", "OLED"],
        "quality_score": 0.87,
    },
    {
        "case_name": "智能音箱音频测试",
        "industry": "消费电子",
        "equipment_type": "音频测试设备",
        "project_amount": 320000,
        "project_summary": "智能音箱的音质和语音识别测试",
        "technical_highlights": "声学测试、远场语音、降噪测试",
        "success_factors": "测试环境专业、精度高",
        "lessons_learned": "需要消音室进行测试",
        "tags": ["音频测试", "智能音箱", "语音识别"],
        "quality_score": 0.83,
    },
    {
        "case_name": "移动电源性能测试",
        "industry": "消费电子",
        "equipment_type": "电源测试设备",
        "project_amount": 280000,
        "project_summary": "移动电源的充放电性能测试",
        "technical_highlights": "快充协议、转换效率、循环寿命",
        "success_factors": "测试全面、数据准确",
        "lessons_learned": "循环测试周期长",
        "tags": ["电源测试", "移动电源", "快充"],
        "quality_score": 0.80,
    },
    {
        "case_name": "游戏手柄功能测试",
        "industry": "消费电子",
        "equipment_type": "功能测试设备",
        "project_amount": 220000,
        "project_summary": "游戏手柄的按键和摇杆测试",
        "technical_highlights": "按键寿命、摇杆精度、延迟测试",
        "success_factors": "测试准确、效率高",
        "lessons_learned": "机械耐久测试时间长",
        "tags": ["功能测试", "游戏手柄", "耐久测试"],
        "quality_score": 0.78,
    },
    {
        "case_name": "VR头显光学测试",
        "industry": "消费电子",
        "equipment_type": "光学测试设备",
        "project_amount": 750000,
        "project_summary": "VR头显的光学性能和显示测试",
        "technical_highlights": "FOV测试、畸变校正、刷新率",
        "success_factors": "测试专业、精度高",
        "lessons_learned": "光学测试设备投资大",
        "tags": ["光学测试", "VR", "显示", "消费电子"],
        "quality_score": 0.89,
    },
    {
        "case_name": "智能门锁功能测试",
        "industry": "智能家居",
        "equipment_type": "功能测试设备",
        "project_amount": 420000,
        "project_summary": "智能门锁的安全和功能测试",
        "technical_highlights": "指纹识别、NFC、机械寿命",
        "success_factors": "安全测试严格、可靠性高",
        "lessons_learned": "指纹库需要多样性",
        "tags": ["功能测试", "智能门锁", "智能家居", "安全"],
        "quality_score": 0.84,
    },
    {
        "case_name": "路由器WiFi性能测试",
        "industry": "网络设备",
        "equipment_type": "无线测试设备",
        "project_amount": 550000,
        "project_summary": "WiFi路由器的无线性能测试",
        "technical_highlights": "吞吐量测试、信号覆盖、多设备并发",
        "success_factors": "测试环境专业、数据准确",
        "lessons_learned": "需要屏蔽室进行测试",
        "tags": ["无线测试", "WiFi", "路由器", "网络"],
        "quality_score": 0.86,
    },
    {
        "case_name": "摄像头模组测试",
        "industry": "消费电子",
        "equipment_type": "光学测试设备",
        "project_amount": 680000,
        "project_summary": "手机摄像头模组的光学测试",
        "technical_highlights": "解析力、色彩还原、自动对焦",
        "success_factors": "测试精度高、效率高",
        "lessons_learned": "光学标定板需要定期校准",
        "tags": ["光学测试", "摄像头", "手机", "模组"],
        "quality_score": 0.88,
    },
    {
        "case_name": "无线充电器测试",
        "industry": "消费电子",
        "equipment_type": "电源测试设备",
        "project_amount": 350000,
        "project_summary": "Qi无线充电器的性能测试",
        "technical_highlights": "效率测试、异物检测、温升测试",
        "success_factors": "测试全面、精度高",
        "lessons_learned": "线圈对齐很重要",
        "tags": ["电源测试", "无线充电", "Qi", "消费电子"],
        "quality_score": 0.82,
    },
    {
        "case_name": "电子烟性能测试",
        "industry": "消费电子",
        "equipment_type": "功能测试设备",
        "project_amount": 280000,
        "project_summary": "电子烟的功率和安全测试",
        "technical_highlights": "功率控制、短路保护、电池安全",
        "success_factors": "安全测试严格",
        "lessons_learned": "电池安全测试需要防护措施",
        "tags": ["功能测试", "电子烟", "安全", "消费电子"],
        "quality_score": 0.79,
    },
    {
        "case_name": "电子书阅读器测试",
        "industry": "消费电子",
        "equipment_type": "显示测试设备",
        "project_amount": 320000,
        "project_summary": "电子墨水屏阅读器的显示测试",
        "technical_highlights": "对比度、响应速度、触摸精度",
        "success_factors": "测试专业、效率高",
        "lessons_learned": "电子墨水屏响应慢，需要特殊测试方法",
        "tags": ["显示测试", "电子书", "电子墨水屏"],
        "quality_score": 0.81,
    },
    
    # 工业设备行业案例 (10个)
    {
        "case_name": "工业控制器测试系统",
        "industry": "工业自动化",
        "equipment_type": "功能测试设备",
        "customer_name": "某PLC制造商",
        "project_amount": 850000,
        "project_summary": "工业PLC控制器的功能和可靠性测试",
        "technical_highlights": "多协议支持、高低温测试、EMC测试",
        "success_factors": "测试覆盖全面、可靠性高",
        "lessons_learned": "需要考虑工业环境的恶劣条件",
        "tags": ["功能测试", "PLC", "工业自动化"],
        "quality_score": 0.90,
    },
    {
        "case_name": "变频器性能测试",
        "industry": "工业设备",
        "equipment_type": "电源测试设备",
        "project_amount": 720000,
        "project_summary": "工业变频器的性能和效率测试",
        "technical_highlights": "高功率测试、效率分析、谐波测试",
        "success_factors": "测试精度高、安全可靠",
        "lessons_learned": "高功率测试需要专业配电",
        "tags": ["电源测试", "变频器", "工业", "高功率"],
        "quality_score": 0.87,
    },
    {
        "case_name": "伺服驱动器测试",
        "industry": "工业自动化",
        "equipment_type": "功能测试设备",
        "project_amount": 680000,
        "project_summary": "伺服驱动器的控制精度和动态响应测试",
        "technical_highlights": "位置精度、速度响应、力矩测试",
        "success_factors": "测试精度高、动态性能好",
        "lessons_learned": "需要配套电机负载模拟",
        "tags": ["功能测试", "伺服", "工业自动化", "运动控制"],
        "quality_score": 0.88,
    },
    {
        "case_name": "工业传感器校准系统",
        "industry": "工业设备",
        "equipment_type": "校准设备",
        "project_amount": 450000,
        "project_summary": "工业压力、温度传感器的校准测试",
        "technical_highlights": "高精度校准、温度补偿、长期稳定性",
        "success_factors": "校准精度高、可溯源",
        "lessons_learned": "标准器需要定期送检",
        "tags": ["校准", "传感器", "工业", "计量"],
        "quality_score": 0.85,
    },
    {
        "case_name": "工业机器人控制器测试",
        "industry": "机器人",
        "equipment_type": "功能测试设备",
        "project_amount": 920000,
        "project_summary": "工业机器人控制器的功能和安全测试",
        "technical_highlights": "多轴联动、安全回路、轨迹精度",
        "success_factors": "测试全面、安全可靠",
        "lessons_learned": "安全测试必须严格执行",
        "tags": ["功能测试", "机器人", "工业", "安全"],
        "quality_score": 0.91,
    },
    {
        "case_name": "工业电源模块测试",
        "industry": "工业设备",
        "equipment_type": "电源测试设备",
        "project_amount": 380000,
        "project_summary": "工业开关电源的性能测试",
        "technical_highlights": "效率测试、纹波测试、可靠性测试",
        "success_factors": "测试精度高、覆盖全面",
        "lessons_learned": "长期老化测试很重要",
        "tags": ["电源测试", "工业电源", "可靠性"],
        "quality_score": 0.83,
    },
    {
        "case_name": "工业以太网交换机测试",
        "industry": "工业网络",
        "equipment_type": "网络测试设备",
        "project_amount": 550000,
        "project_summary": "工业以太网交换机的性能和可靠性测试",
        "technical_highlights": "吞吐量、延迟、环境测试",
        "success_factors": "测试全面、可靠性高",
        "lessons_learned": "工业环境测试很重要",
        "tags": ["网络测试", "工业以太网", "交换机"],
        "quality_score": 0.86,
    },
    {
        "case_name": "工业显示屏测试",
        "industry": "工业设备",
        "equipment_type": "显示测试设备",
        "project_amount": 420000,
        "project_summary": "工业触摸显示屏的性能测试",
        "technical_highlights": "宽温测试、亮度、触摸精度",
        "success_factors": "测试全面、可靠性高",
        "lessons_learned": "宽温测试需要专业设备",
        "tags": ["显示测试", "工业显示", "触摸屏"],
        "quality_score": 0.84,
    },
    {
        "case_name": "工业相机测试系统",
        "industry": "机器视觉",
        "equipment_type": "光学测试设备",
        "project_amount": 680000,
        "project_summary": "工业相机的成像性能测试",
        "technical_highlights": "MTF测试、畸变、帧率",
        "success_factors": "测试精度高、专业性强",
        "lessons_learned": "光学测试环境要求严格",
        "tags": ["光学测试", "工业相机", "机器视觉"],
        "quality_score": 0.88,
    },
    {
        "case_name": "工业UPS测试系统",
        "industry": "工业设备",
        "equipment_type": "电源测试设备",
        "project_amount": 780000,
        "project_summary": "工业UPS不间断电源的性能测试",
        "technical_highlights": "切换时间、效率、电池管理",
        "success_factors": "测试全面、精度高",
        "lessons_learned": "大功率测试需要充足的配电",
        "tags": ["电源测试", "UPS", "工业", "不间断电源"],
        "quality_score": 0.87,
    },
    
    # 医疗设备行业案例 (5个)
    {
        "case_name": "医疗监护仪测试系统",
        "industry": "医疗设备",
        "equipment_type": "功能测试设备",
        "customer_name": "某医疗器械公司",
        "project_amount": 950000,
        "project_summary": "多参数监护仪的功能和安全测试",
        "technical_highlights": "生理信号模拟、报警测试、电气安全",
        "success_factors": "符合医疗标准、测试严格",
        "lessons_learned": "医疗认证要求高",
        "tags": ["功能测试", "医疗", "监护仪", "安全"],
        "quality_score": 0.92,
    },
    {
        "case_name": "血糖仪测试系统",
        "industry": "医疗设备",
        "equipment_type": "功能测试设备",
        "project_amount": 420000,
        "project_summary": "血糖仪的精度和稳定性测试",
        "technical_highlights": "精度验证、标准品测试、用户测试",
        "success_factors": "测试精度高、符合标准",
        "lessons_learned": "需要医疗级标准品",
        "tags": ["功能测试", "医疗", "血糖仪", "精度"],
        "quality_score": 0.88,
    },
    {
        "case_name": "医用电源测试",
        "industry": "医疗设备",
        "equipment_type": "电源测试设备",
        "project_amount": 520000,
        "project_summary": "医用电源的性能和安全测试",
        "technical_highlights": "漏电流、绝缘、EMC",
        "success_factors": "符合医疗标准、安全可靠",
        "lessons_learned": "医疗电源安全要求极高",
        "tags": ["电源测试", "医疗", "安全", "EMC"],
        "quality_score": 0.90,
    },
    {
        "case_name": "医疗影像设备测试",
        "industry": "医疗设备",
        "equipment_type": "显示测试设备",
        "project_amount": 880000,
        "project_summary": "医疗显示器的性能测试",
        "technical_highlights": "灰阶测试、DICOM标准、亮度校准",
        "success_factors": "测试专业、符合标准",
        "lessons_learned": "医疗显示标准要求严格",
        "tags": ["显示测试", "医疗", "DICOM", "影像"],
        "quality_score": 0.91,
    },
    {
        "case_name": "医用传感器测试",
        "industry": "医疗设备",
        "equipment_type": "功能测试设备",
        "project_amount": 380000,
        "project_summary": "医用生理传感器的性能测试",
        "technical_highlights": "精度验证、响应时间、生物兼容性",
        "success_factors": "测试精度高、符合医疗标准",
        "lessons_learned": "需要生物模拟装置",
        "tags": ["功能测试", "医疗", "传感器", "精度"],
        "quality_score": 0.86,
    },
    
    # 通讯设备行业案例 (5个)
    {
        "case_name": "5G基站测试系统",
        "industry": "通讯设备",
        "equipment_type": "RF测试设备",
        "customer_name": "某通讯设备商",
        "project_amount": 1500000,
        "project_summary": "5G基站的RF性能测试",
        "technical_highlights": "毫米波测试、MIMO、功率测试",
        "success_factors": "测试精度高、支持5G标准",
        "lessons_learned": "毫米波测试技术要求高",
        "tags": ["RF测试", "5G", "基站", "通讯"],
        "quality_score": 0.93,
    },
    {
        "case_name": "光模块测试系统",
        "industry": "通讯设备",
        "equipment_type": "光学测试设备",
        "project_amount": 820000,
        "project_summary": "光通信模块的性能测试",
        "technical_highlights": "光功率、眼图、误码率",
        "success_factors": "测试精度高、速度快",
        "lessons_learned": "光学连接器清洁很重要",
        "tags": ["光学测试", "光模块", "通讯", "误码率"],
        "quality_score": 0.89,
    },
    {
        "case_name": "交换机性能测试",
        "industry": "网络设备",
        "equipment_type": "网络测试设备",
        "project_amount": 680000,
        "project_summary": "数据中心交换机的性能测试",
        "technical_highlights": "吞吐量、延迟、丢包率",
        "success_factors": "测试全面、精度高",
        "lessons_learned": "需要专业网络测试仪",
        "tags": ["网络测试", "交换机", "数据中心"],
        "quality_score": 0.87,
    },
    {
        "case_name": "天线性能测试",
        "industry": "通讯设备",
        "equipment_type": "RF测试设备",
        "project_amount": 720000,
        "project_summary": "无线通讯天线的性能测试",
        "technical_highlights": "方向图、增益、VSWR",
        "success_factors": "测试环境专业、精度高",
        "lessons_learned": "需要微波暗室",
        "tags": ["RF测试", "天线", "通讯", "增益"],
        "quality_score": 0.88,
    },
    {
        "case_name": "物联网模组测试",
        "industry": "物联网",
        "equipment_type": "功能测试设备",
        "project_amount": 450000,
        "project_summary": "IoT通讯模组的功能测试",
        "technical_highlights": "多协议支持、功耗测试、兼容性",
        "success_factors": "测试覆盖全面、效率高",
        "lessons_learned": "需要测试多种网络场景",
        "tags": ["功能测试", "IoT", "物联网", "通讯模组"],
        "quality_score": 0.84,
    },
]


def import_cases():
    """导入案例到数据库"""
    db = SessionLocal()
    service = PresaleAIKnowledgeService(db)
    
    success_count = 0
    fail_count = 0
    
    print("=" * 80)
    print("开始导入AI知识库案例...")
    print(f"总计案例数: {len(SAMPLE_CASES)}")
    print("=" * 80)
    
    for i, case_data in enumerate(SAMPLE_CASES, 1):
        try:
            case_create = KnowledgeCaseCreate(**case_data)
            case = service.create_case(case_create)
            
            success_count += 1
            print(f"[{i}/{len(SAMPLE_CASES)}] ✅ 成功导入: {case.case_name} (ID: {case.id})")
            
        except Exception as e:
            fail_count += 1
            print(f"[{i}/{len(SAMPLE_CASES)}] ❌ 导入失败: {case_data.get('case_name', 'Unknown')} - {str(e)}")
    
    db.close()
    
    print("=" * 80)
    print("导入完成!")
    print(f"✅ 成功: {success_count}")
    print(f"❌ 失败: {fail_count}")
    print(f"📊 成功率: {success_count / len(SAMPLE_CASES) * 100:.1f}%")
    print("=" * 80)


if __name__ == "__main__":
    import_cases()
