# -*- coding: utf-8 -*-
"""
初始化报告指标定义
预置系统常用指标，管理部可以在此基础上自定义
"""
import sys
from pathlib import Path

# 添加项目根目录到路径
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from app.models.base import get_db_session
from app.models.management_rhythm import ReportMetricDefinition


# 预置指标定义
PREDEFINED_METRICS = [
    # ==================== 项目管理模块 ====================
    {
        "metric_code": "project_total",
        "metric_name": "项目总数",
        "category": "项目管理",
        "description": "统计所有项目数量",
        "data_source": "Project",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "project_new",
        "metric_name": "新增项目数",
        "category": "项目管理",
        "description": "本月/年新增项目数",
        "data_source": "Project",
        "filter_conditions": {"filters": [{"field": "created_at", "operator": ">=", "value": "period_start"}]},
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "project_completed",
        "metric_name": "完成项目数",
        "category": "项目管理",
        "description": "本月/年完成项目数（actual_end_date在周期内）",
        "data_source": "Project",
        "filter_conditions": {"filters": [{"field": "actual_end_date", "operator": ">=", "value": "period_start"}, {"field": "actual_end_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "project_in_progress",
        "metric_name": "进行中项目数",
        "category": "项目管理",
        "description": "当前进行中的项目数（非S9阶段）",
        "data_source": "Project",
        "filter_conditions": {"filters": [{"field": "stage", "operator": "!=", "value": "S9"}]},
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "project_contract_amount",
        "metric_name": "项目合同总额",
        "category": "项目管理",
        "description": "所有项目合同金额汇总",
        "data_source": "Project",
        "data_field": "contract_amount",
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "project_new_contract_amount",
        "metric_name": "新增合同额",
        "category": "项目管理",
        "description": "本月/年新签合同额（contract_date在周期内）",
        "data_source": "Project",
        "data_field": "contract_amount",
        "filter_conditions": {"filters": [{"field": "contract_date", "operator": ">=", "value": "period_start"}, {"field": "contract_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "project_actual_cost",
        "metric_name": "项目实际成本",
        "category": "项目管理",
        "description": "所有项目实际成本汇总",
        "data_source": "Project",
        "data_field": "actual_cost",
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "project_avg_progress",
        "metric_name": "平均项目进度",
        "category": "项目管理",
        "description": "所有项目进度平均值",
        "data_source": "Project",
        "data_field": "progress_pct",
        "calculation_type": "AVG",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "project_health_abnormal",
        "metric_name": "健康度异常项目数",
        "category": "项目管理",
        "description": "健康度为H2或H3的项目数",
        "data_source": "Project",
        "filter_conditions": {"filters": [{"field": "health", "operator": "IN", "value": ["H2", "H3"]}]},
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    # ==================== 销售管理模块 ====================
    {
        "metric_code": "lead_total",
        "metric_name": "线索总数",
        "category": "销售管理",
        "description": "线索数量",
        "data_source": "Lead",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "lead_new",
        "metric_name": "新增线索数",
        "category": "销售管理",
        "description": "本月/年新增线索",
        "data_source": "Lead",
        "filter_conditions": {"filters": [{"field": "created_at", "operator": ">=", "value": "period_start"}]},
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "opportunity_total",
        "metric_name": "商机总数",
        "category": "销售管理",
        "description": "商机数量",
        "data_source": "Opportunity",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "contract_total",
        "metric_name": "合同总数",
        "category": "销售管理",
        "description": "合同数量",
        "data_source": "Contract",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "contract_new_amount",
        "metric_name": "新签合同额",
        "category": "销售管理",
        "description": "本月/年新签合同额",
        "data_source": "Contract",
        "data_field": "contract_amount",
        "filter_conditions": {"filters": [{"field": "contract_date", "operator": ">=", "value": "period_start"}, {"field": "contract_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "payment_total",
        "metric_name": "回款总额",
        "category": "销售管理",
        "description": "实际回款金额汇总",
        "data_source": "ContractPayment",
        "data_field": "actual_amount",
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "payment_monthly",
        "metric_name": "本月回款额",
        "category": "销售管理",
        "description": "本月回款金额",
        "data_source": "ContractPayment",
        "data_field": "actual_amount",
        "filter_conditions": {"filters": [{"field": "payment_date", "operator": ">=", "value": "period_start"}, {"field": "payment_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== 采购管理模块 ====================
    {
        "metric_code": "purchase_order_total",
        "metric_name": "采购订单总数",
        "category": "采购管理",
        "description": "采购订单数量",
        "data_source": "PurchaseOrder",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "purchase_order_amount",
        "metric_name": "采购订单金额",
        "category": "采购管理",
        "description": "采购订单总金额",
        "data_source": "PurchaseOrder",
        "data_field": "total_amount",
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "purchase_order_monthly",
        "metric_name": "本月采购额",
        "category": "采购管理",
        "description": "本月采购金额",
        "data_source": "PurchaseOrder",
        "data_field": "total_amount",
        "filter_conditions": {"filters": [{"field": "order_date", "operator": ">=", "value": "period_start"}, {"field": "order_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "元",
        "format_type": "CURRENCY",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== ECN管理模块 ====================
    {
        "metric_code": "ecn_total",
        "metric_name": "ECN总数",
        "category": "变更管理",
        "description": "工程变更通知数量",
        "data_source": "Ecn",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "ecn_approved_rate",
        "metric_name": "ECN批准率",
        "category": "变更管理",
        "description": "已批准ECN数 / ECN总数",
        "data_source": "Ecn",
        "calculation_type": "RATIO",
        "calculation_formula": "COUNT(WHERE status='APPROVED') / COUNT()",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== 验收管理模块 ====================
    {
        "metric_code": "acceptance_total",
        "metric_name": "验收单总数",
        "category": "验收管理",
        "description": "验收单数量",
        "data_source": "AcceptanceOrder",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "acceptance_pass_rate",
        "metric_name": "验收通过率",
        "category": "验收管理",
        "description": "通过验收数 / 验收总数",
        "data_source": "AcceptanceOrder",
        "calculation_type": "RATIO",
        "calculation_formula": "COUNT(WHERE status='PASSED') / COUNT()",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== 问题管理模块 ====================
    {
        "metric_code": "issue_total",
        "metric_name": "问题总数",
        "category": "问题管理",
        "description": "问题数量",
        "data_source": "Issue",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "issue_resolve_rate",
        "metric_name": "问题解决率",
        "category": "问题管理",
        "description": "已解决问题数 / 问题总数",
        "data_source": "Issue",
        "calculation_type": "RATIO",
        "calculation_formula": "COUNT(WHERE status='RESOLVED') / COUNT()",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== 工时管理模块 ====================
    {
        "metric_code": "timesheet_total",
        "metric_name": "总工时",
        "category": "工时管理",
        "description": "所有工时汇总",
        "data_source": "Timesheet",
        "data_field": "hours",
        "filter_conditions": {"filters": [{"field": "work_date", "operator": ">=", "value": "period_start"}, {"field": "work_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "小时",
        "format_type": "NUMBER",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "timesheet_overtime",
        "metric_name": "加班工时",
        "category": "工时管理",
        "description": "加班工时汇总",
        "data_source": "Timesheet",
        "data_field": "hours",
        "filter_conditions": {"filters": [{"field": "overtime_type", "operator": "!=", "value": "NORMAL"}, {"field": "work_date", "operator": ">=", "value": "period_start"}, {"field": "work_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "SUM",
        "support_mom": True,
        "support_yoy": True,
        "unit": "小时",
        "format_type": "NUMBER",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== 任务中心模块 ====================
    {
        "metric_code": "task_total",
        "metric_name": "任务总数",
        "category": "任务管理",
        "description": "任务数量",
        "data_source": "TaskUnified",
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "task_completion_rate",
        "metric_name": "任务完成率",
        "category": "任务管理",
        "description": "已完成任务数 / 任务总数",
        "data_source": "TaskUnified",
        "calculation_type": "RATIO",
        "calculation_formula": "COUNT(WHERE status='COMPLETED') / COUNT()",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
    # ==================== 管理节律模块 ====================
    {
        "metric_code": "meeting_total",
        "metric_name": "会议总数",
        "category": "管理节律",
        "description": "会议数量",
        "data_source": "StrategicMeeting",
        "filter_conditions": {"filters": [{"field": "meeting_date", "operator": ">=", "value": "period_start"}, {"field": "meeting_date", "operator": "<=", "value": "period_end"}]},
        "calculation_type": "COUNT",
        "support_mom": True,
        "support_yoy": True,
        "unit": "个",
        "format_type": "NUMBER",
        "decimal_places": 0,
        "is_system": True,
    },
    {
        "metric_code": "meeting_completion_rate",
        "metric_name": "会议完成率",
        "category": "管理节律",
        "description": "已完成会议数 / 会议总数",
        "data_source": "StrategicMeeting",
        "calculation_type": "RATIO",
        "calculation_formula": "COUNT(WHERE status='COMPLETED') / COUNT()",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
    {
        "metric_code": "action_item_completion_rate",
        "metric_name": "行动项完成率",
        "category": "管理节律",
        "description": "已完成行动项数 / 行动项总数",
        "data_source": "MeetingActionItem",
        "calculation_type": "RATIO",
        "calculation_formula": "COUNT(WHERE status='COMPLETED') / COUNT()",
        "support_mom": True,
        "support_yoy": True,
        "unit": "%",
        "format_type": "PERCENTAGE",
        "decimal_places": 2,
        "is_system": True,
    },
]


def init_report_metrics():
    """初始化报告指标定义"""
    with get_db_session() as db:
        # 检查是否已有指标
        existing_count = db.query(ReportMetricDefinition).count()
        if existing_count > 0:
            print(f"已存在 {existing_count} 个指标定义，跳过初始化")
            return
        
        # 创建预置指标
        created_count = 0
        for metric_data in PREDEFINED_METRICS:
            # 检查是否已存在
            existing = db.query(ReportMetricDefinition).filter(
                ReportMetricDefinition.metric_code == metric_data["metric_code"]
            ).first()
            
            if not existing:
                metric = ReportMetricDefinition(**metric_data)
                db.add(metric)
                created_count += 1
        
        db.commit()
        print(f"成功创建 {created_count} 个预置指标定义")


if __name__ == "__main__":
    print("开始初始化报告指标定义...")
    init_report_metrics()
    print("初始化完成！")
