#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
销售模块演示数据生成脚本
生成：客户、商机、关系评估、赢单率预测等演示数据
"""

import json
from datetime import date, timedelta
from pathlib import Path

# ========== 1. 客户数据 ==========

customers = [
    {
        "id": 1,
        "name": "宁德时代新能源科技股份有限公司",
        "short_name": "宁德时代",
        "industry": "锂电池",
        "location": "福建宁德",
        "scale": "大型",
        "annual_revenue": 30000000000,
        "employee_count": 50000,
        "stage": "战略合作客户",
        "priority": "A",
        "owner_id": 101,
        "owner_name": "张三",
        "created_at": "2024-06-15",
        "last_contact": "2026-02-28",
        "next_followup": "2026-03-05",
        "tags": ["动力电池", "储能", "头部客户", "上市公司"],
        "decision_chain": {
            "EB": {
                "name": "曾毓群",
                "title": "董事长",
                "contact": "138****0001",
                "attitude": "neutral",
            },
            "TB": {
                "name": "吴凯",
                "title": "首席科学家",
                "contact": "138****0002",
                "attitude": "supportive",
            },
            "PB": {
                "name": "李平",
                "title": "采购总监",
                "contact": "138****0003",
                "attitude": "neutral",
            },
            "UB": {
                "name": "赵伟",
                "title": "生产总监",
                "contact": "138****0004",
                "attitude": "supportive",
            },
            "Coach": {
                "name": "钱七",
                "title": "设备工程师",
                "contact": "138****0005",
                "attitude": "supportive",
            },
        },
    },
    {
        "id": 2,
        "name": "比亚迪股份有限公司",
        "short_name": "比亚迪",
        "industry": "新能源汽车",
        "location": "广东深圳",
        "scale": "大型",
        "annual_revenue": 40000000000,
        "employee_count": 60000,
        "stage": "战略合作客户",
        "priority": "A",
        "owner_id": 102,
        "owner_name": "李四",
        "created_at": "2024-03-20",
        "last_contact": "2026-02-27",
        "next_followup": "2026-03-03",
        "tags": ["新能源汽车", "电池", "整车", "上市公司"],
        "decision_chain": {
            "EB": {
                "name": "王传福",
                "title": "董事长",
                "contact": "139****0001",
                "attitude": "supportive",
            },
            "TB": {
                "name": "廉玉波",
                "title": "副总裁",
                "contact": "139****0002",
                "attitude": "supportive",
            },
            "PB": {
                "name": "何志健",
                "title": "采购总经理",
                "contact": "139****0003",
                "attitude": "supportive",
            },
            "UB": {
                "name": "张强",
                "title": "工厂厂长",
                "contact": "139****0004",
                "attitude": "supportive",
            },
            "Coach": {
                "name": "刘工",
                "title": "设备主管",
                "contact": "139****0005",
                "attitude": "supportive",
            },
        },
    },
    {
        "id": 3,
        "name": "中创新航科技股份有限公司",
        "short_name": "中创新航",
        "industry": "锂电池",
        "location": "江苏常州",
        "scale": "中型",
        "annual_revenue": 15000000000,
        "employee_count": 20000,
        "stage": "重点开发客户",
        "priority": "A",
        "owner_id": 101,
        "owner_name": "张三",
        "created_at": "2025-01-10",
        "last_contact": "2026-02-25",
        "next_followup": "2026-03-04",
        "tags": ["动力电池", "储能", "上市公司"],
        "decision_chain": {
            "EB": {
                "name": "刘静瑜",
                "title": "董事长",
                "contact": "137****0001",
                "attitude": "neutral",
            },
            "TB": {
                "name": "陈工",
                "title": "技术总监",
                "contact": "137****0002",
                "attitude": "neutral",
            },
            "PB": {
                "name": "王采购",
                "title": "采购经理",
                "contact": "137****0003",
                "attitude": "neutral",
            },
            "UB": {
                "name": "李生产",
                "title": "生产经理",
                "contact": "137****0004",
                "attitude": "supportive",
            },
            "Coach": None,
        },
    },
    {
        "id": 4,
        "name": "惠州亿纬锂能股份有限公司",
        "short_name": "亿纬锂能",
        "industry": "锂电池",
        "location": "广东惠州",
        "scale": "中型",
        "annual_revenue": 12000000000,
        "employee_count": 18000,
        "stage": "合作客户",
        "priority": "B",
        "owner_id": 103,
        "owner_name": "王五",
        "created_at": "2024-09-05",
        "last_contact": "2026-02-26",
        "next_followup": "2026-03-06",
        "tags": ["消费电池", "动力电池", "上市公司"],
        "decision_chain": {
            "EB": {
                "name": "刘金成",
                "title": "董事长",
                "contact": "136****0001",
                "attitude": "supportive",
            },
            "TB": {
                "name": "技术总",
                "title": "技术总监",
                "contact": "136****0002",
                "attitude": "supportive",
            },
            "PB": {
                "name": "采购总",
                "title": "采购总监",
                "contact": "136****0003",
                "attitude": "neutral",
            },
            "UB": {
                "name": "生产总",
                "title": "生产总监",
                "contact": "136****0004",
                "attitude": "supportive",
            },
            "Coach": {
                "name": "内部人",
                "title": "工程师",
                "contact": "136****0005",
                "attitude": "supportive",
            },
        },
    },
    {
        "id": 5,
        "name": "欣旺达电子股份有限公司",
        "short_name": "欣旺达",
        "industry": "锂电池",
        "location": "广东深圳",
        "scale": "中型",
        "annual_revenue": 10000000000,
        "employee_count": 15000,
        "stage": "开发中客户",
        "priority": "B",
        "owner_id": 104,
        "owner_name": "赵六",
        "created_at": "2025-06-20",
        "last_contact": "2026-02-15",
        "next_followup": "2026-03-02",
        "tags": ["消费电池", "动力电池"],
        "decision_chain": {
            "EB": {
                "name": "王威",
                "title": "总经理",
                "contact": "135****0001",
                "attitude": "unknown",
            },
            "TB": {
                "name": "技术总",
                "title": "技术总监",
                "contact": "135****0002",
                "attitude": "neutral",
            },
            "PB": None,
            "UB": None,
            "Coach": None,
        },
    },
    {
        "id": 6,
        "name": "蜂巢能源科技有限公司",
        "short_name": "蜂巢能源",
        "industry": "锂电池",
        "location": "江苏常州",
        "scale": "中型",
        "annual_revenue": 8000000000,
        "employee_count": 12000,
        "stage": "开发中客户",
        "priority": "B",
        "owner_id": 104,
        "owner_name": "赵六",
        "created_at": "2025-08-15",
        "last_contact": "2026-02-10",
        "next_followup": "2026-03-03",
        "tags": ["动力电池", "储能"],
        "decision_chain": {
            "EB": {
                "name": "杨红新",
                "title": "董事长",
                "contact": "134****0001",
                "attitude": "unknown",
            },
            "TB": None,
            "PB": None,
            "UB": None,
            "Coach": None,
        },
    },
    {
        "id": 7,
        "name": "国轩高科股份有限公司",
        "short_name": "国轩高科",
        "industry": "锂电池",
        "location": "安徽合肥",
        "scale": "中型",
        "annual_revenue": 9000000000,
        "employee_count": 14000,
        "stage": "初步接触",
        "priority": "C",
        "owner_id": 105,
        "owner_name": "钱七",
        "created_at": "2025-11-01",
        "last_contact": "2026-02-20",
        "next_followup": "2026-03-10",
        "tags": ["动力电池", "上市公司"],
        "decision_chain": {
            "EB": {
                "name": "李缜",
                "title": "董事长",
                "contact": "133****0001",
                "attitude": "unknown",
            },
            "TB": None,
            "PB": None,
            "UB": None,
            "Coach": None,
        },
    },
    {
        "id": 8,
        "name": "珠海冠宇电池股份有限公司",
        "short_name": "珠海冠宇",
        "industry": "消费电池",
        "location": "广东珠海",
        "scale": "中型",
        "annual_revenue": 7000000000,
        "employee_count": 10000,
        "stage": "合作客户",
        "priority": "B",
        "owner_id": 103,
        "owner_name": "王五",
        "created_at": "2024-12-10",
        "last_contact": "2026-02-28",
        "next_followup": "2026-03-07",
        "tags": ["消费电池", "笔记本电脑", "上市公司"],
        "decision_chain": {
            "EB": {
                "name": "徐延铭",
                "title": "董事长",
                "contact": "132****0001",
                "attitude": "supportive",
            },
            "TB": {
                "name": "技术总",
                "title": "技术总监",
                "contact": "132****0002",
                "attitude": "supportive",
            },
            "PB": {
                "name": "采购总",
                "title": "采购经理",
                "contact": "132****0003",
                "attitude": "neutral",
            },
            "UB": {
                "name": "生产总",
                "title": "生产经理",
                "contact": "132****0004",
                "attitude": "supportive",
            },
            "Coach": {
                "name": "内部人",
                "title": "工程师",
                "contact": "132****0005",
                "attitude": "supportive",
            },
        },
    },
]

# ========== 2. 商机数据 ==========

opportunities = [
    {
        "id": 1,
        "customer_id": 1,
        "customer_name": "宁德时代",
        "name": "FCT 测试线项目",
        "type": "FCT",
        "stage": "商务谈判",
        "amount": 3500000,
        "currency": "CNY",
        "probability": 75,
        "expected_close_date": "2026-03-31",
        "created_at": "2025-11-15",
        "owner_id": 101,
        "owner_name": "张三",
        "description": "新建 FCT 测试线 3 条，用于动力电池包测试",
        "requirements": [
            "测试电压：0-1000V",
            "测试电流：0-500A",
            "测试精度：±0.1%",
            "节拍：≤30 秒/pcs",
        ],
        "competitors": ["竞品 A（报价 320 万）", "竞品 B（报价 380 万）"],
        "key_events": [
            {"date": "2025-11-15", "event": "商机创建"},
            {"date": "2025-12-01", "event": "技术交流"},
            {"date": "2026-01-10", "event": "方案提交"},
            {"date": "2026-02-15", "event": "商务报价"},
            {"date": "2026-03-10", "event": "商务谈判（计划）"},
        ],
    },
    {
        "id": 2,
        "customer_id": 2,
        "customer_name": "比亚迪",
        "name": "EOL 测试设备项目",
        "type": "EOL",
        "stage": "方案确认",
        "amount": 4200000,
        "currency": "CNY",
        "probability": 82,
        "expected_close_date": "2026-03-25",
        "created_at": "2025-10-20",
        "owner_id": 102,
        "owner_name": "李四",
        "description": "EOL 终检设备 5 台，用于新能源汽车电池包检测",
        "requirements": [
            "绝缘测试：0-5000V",
            "耐压测试：0-3000V",
            "功能测试：充放电 + 通讯",
            "自动化程度：全自动",
        ],
        "competitors": ["竞品 A（报价 450 万）"],
        "key_events": [
            {"date": "2025-10-20", "event": "商机创建"},
            {"date": "2025-11-25", "event": "技术交流"},
            {"date": "2026-01-05", "event": "方案确认"},
            {"date": "2026-02-20", "event": "商务谈判"},
            {"date": "2026-03-15", "event": "合同审批（计划）"},
        ],
    },
    {
        "id": 3,
        "customer_id": 3,
        "customer_name": "中创新航",
        "name": "ICT 在线测试项目",
        "type": "ICT",
        "stage": "方案评估",
        "amount": 2800000,
        "currency": "CNY",
        "probability": 58,
        "expected_close_date": "2026-04-15",
        "created_at": "2025-12-10",
        "owner_id": 101,
        "owner_name": "张三",
        "description": "ICT 在线测试设备 4 台，用于 PCBA 测试",
        "requirements": [
            "测试点数：≥2000 点",
            "测试速度：≤15 秒/pcs",
            "支持双面测试",
        ],
        "competitors": ["竞品 A（报价 250 万）", "竞品 B（报价 270 万）", "竞品 C（报价 290 万）"],
        "key_events": [
            {"date": "2025-12-10", "event": "商机创建"},
            {"date": "2026-01-15", "event": "技术交流"},
            {"date": "2026-02-20", "event": "方案提交"},
            {"date": "2026-03-20", "event": "方案评估（计划）"},
        ],
    },
    {
        "id": 4,
        "customer_id": 4,
        "customer_name": "亿纬锂能",
        "name": "烧录设备采购项目",
        "type": "烧录",
        "stage": "商务谈判",
        "amount": 1800000,
        "currency": "CNY",
        "probability": 68,
        "expected_close_date": "2026-04-05",
        "created_at": "2026-01-05",
        "owner_id": 103,
        "owner_name": "王五",
        "description": "MCU 烧录设备 10 台，用于电池管理芯片编程",
        "requirements": [
            "支持芯片：STM32/NXP/瑞萨",
            "烧录速度：≤5 秒/pcs",
            "同时烧录：8 通道",
        ],
        "competitors": ["竞品 A（报价 160 万）"],
        "key_events": [
            {"date": "2026-01-05", "event": "商机创建"},
            {"date": "2026-01-20", "event": "技术交流"},
            {"date": "2026-02-10", "event": "商务报价"},
            {"date": "2026-03-05", "event": "商务谈判（计划）"},
        ],
    },
    {
        "id": 5,
        "customer_id": 5,
        "customer_name": "欣旺达",
        "name": "FCT 功能测试项目",
        "type": "FCT",
        "stage": "需求分析",
        "amount": 3200000,
        "currency": "CNY",
        "probability": 35,
        "expected_close_date": "2026-05-15",
        "created_at": "2026-01-20",
        "owner_id": 104,
        "owner_name": "赵六",
        "description": "FCT 功能测试线 2 条，用于消费电池测试",
        "requirements": ["待确认"],
        "competitors": ["竞品 A", "竞品 B"],
        "key_events": [
            {"date": "2026-01-20", "event": "商机创建"},
            {"date": "2026-02-10", "event": "初步交流"},
            {"date": "2026-03-10", "event": "需求调研（计划）"},
        ],
    },
    {
        "id": 6,
        "customer_id": 6,
        "customer_name": "蜂巢能源",
        "name": "EOL 检测设备项目",
        "type": "EOL",
        "stage": "初步接触",
        "amount": 2500000,
        "currency": "CNY",
        "probability": 28,
        "expected_close_date": "2026-06-30",
        "created_at": "2026-02-01",
        "owner_id": 104,
        "owner_name": "赵六",
        "description": "EOL 检测设备 3 台，用于储能电池包检测",
        "requirements": ["待确认"],
        "competitors": ["竞品 A", "竞品 B", "竞品 C"],
        "key_events": [
            {"date": "2026-02-01", "event": "商机创建"},
            {"date": "2026-02-15", "event": "初步接触"},
            {"date": "2026-03-15", "event": "技术交流（计划）"},
        ],
    },
    {
        "id": 7,
        "customer_id": 7,
        "customer_name": "国轩高科",
        "name": "ICT 测试设备项目",
        "type": "ICT",
        "stage": "线索",
        "amount": 2000000,
        "currency": "CNY",
        "probability": 15,
        "expected_close_date": "2026-08-31",
        "created_at": "2026-02-15",
        "owner_id": 105,
        "owner_name": "钱七",
        "description": "ICT 测试设备采购意向",
        "requirements": ["待确认"],
        "competitors": ["未知"],
        "key_events": [
            {"date": "2026-02-15", "event": "线索创建"},
            {"date": "2026-03-20", "event": "首次拜访（计划）"},
        ],
    },
    {
        "id": 8,
        "customer_id": 8,
        "customer_name": "珠海冠宇",
        "name": "老化测试设备项目",
        "type": "老化",
        "stage": "合同审批",
        "amount": 1500000,
        "currency": "CNY",
        "probability": 88,
        "expected_close_date": "2026-03-20",
        "created_at": "2025-11-01",
        "owner_id": 103,
        "owner_name": "王五",
        "description": "老化测试房 1 间，用于笔记本电脑电池老化测试",
        "requirements": [
            "温度范围：室温~60℃",
            "容量：10000 支电池",
            "监控：实时监控 + 报警",
        ],
        "competitors": ["竞品 A（报价 170 万）"],
        "key_events": [
            {"date": "2025-11-01", "event": "商机创建"},
            {"date": "2025-12-15", "event": "方案确认"},
            {"date": "2026-01-20", "event": "商务谈判"},
            {"date": "2026-02-25", "event": "合同审批"},
            {"date": "2026-03-15", "event": "签约（计划）"},
        ],
    },
]

# ========== 3. 关系成熟度评估数据 ==========

relationship_assessments = [
    {
        "customer_id": 1,
        "customer_name": "宁德时代",
        "assessment_date": "2026-03-01",
        "overall_score": 78,
        "maturity_level": "L4",
        "maturity_level_name": "战略级",
        "dimensions": {
            "decision_chain": {
                "score": 16,
                "max": 20,
                "details": "EB/TB/PB/UB 已覆盖，Coach 已建立",
            },
            "interaction": {"score": 12, "max": 15, "details": "每周 2.8 次，频率良好"},
            "relationship_depth": {
                "score": 14,
                "max": 20,
                "details": "L4 信任级，客户主动分享信息",
            },
            "information": {"score": 13, "max": 15, "details": "预算/流程/时间表清楚"},
            "support": {"score": 16, "max": 20, "details": "TB/UB支持，EB/PB中立"},
            "executive": {"score": 7, "max": 10, "details": "VP 级交流，需提升至 CEO"},
        },
        "estimated_win_rate": 72,
        "trend": "improving",
        "score_change_30d": 5,
    },
    {
        "customer_id": 2,
        "customer_name": "比亚迪",
        "assessment_date": "2026-03-01",
        "overall_score": 85,
        "maturity_level": "L4",
        "maturity_level_name": "战略级",
        "dimensions": {
            "decision_chain": {"score": 19, "max": 20, "details": "决策链完整，Coach 强力支持"},
            "interaction": {"score": 14, "max": 15, "details": "每周 3+ 次，频率很高"},
            "relationship_depth": {"score": 17, "max": 20, "details": "接近 L5 伙伴级"},
            "information": {"score": 14, "max": 15, "details": "信息高度透明"},
            "support": {"score": 18, "max": 20, "details": "EB/TB/PB/UB均支持"},
            "executive": {"score": 8, "max": 10, "details": "CEO 互访过 2 次"},
        },
        "estimated_win_rate": 85,
        "trend": "stable",
        "score_change_30d": 2,
    },
    {
        "customer_id": 3,
        "customer_name": "中创新航",
        "assessment_date": "2026-03-01",
        "overall_score": 62,
        "maturity_level": "L3",
        "maturity_level_name": "成熟级",
        "dimensions": {
            "decision_chain": {"score": 12, "max": 20, "details": "EB/TB/PB已识别，关系待深化"},
            "interaction": {"score": 10, "max": 15, "details": "每周 1-2 次"},
            "relationship_depth": {"score": 12, "max": 20, "details": "L3 认可级"},
            "information": {"score": 11, "max": 15, "details": "部分信息获取"},
            "support": {"score": 12, "max": 20, "details": "UB 支持，其他中立"},
            "executive": {"score": 4, "max": 10, "details": "仅工作层交流"},
        },
        "estimated_win_rate": 52,
        "trend": "improving",
        "score_change_30d": 8,
    },
    {
        "customer_id": 4,
        "customer_name": "亿纬锂能",
        "assessment_date": "2026-03-01",
        "overall_score": 72,
        "maturity_level": "L3",
        "maturity_level_name": "成熟级",
        "dimensions": {
            "decision_chain": {"score": 15, "max": 20, "details": "决策链完整"},
            "interaction": {"score": 11, "max": 15, "details": "每周 1-2 次"},
            "relationship_depth": {"score": 14, "max": 20, "details": "L4 信任级"},
            "information": {"score": 12, "max": 15, "details": "信息较透明"},
            "support": {"score": 14, "max": 20, "details": "EB/TB/UB支持，PB中立"},
            "executive": {"score": 6, "max": 10, "details": "总监级交流"},
        },
        "estimated_win_rate": 65,
        "trend": "stable",
        "score_change_30d": 0,
    },
    {
        "customer_id": 5,
        "customer_name": "欣旺达",
        "assessment_date": "2026-03-01",
        "overall_score": 42,
        "maturity_level": "L2",
        "maturity_level_name": "发展级",
        "dimensions": {
            "decision_chain": {"score": 8, "max": 20, "details": "仅识别 EB/TB"},
            "interaction": {"score": 6, "max": 15, "details": "每 2 周 1 次"},
            "relationship_depth": {"score": 8, "max": 20, "details": "L2 接触级"},
            "information": {"score": 8, "max": 15, "details": "信息有限"},
            "support": {"score": 8, "max": 20, "details": "TB 中立，其他未知"},
            "executive": {"score": 2, "max": 10, "details": "仅工作层"},
        },
        "estimated_win_rate": 32,
        "trend": "declining",
        "score_change_30d": -3,
    },
    {
        "customer_id": 6,
        "customer_name": "蜂巢能源",
        "assessment_date": "2026-03-01",
        "overall_score": 35,
        "maturity_level": "L2",
        "maturity_level_name": "发展级",
        "dimensions": {
            "decision_chain": {"score": 5, "max": 20, "details": "仅识别 EB"},
            "interaction": {"score": 5, "max": 15, "details": "每月 1 次"},
            "relationship_depth": {"score": 8, "max": 20, "details": "L2 接触级"},
            "information": {"score": 6, "max": 15, "details": "信息很少"},
            "support": {"score": 6, "max": 20, "details": "EB 态度未知"},
            "executive": {"score": 2, "max": 10, "details": "仅工作层"},
        },
        "estimated_win_rate": 25,
        "trend": "stable",
        "score_change_30d": 0,
    },
]

# ========== 4. 赢单率综合评估数据 ==========

win_rate_assessments = [
    {
        "opportunity_id": 1,
        "opportunity_name": "宁德时代 FCT 测试线项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 78, "weight": 0.35, "contribution": 27.3},
            "technical_solution": {"score": 81, "weight": 0.30, "contribution": 24.3},
            "price_competitiveness": {"score": 66, "weight": 0.25, "contribution": 16.5},
            "other_factors": {"score": 72, "weight": 0.10, "contribution": 7.2},
        },
        "total_win_rate": 75,
        "confidence": 85,
        "primary_weakness": "价格竞争力",
        "improvement_potential": 6,
    },
    {
        "opportunity_id": 2,
        "opportunity_name": "比亚迪 EOL 测试设备项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 85, "weight": 0.35, "contribution": 29.75},
            "technical_solution": {"score": 88, "weight": 0.30, "contribution": 26.4},
            "price_competitiveness": {"score": 75, "weight": 0.25, "contribution": 18.75},
            "other_factors": {"score": 78, "weight": 0.10, "contribution": 7.8},
        },
        "total_win_rate": 83,
        "confidence": 90,
        "primary_weakness": "无明显短板",
        "improvement_potential": 2,
    },
    {
        "opportunity_id": 3,
        "opportunity_name": "中创新航 ICT 在线测试项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 62, "weight": 0.35, "contribution": 21.7},
            "technical_solution": {"score": 70, "weight": 0.30, "contribution": 21.0},
            "price_competitiveness": {"score": 55, "weight": 0.25, "contribution": 13.75},
            "other_factors": {"score": 58, "weight": 0.10, "contribution": 5.8},
        },
        "total_win_rate": 62,
        "confidence": 75,
        "primary_weakness": "商务关系",
        "improvement_potential": 10,
    },
    {
        "opportunity_id": 4,
        "opportunity_name": "亿纬锂能烧录设备采购项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 72, "weight": 0.35, "contribution": 25.2},
            "technical_solution": {"score": 75, "weight": 0.30, "contribution": 22.5},
            "price_competitiveness": {"score": 60, "weight": 0.25, "contribution": 15.0},
            "other_factors": {"score": 65, "weight": 0.10, "contribution": 6.5},
        },
        "total_win_rate": 69,
        "confidence": 80,
        "primary_weakness": "价格竞争力",
        "improvement_potential": 8,
    },
    {
        "opportunity_id": 5,
        "opportunity_name": "欣旺达 FCT 功能测试项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 42, "weight": 0.35, "contribution": 14.7},
            "technical_solution": {"score": 50, "weight": 0.30, "contribution": 15.0},
            "price_competitiveness": {"score": 55, "weight": 0.25, "contribution": 13.75},
            "other_factors": {"score": 45, "weight": 0.10, "contribution": 4.5},
        },
        "total_win_rate": 48,
        "confidence": 60,
        "primary_weakness": "商务关系",
        "improvement_potential": 15,
    },
    {
        "opportunity_id": 6,
        "opportunity_name": "蜂巢能源 EOL 检测设备项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 35, "weight": 0.35, "contribution": 12.25},
            "technical_solution": {"score": 45, "weight": 0.30, "contribution": 13.5},
            "price_competitiveness": {"score": 50, "weight": 0.25, "contribution": 12.5},
            "other_factors": {"score": 40, "weight": 0.10, "contribution": 4.0},
        },
        "total_win_rate": 42,
        "confidence": 55,
        "primary_weakness": "商务关系",
        "improvement_potential": 18,
    },
    {
        "opportunity_id": 7,
        "opportunity_name": "国轩高科 ICT 测试设备项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 25, "weight": 0.35, "contribution": 8.75},
            "technical_solution": {"score": 35, "weight": 0.30, "contribution": 10.5},
            "price_competitiveness": {"score": 50, "weight": 0.25, "contribution": 12.5},
            "other_factors": {"score": 30, "weight": 0.10, "contribution": 3.0},
        },
        "total_win_rate": 35,
        "confidence": 45,
        "primary_weakness": "商务关系",
        "improvement_potential": 20,
    },
    {
        "opportunity_id": 8,
        "opportunity_name": "珠海冠宇老化测试设备项目",
        "assessment_date": "2026-03-01",
        "factors": {
            "business_relationship": {"score": 82, "weight": 0.35, "contribution": 28.7},
            "technical_solution": {"score": 85, "weight": 0.30, "contribution": 25.5},
            "price_competitiveness": {"score": 78, "weight": 0.25, "contribution": 19.5},
            "other_factors": {"score": 80, "weight": 0.10, "contribution": 8.0},
        },
        "total_win_rate": 82,
        "confidence": 92,
        "primary_weakness": "无明显短板",
        "improvement_potential": 3,
    },
]

# ========== 5. 销售数据 ==========

sales_reps = [
    {
        "id": 101,
        "name": "张三",
        "team": "华南大区",
        "territory": "福建/广东",
        "quota_annual": 50000000,
    },
    {
        "id": 102,
        "name": "李四",
        "team": "华东大区",
        "territory": "江苏/浙江",
        "quota_annual": 45000000,
    },
    {
        "id": 103,
        "name": "王五",
        "team": "华南大区",
        "territory": "广东/广西",
        "quota_annual": 40000000,
    },
    {
        "id": 104,
        "name": "赵六",
        "team": "华东大区",
        "territory": "江苏/安徽",
        "quota_annual": 35000000,
    },
    {
        "id": 105,
        "name": "钱七",
        "team": "华北大区",
        "territory": "安徽/湖北",
        "quota_annual": 30000000,
    },
]

# ========== 输出数据 ==========

output_dir = Path("/Users/flw/non-standard-automation-pm/data/demo")
output_dir.mkdir(parents=True, exist_ok=True)

# 保存为 JSON 文件
files_to_save = [
    ("customers.json", customers),
    ("opportunities.json", opportunities),
    ("relationship_assessments.json", relationship_assessments),
    ("win_rate_assessments.json", win_rate_assessments),
    ("sales_reps.json", sales_reps),
]

for filename, data in files_to_save:
    output_path = output_dir / filename
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ 已生成：{output_path}")

print("")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("📦 演示数据生成完成！")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("")
print(f"📁 数据位置：{output_dir}")
print("")
print("📊 数据概览:")
print(f"  • 客户数据：{len(customers)} 个")
print(f"  • 商机数据：{len(opportunities)} 个")
print(f"  • 关系评估：{len(relationship_assessments)} 个")
print(f"  • 赢单率评估：{len(win_rate_assessments)} 个")
print(f"  • 销售代表：{len(sales_reps)} 个")
print("")
print("💰 商机金额统计:")
total_amount = sum(opp["amount"] for opp in opportunities)
weighted_amount = sum(opp["amount"] * opp["probability"] / 100 for opp in opportunities)
print(f"  • Pipeline 总额：¥{total_amount / 1000000:.1f}M")
print(f"  • 加权 Pipeline: ¥{weighted_amount / 1000000:.1f}M")
print("")
print("🎯 赢单率分布:")
win_rates = [assess["total_win_rate"] for assess in win_rate_assessments]
print(f"  • ≥80%: {sum(1 for r in win_rates if r >= 80)} 个")
print(f"  • 60-79%: {sum(1 for r in win_rates if 60 <= r < 80)} 个")
print(f"  • 40-59%: {sum(1 for r in win_rates if 40 <= r < 60)} 个")
print(f"  • <40%: {sum(1 for r in win_rates if r < 40)} 个")
print("")
