# -*- coding: utf-8 -*-
"""
销售管理模块 ORM 模型 - 兼容层

此文件保持向后兼容性，从拆分后的模块导入所有模型。
原有功能已拆分为 models/sales/ 目录下的模块。
"""

# 从销售模块导入所有模型
from app.models.sales import (  # 线索和商机; 报价相关; 合同相关; 发票相关; 技术评估和需求; 审批工作流和目标
    AIClarification,
    ApprovalHistory,
    ApprovalRecord,
    ApprovalWorkflow,
    ApprovalWorkflowStep,
    Contract,
    ContractAmendment,
    ContractApproval,
    ContractDeliverable,
    ContractTemplate,
    ContractTemplateVersion,
    CpqRuleSet,
    FailureCase,
    Invoice,
    InvoiceApproval,
    Lead,
    LeadFollowUp,
    LeadRequirementDetail,
    MaterialCostUpdateReminder,
    OpenItem,
    Opportunity,
    OpportunityRequirement,
    PurchaseMaterialCost,
    Quote,
    QuoteApproval,
    QuoteCostApproval,
    QuoteCostHistory,
    QuoteCostTemplate,
    QuoteItem,
    QuoteTemplate,
    QuoteTemplateVersion,
    QuoteVersion,
    ReceivableDispute,
    RequirementFreeze,
    SalesRankingConfig,
    SalesTarget,
    ScoringRule,
    TechnicalAssessment,
)

__all__ = [
    "Lead",
    "LeadFollowUp",
    "Opportunity",
    "OpportunityRequirement",
    "Quote",
    "QuoteVersion",
    "QuoteItem",
    "QuoteCostTemplate",
    "QuoteCostApproval",
    "QuoteCostHistory",
    "PurchaseMaterialCost",
    "MaterialCostUpdateReminder",
    "CpqRuleSet",
    "QuoteTemplate",
    "QuoteTemplateVersion",
    "ContractTemplate",
    "ContractTemplateVersion",
    "Contract",
    "ContractDeliverable",
    "ContractAmendment",
    "ContractApproval",
    "Invoice",
    "ReceivableDispute",
    "InvoiceApproval",
    "TechnicalAssessment",
    "ScoringRule",
    "FailureCase",
    "LeadRequirementDetail",
    "RequirementFreeze",
    "OpenItem",
    "AIClarification",
    "QuoteApproval",
    "ApprovalWorkflow",
    "ApprovalWorkflowStep",
    "ApprovalRecord",
    "ApprovalHistory",
    "SalesTarget",
    "SalesRankingConfig",
]
